// gen-gallery.js — generate the screenshot flow + docs data from DEMOS.
//
// Run with bun (it transpiles the demos' JSX on import; jsconfig.json
// points the runtime at solid-js/h so the import resolves — the views
// are never invoked here):
//
//   bun scripts/gen-gallery.js
//
// Emits:
//   .maestro/gallery.yaml            — walk every demo, screenshot each
//   ../../website/docs/components-data.json — per-component docs entries
//
// The screenshot pipeline is scripts/shoot-gallery.sh; the docs page is
// rebuilt from the JSON by website/build-components.mjs.

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { DEMOS } from '../src/demos.jsx';
import { slug } from '../src/slug.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const APP = join(HERE, '..');
const SITE = join(APP, '..', '..', 'website');

// ── .maestro/gallery.yaml ────────────────────────────────────────────
// Screenshot paths are relative to where `maestro test` runs (the
// shoot script cd's into the output dir's parent and passes shots/…).
const steps = DEMOS.flatMap((d, i) => [
  `# ${i + 1}/${DEMOS.length} — ${d.name}`,
  `- takeScreenshot: shots/${String(i).padStart(2, '0')}-${slug(d.name)}`,
  '- tapOn:',
  '    id: "next"',
]);

const flow = `# GENERATED by scripts/gen-gallery.js — do not edit by hand.
# Walks every gallery demo and screenshots it for the docs.
appId: com.example.gallery
---
- launchApp
- extendedWaitUntil:
    visible:
      id: "gallery-title"
    timeout: 20000
${steps.join('\n')}
`;

writeFileSync(join(APP, '.maestro', 'gallery.yaml'), flow);
console.log(`✓ .maestro/gallery.yaml — ${DEMOS.length} demos`);

// ── website/docs/components-data.json ────────────────────────────────
const data = DEMOS.map((d, i) => ({
  name: d.name,
  widget: d.widget,
  group: d.group,
  blurb: d.blurb,
  code: d.code,
  img: `../assets/components/${String(i).padStart(2, '0')}-${slug(d.name)}.png`,
}));
mkdirSync(join(SITE, 'docs'), { recursive: true });
writeFileSync(join(SITE, 'docs', 'components-data.json'), JSON.stringify(data, null, 2) + '\n');
console.log(`✓ website/docs/components-data.json — ${data.length} entries`);
