// Solid universal-renderer adapter for Skal.
//
// Everything imported from this module by user JSX is generated by
// `babel-preset-solid` with `generate: 'universal'`. The babel plugin
// turns `<column>...</column>` into:
//
//   const _$el = createElement('column');
//   insert(_$el, ...);
//
// We map each of those host-tree calls onto bridge ops (CREATE_NODE,
// INSERT_BEFORE, REMOVE_NODE, SET_TEXT, BIND_HANDLER). Solid handles
// reactivity (signals, effects, memos, For, Show, etc.) by composing
// our `effect`/`memo` exports with createSignal & friends from solid-js.

import { createRenderer } from 'solid-js/universal';
import { createEffect } from 'solid-js';
import * as B from './bridge.js';

// Map JSX tag → widget type opcode. Tag names mirror Flutter widget
// names so the layer underneath is unsurprising — `<column>` →
// `Column`, `<listView>` → `ListView`, `<reorderableListView>` →
// `ReorderableListView`, etc.
const TAG_TO_WIDGET = {
  box:                  B.WT_BOX,
  column:               B.WT_COLUMN,
  scrollView:           B.WT_SCROLL_VIEW,
  listView:             B.WT_LIST_VIEW,
  reorderableListView:  B.WT_REORDERABLE_LIST_VIEW,
  row:                  B.WT_ROW,
  // <text label="..." fontSize={...}> — for STYLED text content
  // (font size/weight/color/etc.). For unstyled text, use plain
  // strings as children of any container:
  //   <column>{() => `Count: ${count()}`}</column>
  // The string child is auto-wrapped as an unstyled WT_TEXT leaf.
  text:                 B.WT_TEXT,
  button:               B.WT_BUTTON,
  // <image src="https://..." contentScale={1} cornerRadius={8} /> —
  // a display leaf. `src` accepts http(s):// , file:// , asset:// or
  // a bare asset path. `contentScale` is the BoxFit enum (0=contain,
  // 1=cover, 2=fill, 3=fitWidth, 4=fitHeight, 5=none, 6=scaleDown).
  image:                B.WT_IMAGE,
  // <stack> overlaps children. A child carrying top/right/bottom/left
  // is wrapped in a Positioned by the host.
  stack:                B.WT_STACK,
  // Wave-2 controls. switch/checkbox take `checked` + onChange(bool);
  // slider takes `value`/`min`/`max` + onChange(double); progressBar
  // takes `progress` (0..1, omit for indeterminate).
  switch:               B.WT_SWITCH,
  slider:               B.WT_SLIDER,
  checkbox:             B.WT_CHECKBOX,
  activityIndicator:    B.WT_ACTIVITY_INDICATOR,
  progressBar:          B.WT_PROGRESS_BAR,
  // Wave-3. <lazyGrid> takes crossAxisCount + aspectRatio; <wrap> is
  // a flow layout; <safeArea> insets one child; <richText> styles
  // inline runs via its child <text> nodes.
  lazyGrid:             B.WT_LAZY_GRID,
  wrap:                 B.WT_WRAP,
  safeArea:             B.WT_SAFE_AREA,
  richText:             B.WT_RICH_TEXT,
  // <textInput value=… placeholder=… onChange=… onSubmit=… />
  textInput:            B.WT_TEXT_INPUT,
  // <navigator> stacks <screen> children with native push/pop.
  navigator:            B.WT_NAVIGATOR,
  screen:               B.WT_SCREEN,
  // <tabs> holds <tab> destinations — IndexedStack keep-alive + a
  // bottom NavigationBar. `activeTab` selects; onChange(index) fires.
  tabs:                 B.WT_TABS,
  tab:                  B.WT_TAB,
  // Animation widgets — <animatedList> animates item enter/exit;
  // <crossFade> cross-fades its single child when it swaps; <hero>
  // marks a shared-element for navigator transitions. See ANIMATION.md.
  animatedList:         B.WT_ANIMATED_LIST,
  crossFade:            B.WT_CROSS_FADE,
  hero:                 B.WT_HERO,
  // <listTile title subtitle leadingIcon trailingIcon onTap> — the
  // structured Material row. <pageView> swipes full-page children.
  listTile:             B.WT_LIST_TILE,
  pageView:             B.WT_PAGE_VIEW,
  // <dismissible onDismiss> — swipe its single child away.
  dismissible:          B.WT_DISMISSIBLE,
  // Slivers — <customScrollView> viewport holds <sliverAppBar> /
  // <sliverList> / <sliverGrid> sections (collapsing headers etc.).
  customScrollView:     B.WT_CUSTOM_SCROLL_VIEW,
  sliverAppBar:         B.WT_SLIVER_APP_BAR,
  sliverList:           B.WT_SLIVER_LIST,
  sliverGrid:           B.WT_SLIVER_GRID,
  // <canvas draw={(ctx) => …}> — arbitrary 2-D drawing via CustomPaint.
  canvas:               B.WT_CANVAS,
  // Drag-and-drop — <dragItem> carries dragData; <dropZone onDrop>.
  dragItem:             B.WT_DRAG_ITEM,
  dropZone:             B.WT_DROP_ZONE,
  // §2 controls — radio / chip take checked + onChange; segmentedButton
  // and dropdown take activeTab + onChange; expansionTile takes
  // title + onChange.
  radio:                B.WT_RADIO,
  chip:                 B.WT_CHIP,
  segmentedButton:      B.WT_SEGMENTED_BUTTON,
  expansionTile:        B.WT_EXPANSION_TILE,
  dropdown:             B.WT_DROPDOWN,
  // <stepper> holds <step> children — a multi-step flow. activeTab is
  // the current step; onChange(index) fires on tap / continue / cancel.
  stepper:              B.WT_STEPPER,
  step:                 B.WT_STEP,
  // <drawer> — a slide-in side panel; place it as a <screen> child and
  // the navigator routes it to that screen's Scaffold.drawer slot.
  drawer:               B.WT_DRAWER,
  // <bottomSheet> — a draggable / expandable sheet; place inside a
  // <stack>. initialSize / minSize / maxSize are 0..1 height fractions.
  bottomSheet:          B.WT_BOTTOM_SHEET,
  // §3 polish — <backdropFilter blurRadius> frosts what's behind it
  // (place in a <stack>); <interactiveViewer> pinch-zooms its child.
  backdropFilter:       B.WT_BACKDROP_FILTER,
  interactiveViewer:    B.WT_INTERACTIVE_VIEWER,
  // Shape D-with-holes — <htmlEmbed viewType="…"/> punches a real-DOM
  // rectangle into the Flutter render tree (Flutter Web's
  // HtmlElementView). On native the renderer falls back to a sized
  // placeholder; the use cases (Stripe Elements, OAuth iframes,
  // browser-native form controls) are inherently web-only.
  htmlEmbed:            B.WT_HTML_EMBED,
};

/**
 * Build a recording 2-D context for `<canvas draw>`. Each method
 * appends a paint command to `_cmds`; the renderer JSON-encodes the
 * list and ships it to the host, which replays it onto a Flutter
 * Canvas. Methods are chainable. Colors are parsed to packed u32
 * here (once) so the host never parses a colour string.
 */
function makeCanvasRecorder() {
  const cmds = [];
  const ctx = {
    _cmds: cmds,
    fillStyle(c)        { cmds.push(['fillStyle', parseColor(c)]); return ctx; },
    strokeStyle(c)      { cmds.push(['strokeStyle', parseColor(c)]); return ctx; },
    lineWidth(w)        { cmds.push(['lineWidth', +w || 0]); return ctx; },
    fillRect(x, y, w, h)   { cmds.push(['fillRect', +x, +y, +w, +h]); return ctx; },
    strokeRect(x, y, w, h) { cmds.push(['strokeRect', +x, +y, +w, +h]); return ctx; },
    circle(x, y, r)     { cmds.push(['circle', +x, +y, +r]); return ctx; },
    line(x1, y1, x2, y2){ cmds.push(['line', +x1, +y1, +x2, +y2]); return ctx; },
    beginPath()         { cmds.push(['beginPath']); return ctx; },
    moveTo(x, y)        { cmds.push(['moveTo', +x, +y]); return ctx; },
    lineTo(x, y)        { cmds.push(['lineTo', +x, +y]); return ctx; },
    closePath()         { cmds.push(['closePath']); return ctx; },
    fill()              { cmds.push(['fill']); return ctx; },
    stroke()            { cmds.push(['stroke']); return ctx; },
    fontSize(s)         { cmds.push(['fontSize', +s || 14]); return ctx; },
    fillText(t, x, y)   { cmds.push(['fillText', String(t), +x, +y]); return ctx; },
  };
  return ctx;
}

// ───────────────────────────────────────────────────────────────────────
// JSX attribute → bridge prop mapping
//
// Two flavors:
//   • Cold props (set rarely; map to the typed setPropU32 / F32 / Str
//     helpers, which diff against the last-seen value and skip equal
//     writes). Each entry: [propKey, valueKind].
//   • Hot props (set every frame; map to a dedicated setter that
//     bypasses the cold prop machinery entirely).
//
// valueKind: 'u32' | 'f32' | 'str' | 'color' | 'dim'
//   - color: accepts CSS hex string "#RRGGBB" or "#AARRGGBB", or u32
//   - dim: accepts number (literal dp) or "fill" / "wrap" sentinel
//
// Adding a new prop is one entry here + a matching read in the
// host builder. ~10 lines total.
// ───────────────────────────────────────────────────────────────────────

const COLD_PROPS = {
  // Layout
  padding:        [B.PROP_PADDING,          'u32'],
  paddingTop:     [B.PROP_PADDING_TOP,      'u32'],
  paddingRight:   [B.PROP_PADDING_RIGHT,    'u32'],
  paddingBottom:  [B.PROP_PADDING_BOTTOM,   'u32'],
  paddingLeft:    [B.PROP_PADDING_LEFT,     'u32'],
  width:          [B.PROP_WIDTH,            'dim'],
  height:         [B.PROP_HEIGHT,           'dim'],
  weight:         [B.PROP_WEIGHT,           'f32'],
  alignment:      [B.PROP_ALIGNMENT,        'u32'],
  gap:            [B.PROP_GAP,              'u32'],
  // axis: 0 = vertical (default), 1 = horizontal — for scrollView /
  // listView / reorderableListView. `axis={1}` makes a lazy list scroll
  // sideways (the "lazyRow" use case).
  axis:           [B.PROP_AXIS,             'u32'],
  // Stack-child positioning — set on a child of <stack>. Offsets in dp
  // (negative allowed for overflow). Omit for a non-positioned child.
  top:            [B.PROP_TOP,              'u32'],
  right:          [B.PROP_RIGHT,            'u32'],
  bottom:         [B.PROP_BOTTOM,           'u32'],
  left:           [B.PROP_LEFT,             'u32'],
  // Grid (lazyGrid).
  crossAxisCount: [B.PROP_CROSS_AXIS_COUNT, 'u32'],
  aspectRatio:    [B.PROP_ASPECT_RATIO,     'f32'],
  // Visual
  background:     [B.PROP_BG_COLOR,         'color'],
  color:          [B.PROP_FG_COLOR,         'color'],
  cornerRadius:   [B.PROP_CORNER_RADIUS,    'u32'],
  borderWidth:    [B.PROP_BORDER_WIDTH,     'u32'],
  borderColor:    [B.PROP_BORDER_COLOR,     'color'],
  shadow:         [B.PROP_SHADOW_ELEVATION, 'u32'],
  // Text
  fontSize:       [B.PROP_FONT_SIZE,        'u32'],
  fontWeight:     [B.PROP_FONT_WEIGHT,      'u32'],
  fontFamily:     [B.PROP_FONT_FAMILY,      'u32'],
  textAlign:      [B.PROP_TEXT_ALIGN,       'u32'],
  lineHeight:     [B.PROP_LINE_HEIGHT,      'u32'],
  maxLines:       [B.PROP_MAX_LINES,        'u32'],
  textOverflow:   [B.PROP_TEXT_OVERFLOW,    'u32'],
  // Image
  src:            [B.PROP_IMAGE_SRC,        'str'],
  contentScale:   [B.PROP_CONTENT_SCALE,    'u32'],
  // Input
  placeholder:    [B.PROP_PLACEHOLDER,      'str'],
  value:          [B.PROP_VALUE,            'str'],
  keyboardType:   [B.PROP_KEYBOARD_TYPE,    'u32'],
  secureEntry:    [B.PROP_SECURE_ENTRY,     'u32'],
  // Controls — `checked` for switch/checkbox; `min`/`max` for slider;
  // `progress` for progressBar. (Slider's `value` is handled per-tag
  // in setProperty since the name collides with text inputs.)
  checked:        [B.PROP_CHECKED,          'u32'],
  min:            [B.PROP_SLIDER_MIN,       'f32'],
  max:            [B.PROP_SLIDER_MAX,       'f32'],
  progress:       [B.PROP_PROGRESS,         'f32'],
  // <bottomSheet> extent fractions (0..1) — mount-once config.
  initialSize:    [B.PROP_SHEET_INITIAL,    'f32'],
  minSize:        [B.PROP_SHEET_MIN,        'f32'],
  maxSize:        [B.PROP_SHEET_MAX,        'f32'],
  // Navigation — <screen presentation>: 0 = push, 1 = modal.
  presentation:   [B.PROP_PRESENTATION,     'u32'],
  // <screen title> → AppBar title; <tab title> → nav-bar label.
  title:          [B.PROP_TITLE,            'str'],
  // <tab icon> → nav-bar icon / <listTile leadingIcon> (resolved host-side).
  icon:           [B.PROP_ICON,             'str'],
  leadingIcon:    [B.PROP_ICON,             'str'],
  // <listTile subtitle> → secondary line; <listTile trailingIcon>.
  subtitle:       [B.PROP_SUBTITLE,         'str'],
  trailingIcon:   [B.PROP_TRAILING_ICON,    'str'],
  // <tabs activeTab> → selected index; also <pageView activeTab> page.
  activeTab:      [B.PROP_ACTIVE_TAB,       'u32'],
  // <hero tag> → shared-element transition tag.
  tag:            [B.PROP_HERO_TAG,         'str'],
  // <screen transition> → 0 default, 1 fade, 2 none.
  transition:     [B.PROP_TRANSITION,       'u32'],
  // Behavior
  enabled:        [B.PROP_ENABLED,          'u32'],
  focusable:      [B.PROP_FOCUSABLE,        'u32'],
  visible:        [B.PROP_VISIBLE,          'u32'],
  draggable:      [B.PROP_DRAGGABLE,        'u32'],
  spring:         [B.PROP_SPRING,           'u32'],
  release:        [B.PROP_RELEASE,          'u32'],
  // <sliverAppBar sliverMode> — 0 normal / 1 pinned / 2 floating / 3 both.
  sliverMode:     [B.PROP_SLIVER_MODE,      'u32'],
  // <dragItem dragData> — string id carried to a <dropZone>'s onDrop.
  dragData:       [B.PROP_DRAG_DATA,        'str'],
  // <scrollView scrollbar> / <listView scrollbar> — always-on scrollbar.
  scrollbar:      [B.PROP_SCROLLBAR,        'u32'],
  // <backdropFilter blurRadius> blur sigma; <interactiveViewer> clamps.
  blurRadius:     [B.PROP_BLUR_RADIUS,      'u32'],
  minScale:       [B.PROP_MIN_SCALE,        'f32'],
  maxScale:       [B.PROP_MAX_SCALE,        'f32'],
  // <htmlEmbed viewType="…"/> — string key matching a factory in
  // registerHtmlView(). Mount-once: Flutter Web caches the rendered
  // DOM element for the platform-view's lifetime.
  viewType:       [B.PROP_VIEW_TYPE,        'str'],
  // Accessibility — wraps any widget in a Semantics node.
  semanticLabel:  [B.PROP_SEMANTIC_LABEL,   'str'],
  // Stable E2E test handle — sets the Semantics `identifier` so Maestro
  // (`tapOn: { id }`) / integration_test (`bySemanticsIdentifier`) can target
  // this widget without relying on visible text. See docs/TESTING.md.
  testID:         [B.PROP_TEST_ID,          'str'],
};

const HOT_PROP_SETTERS = {
  opacity:      B.setOpacity,
  translationX: B.setTranslationX,
  translationY: B.setTranslationY,
  scaleX:       B.setScaleX,
  scaleY:       B.setScaleY,
  rotation:     B.setRotationZ,
};

// Function-valued handler props → bridge event kinds. Gesture
// handlers (onClick / onTap / onLongPress / onDoubleTap) wrap the node
// in a GestureDetector on the host; onChange is the value-change
// callback for controls (switch / slider / checkbox).
const HANDLER_EVENTS = {
  onClick:       B.EV_CLICK,
  onclick:       B.EV_CLICK,
  onTap:         B.EV_CLICK,
  onLongPress:   B.EV_LONG_PRESS,
  onDoubleTap:   B.EV_DOUBLE_TAP,
  onChange:      B.EV_CHANGE,
  onSubmit:      B.EV_SUBMIT,
  onReorder:     B.EV_REORDER,
  onPop:         B.EV_NAV_POP,
  // <dismissible onDismiss> — fired when the child is swiped away.
  onDismiss:     B.EV_DISMISS,
  // Pan / drag — onPanUpdate fires every drag frame with a (dx, dy)
  // delta. For "drag this box around" with zero per-frame traffic,
  // use the `draggable` prop instead (the host self-drives translation).
  onPanStart:    B.EV_PAN_START,
  onPanUpdate:   B.EV_PAN_UPDATE,
  onPanEnd:      B.EV_PAN_END,
  // Pinch-scale — onScaleUpdate carries (scale, rotation). A node
  // cannot use scale and pan handlers at once; scale wins on the host.
  onScaleStart:  B.EV_SCALE_START,
  onScaleUpdate: B.EV_SCALE_UPDATE,
  onScaleEnd:    B.EV_SCALE_END,
  // <dropZone onDrop> — a <dragItem> dropped on it; arg is the
  // dropped item's `dragData` string.
  onDrop:        B.EV_DROP,
  // onHover — pointer enter / exit on a container (desktop / web).
  // The handler gets a bool: true on enter, false on exit.
  onHover:       B.EV_HOVER,
  // onKey — a key pressed while the container is focused. The handler
  // gets a normalized combo string ("meta+s", "escape", "arrow up").
  onKey:         B.EV_KEY,
};

// `animate.curve` name → wire enum (mirrors _curveFor in root.dart).
const ANIM_CURVES = {
  linear: 0, easeIn: 1, easeOut: 2, easeInOut: 3,
  bounce: 4, elastic: 5, fastOutSlowIn: 6,
};

// `animate.spring` name → wire enum (mirrors _springFor in root.dart).
const ANIM_SPRINGS = { gentle: 1, bouncy: 2, stiff: 3 };

/**
 * Parse a CSS hex color string to a packed ARGB u32. Accepts:
 *   #RGB / #RGBA / #RRGGBB / #AARRGGBB / #RRGGBBAA
 * Numbers pass through unchanged.
 */
function parseColor(v) {
  if (typeof v === 'number') return v | 0;
  if (typeof v !== 'string') return 0;
  let s = v.trim();
  if (s.startsWith('#')) s = s.slice(1);
  let r = 0, g = 0, b = 0, a = 0xFF;
  if (s.length === 3) {
    r = parseInt(s[0] + s[0], 16);
    g = parseInt(s[1] + s[1], 16);
    b = parseInt(s[2] + s[2], 16);
  } else if (s.length === 4) {
    r = parseInt(s[0] + s[0], 16);
    g = parseInt(s[1] + s[1], 16);
    b = parseInt(s[2] + s[2], 16);
    a = parseInt(s[3] + s[3], 16);
  } else if (s.length === 6) {
    r = parseInt(s.slice(0, 2), 16);
    g = parseInt(s.slice(2, 4), 16);
    b = parseInt(s.slice(4, 6), 16);
  } else if (s.length === 8) {
    // Ambiguous between AARRGGBB and RRGGBBAA. We pick AARRGGBB
    // (matches Dart's Color(0xAARRGGBB) constructor). Users wanting RRGGBBAA
    // should pass the numeric u32 directly.
    a = parseInt(s.slice(0, 2), 16);
    r = parseInt(s.slice(2, 4), 16);
    g = parseInt(s.slice(4, 6), 16);
    b = parseInt(s.slice(6, 8), 16);
  }
  return ((a & 0xFF) << 24 | (r & 0xFF) << 16 | (g & 0xFF) << 8 | (b & 0xFF)) | 0;
}

/**
 * Translate a "dim" prop value to the wire-format u32:
 *   number      → literal dp
 *   "fill"      → FILL_MAX sentinel
 *   "wrap"      → WRAP_CONTENT sentinel
 *   anything else → NO_VALUE (host treats as "no constraint")
 *
 * Important: the fallback is NO_VALUE, not 0. A 0 here would be
 * interpreted by the host's _applyWidth/_applyHeight as `SizedBox(width: 0)` —
 * a zero-width box. NO_VALUE means "fall through to the composable's
 * default modifier."
 */
function parseDim(v) {
  if (typeof v === 'number') return v | 0;
  if (v === 'fill') return B.FILL_MAX;
  if (v === 'wrap') return B.WRAP_CONTENT;
  return B.NO_VALUE;
}

/**
 * Set one prop on a custom (registry-dispatched) node.
 *
 * Built-in widgets dispatch through TAG_TO_WIDGET + COLD_PROPS — each
 * prop has a known u8 key and typed encoding. For custom widgets the
 * renderer can't know the prop names ahead of time (the dev's adapter
 * does), so we dispatch by JS value type:
 *
 *   • function  → name-keyed handler binding (onClick → "onClick", etc.)
 *   • number    → see below
 *   • string    → setCustomPropStr (max 255 bytes)
 *   • boolean   → setCustomPropU32 with 0/1
 *   • null/undef → skipped (mirrors built-in setProperty behavior:
 *                  "leave as previous")
 *
 * Adapters read these back via NodeState.getCustomPropF32(name, fb) etc.
 *
 * The numeric path — the hairy one:
 *
 *   JS has no float/int distinction at the value level. `200.0` and
 *   `200` are identical. But the bridge's `setCustomPropU32` and
 *   `setCustomPropF32` ops write to DIFFERENT maps on the Dart side,
 *   and adapters read from EXACTLY ONE map based on their declared
 *   param type. Mismatch reads as zero/null and the prop silently
 *   doesn't take effect.
 *
 *   We can't always-F32 either: u32 ARGB color values (e.g. 0xFF1DA1F2)
 *   exceed f32's 24-bit mantissa precision, so a Color round-tripped
 *   through F32 comes back wrong.
 *
 *   Correct fix: for integer-valued numbers, write to BOTH maps. The
 *   adapter then reads whichever one matches its param type (U32 for
 *   `int`/`Color`, F32 for `double`). Costs one extra 16-byte op per
 *   integer prop write — negligible at typical UI prop rates.
 *
 *   Fractional values can ONLY be F32 (writing 3.14 to U32 would lose
 *   the fractional part). That's fine: a fractional value in JSX is
 *   always meant for a double param.
 */
// Returns true for values that JSON.stringify into something
// meaningful for the Dart-side parsers — plain `{}` object literals
// and arrays. Rejects class instances, Map, Set, Date, RegExp,
// TypedArrays, etc. The check is structural (prototype = Object's, or
// the rare null-prototype object created via Object.create(null)) so
// it survives realms and bundlers that strip the `Object` global.
function _isJsonShaped(value) {
  if (Array.isArray(value)) return true;
  const proto = Object.getPrototypeOf(value);
  return proto === Object.prototype || proto === null;
}

function _setCustomProperty(node, name, value) {
  if (value == null) return;
  // `ref={someRef}` — bind the SkalRef's nodeId so subsequent
  // `await ref.method()` calls know which host to RPC. SkalRefs
  // expose a hidden `__skalBind` setter that the runtime detects
  // here. Falls through silently for plain object/array values that
  // happen to land on a `ref` prop — those have no encoding today.
  if (name === 'ref' && value && typeof value.__skalBind === 'function') {
    value.__skalBind(node.id);
    return;
  }
  const t = typeof value;
  // Plain-object or array prop values → JSON-stringify, send as a
  // string. Lets codegen-emitted Dart parsers reconstruct complex
  // value types (Gradient, BoxShadow lists, per-side Border, etc.)
  // from a single JSX object literal. The Dart side parses with
  // jsonDecode + a type-specific helper (e.g. _skalParseGradient).
  //
  // Excludes Refs (handled above) and primitives (number/string/
  // boolean → their existing typed paths). Restricts to JSON-shaped
  // values — plain Object literals + Arrays. Map/Set/Date/RegExp/
  // typed arrays all pass `typeof === 'object'` but produce garbage
  // through JSON.stringify (Map → '{}', Set → '{}', etc.); rather
  // than silently writing nonsense to the wire we fall through to
  // the no-op branch so the dev notices the unwrapped value didn't
  // land. Future encodings (Map → object pair list, etc.) can add
  // explicit branches.
  if (t === 'object' && _isJsonShaped(value)) {
    B.setCustomPropStr(node.id, name, JSON.stringify(value));
    B.scheduleCommit();
    return;
  }
  if (t === 'function') {
    const handlerId = B.newHandlerId(value);
    B.bindCustomHandler(node.id, name, handlerId);
    B.scheduleCommit();
    return;
  }
  if (t === 'number') {
    if (Number.isInteger(value) && value >= 0 && value <= 0xFFFFFFFF) {
      // Integer fits in u32 — write to BOTH maps so adapters for `int`
      // or `Color` params read U32 (full precision) AND adapters for
      // `double` params read F32 (with the obvious round-trip).
      B.setCustomPropU32(node.id, name, value | 0);
      B.setCustomPropF32(node.id, name, value);
    } else {
      // Fractional, negative, or > u32 max — can only be F32.
      B.setCustomPropF32(node.id, name, value);
    }
    B.scheduleCommit();
    return;
  }
  if (t === 'string') {
    B.setCustomPropStr(node.id, name, value);
    B.scheduleCommit();
    return;
  }
  if (t === 'boolean') {
    B.setCustomPropU32(node.id, name, value ? 1 : 0);
    B.scheduleCommit();
    return;
  }
  // Other types (objects, arrays) — no native encoding. The adapter
  // can teach itself how to read them via a child-node pattern; from
  // the renderer's POV, silently drop. Logging here would spam during
  // legitimate dev experimentation.
}

/**
 * Walk a SkalNode subtree and release the diff cache row for each.
 * Called from removeNode to keep the diff cache from accumulating stale
 * rows on subtree removal. Iterative DFS — no recursion-depth risk on
 * pathological trees.
 */
function releaseSubtreeDiffCache(root) {
  const stack = [root];
  while (stack.length > 0) {
    const n = stack.pop();
    B.diffCacheReleaseNode(n.id);
    let c = n.firstChild;
    while (c) {
      stack.push(c);
      c = c.nextSibling;
    }
  }
}

/**
 * Host node — a JS-side mirror of a bridge node. Maintains parent/sibling
 * pointers (Solid's universal renderer needs walking via getFirstChild +
 * getNextSibling) and the node's tag.
 *
 * We do NOT mirror the children list as an array — sibling links are the
 * canonical source. Insert/remove keeps both sides (bridge children list
 * + JS sibling pointers) in sync.
 */
class SkalNode {
  constructor(tag, id, isText = false, isCustom = false) {
    this.tag = tag;
    this.id = id;
    this.isText = isText;
    // True for nodes created from a JSX tag NOT in TAG_TO_WIDGET —
    // registry-dispatched on the Flutter side (see SkalRegistry.dart).
    // Prop writes on custom nodes go through the name-keyed
    // setCustomProp* ops instead of the enum-keyed setProp* ops.
    this.isCustom = isCustom;
    this.parent = null;
    this.firstChild = null;
    this.lastChild = null;
    this.nextSibling = null;
    this.prevSibling = null;
    // For text nodes we cache the current value so replaceText can
    // short-circuit when nothing changed (Solid sometimes calls it with
    // the same value during reconciliation).
    this.text = '';
  }
}

const _renderer = createRenderer({
  createElement(tag) {
    const id = B.allocNodeId();
    const wt = TAG_TO_WIDGET[tag];
    if (wt !== undefined) {
      // Built-in widget — fast enum-keyed path.
      B.writeOp(B.OP_CREATE_NODE, id, wt, 0);
      B.scheduleCommit();
      return new SkalNode(tag, id, /*isText*/ false, /*isCustom*/ false);
    }
    // Unknown tag → custom (registry-dispatched on the Flutter side).
    // The wire format carries the name hash; the host's SkalRegistry
    // table maps it to a real Flutter widget builder. No error here —
    // any tag is renderable as long as `SkalRegistry.registerWidget`
    // has been called with this exact `tag` name. If the registration
    // is missing, the host renders a debug placeholder + logs (see
    // root.dart's `_buildCustom`).
    B.createCustomNode(id, tag);
    B.scheduleCommit();
    return new SkalNode(tag, id, /*isText*/ false, /*isCustom*/ true);
  },

  createTextNode(value) {
    const id = B.allocNodeId();
    B.writeOp(B.OP_CREATE_NODE, id, B.WT_TEXT, 0);
    const s = value == null ? '' : String(value);
    if (s.length > 0) B.setText(id, s);
    B.scheduleCommit();
    const node = new SkalNode('#text', id, true);
    node.text = s;
    return node;
  },

  replaceText(textNode, value) {
    const s = value == null ? '' : String(value);
    if (textNode.text === s) return;
    textNode.text = s;
    B.setText(textNode.id, s);
    B.scheduleCommit();
  },

  setProperty(node, name, value, _prev) {
    // Custom (registry-dispatched) nodes: all props are name-keyed.
    // We don't consult COLD_PROPS / HOT_PROPS / `label` — those are
    // for the built-in widget set. Dispatch by JS value type instead.
    if (node.isCustom) {
      _setCustomProperty(node, name, value);
      return;
    }
    // onRefresh — pull-to-refresh. Special-cased (not in HANDLER_EVENTS)
    // because it needs an async wrapper: the host's RefreshIndicator
    // keeps spinning until JS signals completion. We wrap the user's
    // callback so that when its returned Promise resolves (or rejects),
    // `completeRefresh` tells the host to retract the spinner.
    if (name === 'onRefresh') {
      if (typeof value === 'function') {
        const nodeId = node.id;
        const userFn = value;
        const wrapped = async () => {
          try { await userFn(); }
          finally { B.completeRefresh(nodeId); }
        };
        const handlerId = B.newHandlerId(wrapped);
        B.bindHandler(node.id, B.EV_REFRESH, handlerId);
        B.scheduleCommit();
      }
      return;
    }
    // <canvas draw={(ctx) => …}> — record + ship the draw program.
    // Run inside an effect so any signals the draw fn reads are
    // tracked: a data change re-records and re-sends the program. A
    // static drawing (no signal reads) records exactly once. The
    // program rides opSetText — diff-cached, so an unchanged program
    // is a no-op write.
    if (name === 'draw' && typeof value === 'function') {
      const drawFn = value;
      const canvasNode = node;
      createEffect(() => {
        const ctx = makeCanvasRecorder();
        try {
          drawFn(ctx);
        } catch (_) {
          // A throwing draw fn just yields whatever it recorded so far.
        }
        const program = JSON.stringify(ctx._cmds);
        // Diff here: B.setText / opSetText do NOT diff, so a spurious
        // effect re-run (a tracked signal fired but the drawing didn't
        // change) would otherwise write an op and cold-rebuild the
        // canvas node for nothing. Skipping an identical program keeps
        // an unchanged drawing at true zero bridge traffic.
        if (program === canvasNode._skalCanvasProgram) return;
        canvasNode._skalCanvasProgram = program;
        B.setText(canvasNode.id, program);
        B.scheduleCommit();
      });
      return;
    }
    // Handler props (onClick / onTap / onLongPress / onDoubleTap /
    // onChange) — wire to a bridge handler ID under the matching kind.
    const handlerKind = HANDLER_EVENTS[name];
    if (handlerKind !== undefined) {
      if (typeof value === 'function') {
        const handlerId = B.newHandlerId(value);
        B.bindHandler(node.id, handlerKind, handlerId);
        B.scheduleCommit();
      }
      return;
    }

    // <slider value={0.5}> — slider's value is a float, distinct from
    // the string `value` that text inputs use. Dispatch by tag.
    if (name === 'value' && node.tag === 'slider') {
      B.setPropF32(node.id, B.PROP_SLIDER_VALUE, Number(value) || 0);
      B.scheduleCommit();
      return;
    }

    // <box draggable="horizontal"> — accept a friendly string alongside
    // the raw enum. `draggable={true}` and `draggable={1}` (free) still
    // go through the generic COLD_PROPS u32 path below.
    if (name === 'draggable' && typeof value === 'string') {
      const m = { free: 1, both: 1, horizontal: 2, x: 2, vertical: 3, y: 3 };
      B.setPropU32(node.id, B.PROP_DRAGGABLE, m[value] ?? 0);
      B.scheduleCommit();
      return;
    }
    // <box spring="bouncy"> — real SpringSimulation physics on the hot
    // props. `spring={true}` → gentle. Distinct from animate.spring.
    if (name === 'spring' && typeof value === 'string') {
      const m = { gentle: 1, bouncy: 2, stiff: 3, wobbly: 2 };
      B.setPropU32(node.id, B.PROP_SPRING, m[value] ?? 0);
      B.scheduleCommit();
      return;
    }
    // <box draggable release="glide"> — release-physics for a draggable
    // box. `release={true}` → glide (friction decelerate).
    if (name === 'release' && typeof value === 'string') {
      const m = { none: 0, glide: 1, friction: 1, springback: 2, spring: 2 };
      B.setPropU32(node.id, B.PROP_RELEASE, m[value.toLowerCase()] ?? 0);
      B.scheduleCommit();
      return;
    }
    // <sliverAppBar sliverMode="pinned"> — collapsing-header behaviour.
    if (name === 'sliverMode' && typeof value === 'string') {
      const m = { normal: 0, pinned: 1, floating: 2, both: 3 };
      B.setPropU32(node.id, B.PROP_SLIVER_MODE, m[value.toLowerCase()] ?? 0);
      B.scheduleCommit();
      return;
    }

    // animate={{ duration, curve, delay, repeat, reverse, loop, spring }}
    // — turns on implicit animation of this node's hot props (opacity /
    // transform) AND its cold visual/layout props (color, size, radius,
    // padding — see ANIMATION.md §4). A duration of 0 (or omitting
    // `animate`) leaves the node snapping.
    //   repeat  — run the tween forever (a pulse / spin)
    //   reverse — ping-pong each cycle instead of saw-toothing
    //   loop    — cap repeat at N cycles
    //   spring  — 'gentle' | 'bouncy' | 'stiff' physics, overrides curve
    if (name === 'animate' && value && typeof value === 'object') {
      B.setPropU32(node.id, B.PROP_ANIM_DURATION, value.duration | 0);
      if (value.curve != null) {
        const c = typeof value.curve === 'string'
          ? (ANIM_CURVES[value.curve] ?? 0)
          : (value.curve | 0);
        B.setPropU32(node.id, B.PROP_ANIM_CURVE, c);
      }
      if (value.delay != null) {
        B.setPropU32(node.id, B.PROP_ANIM_DELAY, value.delay | 0);
      }
      if (value.repeat != null) {
        B.setPropU32(node.id, B.PROP_ANIM_REPEAT, value.repeat ? 1 : 0);
      }
      if (value.reverse != null) {
        B.setPropU32(node.id, B.PROP_ANIM_REVERSE, value.reverse ? 1 : 0);
      }
      if (value.loop != null) {
        B.setPropU32(node.id, B.PROP_ANIM_LOOP, value.loop | 0);
      }
      if (value.spring != null) {
        const s = typeof value.spring === 'string'
          ? (ANIM_SPRINGS[value.spring] ?? 0)
          : (value.spring ? 2 : 0);
        B.setPropU32(node.id, B.PROP_ANIM_SPRING, s);
      }
      B.scheduleCommit();
      return;
    }
    // <button label="..." /> or <text label="..." /> — set the
    // node's text content. Same OP_SET_TEXT for both; renderer-side
    // semantic is identical (the widget composable consumes
    // `node.text.value`).
    if (name === 'label' &&
        (node.tag === 'button' || node.tag === 'text' || node.tag === 'chip')) {
      const s = value == null ? '' : String(value);
      B.setText(node.id, s);
      B.scheduleCommit();
      return;
    }

    // Hot props — animation-frequency, dedicated opcodes, no full rebuild.
    const hotSetter = HOT_PROP_SETTERS[name];
    if (hotSetter !== undefined) {
      if (typeof value === 'number') {
        hotSetter(node.id, value);
        B.scheduleCommit();
      }
      return;
    }

    // Cold props — typed map via diff-cached setter.
    const coldDesc = COLD_PROPS[name];
    if (coldDesc !== undefined) {
      const [propKey, kind] = coldDesc;
      if (value == null) return; // setting to null/undefined = "leave as previous"
      switch (kind) {
        case 'u32':
          if (typeof value === 'number') {
            B.setPropU32(node.id, propKey, value | 0);
            B.scheduleCommit();
          } else if (typeof value === 'boolean') {
            B.setPropU32(node.id, propKey, value ? 1 : 0);
            B.scheduleCommit();
          }
          return;
        case 'f32':
          if (typeof value === 'number') {
            B.setPropF32(node.id, propKey, value);
            B.scheduleCommit();
          }
          return;
        case 'str':
          B.setPropStr(node.id, propKey, String(value));
          B.scheduleCommit();
          return;
        case 'color':
          B.setPropU32(node.id, propKey, parseColor(value));
          B.scheduleCommit();
          return;
        case 'dim':
          B.setPropU32(node.id, propKey, parseDim(value));
          B.scheduleCommit();
          return;
      }
      return;
    }

    // Style-object form: <box style={{ background, padding, ... }}> —
    // iterate the entries and recursively dispatch through this same
    // function. Lets users co-locate styling without per-attr noise.
    if (name === 'style' && value && typeof value === 'object') {
      for (const key in value) {
        this.setProperty(node, key, value[key]);
      }
      return;
    }

    // Unknown attribute — silently drop. Wire-level openness; renderer-
    // level closedness: the wire format reserves slots for future props,
    // but each renderer only emits the ones it knows. See PROPS_PLAN.md §6.
  },

  insertNode(parent, node, anchor) {
    // Insert-before-self is a no-op — "X stays where it is". Solid's
    // reconcileArrays swap path emits exactly `insertBefore(X, X)` for
    // an adjacent swap; without this guard the bridge detaches X, then
    // fails to find the (just-detached) anchor and appends it.
    if (node === anchor) return;
    // If `node` is already mounted this is a MOVE — detach it from its
    // current sibling links first (DOM insertBefore semantics).
    // Without this the old neighbours keep pointing at it, corrupting
    // the sibling list Solid's reconcileArrays walks to plan moves.
    if (node.parent) {
      const op = node.parent;
      if (node.prevSibling) node.prevSibling.nextSibling = node.nextSibling;
      else if (op.firstChild === node) op.firstChild = node.nextSibling;
      if (node.nextSibling) node.nextSibling.prevSibling = node.prevSibling;
      else if (op.lastChild === node) op.lastChild = node.prevSibling;
      node.prevSibling = null;
      node.nextSibling = null;
    }
    // Bridge op
    const anchorId = anchor ? anchor.id : 0;
    B.writeOp(B.OP_INSERT_BEFORE, parent.id, node.id, anchorId);
    B.scheduleCommit();
    // Local linked-list bookkeeping (keep getFirstChild/getNextSibling fast).
    node.parent = parent;
    if (anchor) {
      node.nextSibling = anchor;
      node.prevSibling = anchor.prevSibling;
      if (anchor.prevSibling) anchor.prevSibling.nextSibling = node;
      else parent.firstChild = node;
      anchor.prevSibling = node;
    } else {
      // Append.
      node.prevSibling = parent.lastChild;
      node.nextSibling = null;
      if (parent.lastChild) parent.lastChild.nextSibling = node;
      else parent.firstChild = node;
      parent.lastChild = node;
    }
  },

  removeNode(parent, node) {
    B.writeOp(B.OP_REMOVE_NODE, node.id, 0, 0);
    // Release the diff cache row(s) for this node and any descendants
    // we know about. The host's _removeSubtree handles the
    // descendants on its side; we mirror that here so the JS-side diff
    // cache doesn't accumulate stale rows over a long session.
    releaseSubtreeDiffCache(node);
    B.scheduleCommit();
    if (node.prevSibling) node.prevSibling.nextSibling = node.nextSibling;
    else parent.firstChild = node.nextSibling;
    if (node.nextSibling) node.nextSibling.prevSibling = node.prevSibling;
    else parent.lastChild = node.prevSibling;
    node.parent = null;
    node.prevSibling = null;
    node.nextSibling = null;
  },

  isTextNode(node) { return node.isText; },
  getParentNode(node) { return node.parent; },
  getFirstChild(node) { return node.firstChild; },
  getNextSibling(node) { return node.nextSibling; },
});

// These are the names babel-preset-solid emits imports for. Re-export
// every entry from createRenderer's return value so JSX desugars cleanly.
export const {
  render,
  effect,
  memo,
  createComponent,
  createElement,
  createTextNode,
  insertNode,
  insert,
  spread,
  setProp,
  mergeProps,
  use,
} = _renderer;

// App-facing imperative API — design system selection + dialogs.
// Re-exported so user code imports it from the same module as the
// renderer.
export {
  setDesign, showDialog, showActionSheet, showSnackbar,
  showDatePicker, showTimePicker,
} from './bridge.js';

// ───────────────────────────────────────────────────────────────────────
// The root host node. Pre-creates the bridge node with id=ROOT_NODE_ID
// (which Flutter's SkalRoot mounts at) and exposes it for Solid's render().
//
// Root is a wt_box — single-child passthrough. The Flutter renderer
// builds a wt_box with one child as just that child, no wrapping
// widget. This lets the App's outer container be ANY widget shape
// (lazy column, scroll column, plain column, …) and have its layout
// constraints come directly from the host's Expanded — no
// intermediate Column to consume them.
//
// Earlier this was wt_scroll_view, which wrapped everything in a
// SingleChildScrollView. That worked when the App used a plain
// <column> but broke once we introduced <listView> — nested
// scrollables of the same axis collapse to height 0 (the inner
// ListView gets unbounded height from the outer scroller and can't
// compute its viewport extent). wt_box avoids the issue by being
// transparent.
// ───────────────────────────────────────────────────────────────────────

B.writeOp(B.OP_CREATE_NODE, B.ROOT_NODE_ID, B.WT_BOX, 0);
B.scheduleCommit();

export const root = new SkalNode('box', B.ROOT_NODE_ID, false);

// ───────────────────────────────────────────────────────────────────────
// Hot reload (native dev) — register THIS generation's mount primitives with
// the coordinator that bridge.js installed on native (see hot.js). On a
// reload the Dart trigger evaluates "__skalHot.beginReload();\n<new bundle>":
// beginReload tears down the outgoing generation via its `reset` (emit the
// host tree-reset + publish synchronously), then this fresh bundle mounts via
// `render`. No-op on web / non-native, where __skalHot is absent and the app
// entry falls back to a plain render().
// ───────────────────────────────────────────────────────────────────────
if (globalThis.__skalHot) {
  globalThis.__skalHot.configure({
    render: (factory) => render(factory, root),
    reset: () => B.resetRootSubtree(),
  });
}
