// Generator — turns a list of target Widget class names + a parsed
// AST view of their source files into Skal adapter source code.
//
// The output shape mirrors a hand-written SkalRegistry.registerWidget
// call (after dart format). Each (Widget class × eligible constructor)
// pair produces one private `_build_X` function and one line inside
// `registerAll()`.
//
// What this generator does NOT do (yet):
//
//   - Walk transitive dependencies / scan whole packages. Caller
//     hands it pre-resolved [ResolvedUnitResult]s; package scanning
//     is the CLI's job.
//   - Handle every non-primitive constructor param. The type mapper
//     returns null for unsupported types (e.g. Gradient, BoxDecoration,
//     TextStyle, raw QrCode objects) — the generator then either
//     silently omits the param (if optional) or skips the whole
//     widget with a warning (if required). See type_mapper.dart for
//     the current supported-type matrix.
//   - Event callbacks beyond what the bridge supports today.
//
// What it does:
//
//   1. For each [ResolvedUnitResult], walk the top-level classes.
//   2. Filter to direct subclasses of StatelessWidget / StatefulWidget
//      (anything not a Widget gets skipped silently — that's fine,
//      package source can include non-widget exports).
//   3. Walk EVERY public constructor — both the default (unnamed) one
//      and any named ctors like `Shimmer.fromColors`. Each ctor
//      becomes its own adapter, exposed to JSX under a synthesized
//      PascalCase name: default ctor keeps the class name verbatim
//      (`Shimmer` → `<Shimmer>`), named ctors concatenate (`Shimmer`
//      + `fromColors` → `<ShimmerFromColors>`). The registry key
//      lowercases the first letter (`shimmerFromColors`). Same
//      manifest shape as before, just more entries.
//   4. For each named parameter, ask the type_mapper for an encoding.
//      If any required param has no encoding, skip the whole widget
//      and record a warning.
//   5. Emit the adapter source.
//
// Output shape:
//
//   // GENERATED by skal_codegen — do not edit by hand.
//   //
//   // Source: <input path>
//
//   import 'package:flutter/material.dart';
//   import 'package:skal_flutter/skal/bridge.dart';
//   ...
//   import '<source>.dart';
//
//   Widget _build_<ClassName>(NodeState n, SkalBridge bridge) {
//     return <ClassName>(
//       <param>: <encoding.readerExpression>,
//       ...
//     );
//   }
//
//   void registerAll() {
//     SkalRegistry.registerWidget('<camelCaseName>', _build_<ClassName>);
//   }

// See type_mapper.dart for the rationale on the experimental warning
// suppression.
// ignore_for_file: experimental_member_use

import 'package:analyzer/dart/analysis/results.dart';
import 'package:analyzer/dart/element/element2.dart';
import 'package:analyzer/dart/element/type.dart';
import 'package:path/path.dart' as p;

import 'type_mapper.dart';

/// A "host adapter" config — the marker file declares one of these
/// per JSX symbol that should be backed by a stateful, controller-
/// owning Dart wrapper rather than a pure props-in-widget-out adapter.
///
/// Used for widgets whose constructor REQUIRES a runtime-constructed
/// controller (CameraController, VideoPlayerController, animation
/// controllers, etc.) — primitives over the bridge can't represent
/// those objects, so codegen synthesizes a StatefulWidget that:
///
///   1. Receives ordinary primitive props from JSX.
///   2. Calls a dev-provided factory function in `initState` to
///      create the controller (sync or async).
///   3. Holds it in State until `dispose()`.
///   4. Disposes the controller cleanly on unmount.
///   5. Renders the underlying widget once the controller is ready.
///
/// One YAML entry → one synthesized `<JsxName>` JSX symbol → one
/// generated `_<JsxName>Host` StatefulWidget under the hood.
class HostConfig {
  /// JSX-facing symbol name (the key in `hosts:` in the marker file).
  /// E.g. `Camera`, which lowers to the registry key `camera` and
  /// renders the synthesized `_CameraHost` StatefulWidget.
  final String jsxName;

  /// The class name of the underlying Widget the host wraps —
  /// resolved by the analyzer below (must be available in the same
  /// scope as the generated adapter, typically via the wrapped pub
  /// package's canonical import).
  final String wrappedWidgetName;

  /// The dev's factory function (returns the controller). Either a
  /// plain `Foo` or a `Future<Foo>` — codegen detects which and
  /// emits `await` accordingly.
  final ExecutableElement2 factoryFn;

  /// Import URI for the factory function — emitted as an `import`
  /// in the generated file so the synthesized `_CameraHost` can call
  /// it. Typically a `package:` URI pointing at a file in the
  /// consumer's project.
  final String factoryImport;

  /// Import URI for the wrapped Widget class — the synthesized
  /// `_CameraHost.build()` constructs it directly, so the import has
  /// to be in scope.
  final String wrappedWidgetImport;

  HostConfig({
    required this.jsxName,
    required this.wrappedWidgetName,
    required this.factoryFn,
    required this.factoryImport,
    required this.wrappedWidgetImport,
  });
}

/// One Widget class the generator considered, with the result of that
/// consideration: emitted code OR a skip reason. Returned alongside
/// the final source so callers can surface warnings to the dev.
class GeneratedWidget {
  final String className;
  final String registryKey;
  final String? skipReason; // null = generated; non-null = skipped

  /// Names of optional constructor params that were unsupported and
  /// thus OMITTED from the generated adapter (the constructor's own
  /// default takes effect). Only populated when [skipReason] is null
  /// — a skipped widget has no per-param breakdown. Useful for the
  /// CLI to tell the dev "QrImageView: 12 props mapped, 3 omitted
  /// (padding, embeddedImage, errorStateBuilder)".
  final List<String> omittedOptionalParams;

  GeneratedWidget(
    this.className,
    this.registryKey, {
    this.skipReason,
    this.omittedOptionalParams = const [],
  });
}

class GenerationResult {
  final String source;
  final List<GeneratedWidget> widgets;

  GenerationResult(this.source, this.widgets);

  /// Widgets that DID make it into the output.
  Iterable<GeneratedWidget> get generated =>
      widgets.where((w) => w.skipReason == null);

  /// Widgets that DIDN'T — name + skip reason for diagnostics.
  Iterable<GeneratedWidget> get skipped =>
      widgets.where((w) => w.skipReason != null);
}

/// Run the generator against [units]. [sourceRelativeImports] is the
/// list of import paths to inline into the generated file's header —
/// typically one per input unit, relative to where the generated file
/// will be written.
///
/// [hosts], if non-empty, declares "host adapters" — synthesized
/// StatefulWidget wrappers that own a controller-typed object for
/// each entry, instead of the usual props-in/widget-out adapter. See
/// [HostConfig] for the full rationale + the emission shape.
GenerationResult generate({
  required List<ResolvedUnitResult> units,
  required List<String> sourceRelativeImports,
  List<HostConfig> hosts = const [],
}) {
  final widgets = <GeneratedWidget>[];
  final adapterBodies = <String>[];
  final registryCalls = <String>[];
  // Extra imports an encoding needs beyond the standard framework
  // imports (e.g. widget-child encoding wants SkalNode from root.dart).
  // Deduped before emission.
  final extraImports = <String>{};

  // Track which units contributed at least one GENERATED widget. Units
  // with no widgets (helper-only files in a multi-file scan) or only
  // skipped widgets don't need to be imported by the generated file —
  // emitting unused imports just produces dead lint warnings in the
  // consumer's project.
  final contributingUnitIdx = <int>{};

  // Classes that have a host config attached. The regular widget walk
  // SKIPS these — otherwise we'd emit a broken `_build_CameraPreview`
  // (the codegen can't encode CameraController) alongside the
  // synthesized `_build_Camera` host. Whoever declared the host owns
  // how the underlying widget gets constructed.
  final hostedWidgetNames = {for (final h in hosts) h.wrappedWidgetName};

  for (var i = 0; i < units.length; i++) {
    final unit = units[i];
    final classes = _topLevelWidgetClasses(unit);
    for (final cls in classes) {
      // Host targets bypass the regular emission. See [hosts] in
      // generate()'s contract: the synthesized host below replaces
      // any auto-generated adapter for the same class.
      if (hostedWidgetNames.contains(cls.name3)) continue;
      final ctors = _eligibleConstructors(cls);
      if (ctors.isEmpty) {
        // Class has no usable constructor (all private, or somehow
        // no constructors at all). Record a skip so the dev sees the
        // class was considered but produced nothing.
        widgets.add(GeneratedWidget(
          cls.name3 ?? '',
          _camelCase(cls.name3 ?? ''),
          skipReason: 'no public constructors',
        ));
        continue;
      }
      for (final ctor in ctors) {
        final result = _emitAdapter(cls, ctor);
        widgets.add(result.summary);
        if (result.body != null) {
          adapterBodies.add(result.body!);
          contributingUnitIdx.add(i);
          extraImports.addAll(result.requiredImports);
        }
        if (result.registryLine != null) {
          registryCalls.add(result.registryLine!);
        }
      }
    }
  }

  // ── Host adapters ─────────────────────────────────────────────────
  //
  // For each declared HostConfig, emit a private StatefulWidget that
  // owns a controller-typed object, plus the `_build_<JsxName>`
  // function the registry calls. The host wraps the underlying widget
  // (cls.name3 == h.wrappedWidgetName) without trying to encode the
  // controller across the bridge.
  //
  // Each host config contributes TWO imports to the generated file:
  // the wrapped widget's package (so we can construct it) and the
  // factory function's file (so we can call it). Both go through
  // [extraImports] for deduplication.
  for (final host in hosts) {
    final result = _emitHostAdapter(host);
    widgets.add(result.summary);
    if (result.body != null) {
      adapterBodies.add(result.body!);
      extraImports.addAll(result.requiredImports);
    }
    if (result.registryLine != null) {
      registryCalls.add(result.registryLine!);
    }
  }

  // Basename-only so the output is stable across machines: a
  // committed generated file shouldn't have an absolute path in
  // its header. Filtered to CONTRIBUTING units (those that produced
  // an adapter) — listing every walked .dart file in a package's
  // lib/ would just be noise.
  final sourceList = [
    for (var i = 0; i < units.length; i++)
      if (contributingUnitIdx.contains(i)) p.basename(units[i].path)
  ].join(', ');
  final buffer = StringBuffer()
    ..writeln('// GENERATED by skal_codegen — do not edit by hand.')
    ..writeln('//')
    ..writeln('// Source: $sourceList')
    ..writeln('//')
    ..writeln('// One adapter per Widget class found in the source. Each adapter reads')
    ..writeln("// its constructor's named parameters from the bridge's custom-prop bag")
    ..writeln('// via NodeState.getCustomPropX(name, default), then constructs the')
    ..writeln("// real Flutter widget. The default value comes from the constructor's")
    ..writeln('// own default — if the JSX consumer omits a prop, they get the same')
    ..writeln('// behaviour as a direct Dart caller would.')
    // Lint suppressions for machine-emitted code. Each is opt-in for a
    // specific generator pattern:
    //
    //   • non_constant_identifier_names — `_build_FooBar` follows the
    //     synthesized symbol name (PascalCase) for traceability,
    //     deliberately not lowerCamelCase.
    //   • sort_child_properties_last — params are emitted in the
    //     CONSTRUCTOR's declared order (so default-value mapping stays
    //     trivial), which can put `child`/`children` before primitive
    //     siblings. Reordering would couple the generator to lint
    //     style rather than to source-of-truth semantics.
    //   • unused_import — unlikely (we filter to contributing units)
    //     but cheap to suppress for resilience against future changes
    //     to that filtering logic.
    ..writeln('//')
    ..writeln('// ignore_for_file: non_constant_identifier_names, '
        'sort_child_properties_last, unused_import')
    ..writeln()
    ..writeln("import 'package:flutter/material.dart';")
    ..writeln("import 'package:skal_flutter/skal/bridge.dart';")
    ..writeln("import 'package:skal_flutter/skal/node_state.dart';")
    ..writeln("import 'package:skal_flutter/skal/registry.dart';");
  // Conditional extra framework imports — one per encoding that
  // requested it. Sorted for deterministic output across runs.
  for (final imp in extraImports.toList()..sort()) {
    buffer.writeln("import '$imp';");
  }
  buffer.writeln();
  // Dedupe imports: when multiple input files come from the same
  // pub-cache package, the CLI maps them all to a single `package:`
  // entry-point URI. Emitting that twice is a Dart compile error.
  final emittedImports = <String>{};
  for (var i = 0; i < sourceRelativeImports.length; i++) {
    if (!contributingUnitIdx.contains(i)) continue;
    final imp = sourceRelativeImports[i];
    if (!emittedImports.add(imp)) continue;
    buffer.writeln("import '$imp';");
  }
  buffer.writeln();

  for (final body in adapterBodies) {
    buffer.writeln(body);
    buffer.writeln();
  }

  buffer.writeln('void registerAll() {');
  for (final line in registryCalls) {
    buffer.writeln('  $line');
  }
  buffer.writeln('}');

  return GenerationResult(buffer.toString(), widgets);
}

class _AdapterResult {
  final GeneratedWidget summary;
  final String? body;
  final String? registryLine;
  /// Aggregated requiredImports from every encoding that contributed
  /// to this adapter's body. Generator-level accumulator pulls these
  /// up + dedupes across all adapters in the file.
  final List<String> requiredImports;
  _AdapterResult(
    this.summary, {
    this.body,
    this.registryLine,
    this.requiredImports = const [],
  });
}

_AdapterResult _emitAdapter(ClassElement2 cls, ConstructorElement2 ctor) {
  final className = cls.name3 ?? '';
  final ctorName = ctor.name3 ?? '';
  final isDefaultCtor = ctorName.isEmpty || ctorName == 'new';

  // JSX-facing symbol. Default ctor: keep the class name (`Shimmer`).
  // Named ctor: concatenate PascalCased (`ShimmerFromColors`). This
  // double-counts a class with both a default AND a named ctor — they
  // get separate JSX symbols + registry keys, which is the point.
  final synthesizedName = isDefaultCtor
      ? className
      : '$className${_pascalCase(ctorName)}';
  final registryKey = _camelCase(synthesizedName);

  // Walk named parameters. Three outcomes per param:
  //
  //   • Supported type → emit a `name: <reader>` line.
  //   • Unsupported, but optional (has a default or is nullable) →
  //     SILENTLY omit. The constructor's own default takes effect.
  //     The dev's JSX can't set this prop, but the widget still works
  //     with sensible defaults from the original Flutter source.
  //   • Unsupported AND required → can't construct the widget without
  //     this param. Skip the whole widget with a clear reason.
  //
  // Tracking [omittedOptionalParams] lets the CLI surface "12 props
  // mapped, 3 omitted (padding, embeddedImage, errorStateBuilder)" so
  // devs know what they can't drive from JSX.
  final lines = <String>[];
  final omittedOptionalParams = <String>[];
  final requiredImports = <String>{};
  String? skipReason;

  for (final param in ctor.formalParameters) {
    if (param.isPositional) continue; // positional params not supported yet
    final name = param.name3;
    if (name == null || name.isEmpty) continue;
    if (name == 'key') continue; // skip Flutter's universal `Key? key`

    // FormalParameterElement exposes the default-value expression
    // both as source text (for types we can paste verbatim — strings,
    // numbers) AND as an evaluated constant value (for types we need
    // to inspect — Color's `.value` int, future enums' index, etc.).
    // The type mapper picks whichever it needs per-type.
    //
    // computeConstantValue() returns null when:
    //   • The parameter has no default (we pass null literal too).
    //   • The default isn't a constant expression (a non-const
    //     factory call etc. — unusual for Widget constructors but
    //     theoretically possible). The mapper falls back to defaults
    //     in that case.
    final defaultLiteral = param.defaultValueCode;
    final defaultConstant = param.computeConstantValue();
    final encoding = encodingFor(
      type: param.type,
      paramName: name,
      defaultLiteral: defaultLiteral,
      defaultConstant: defaultConstant,
    );
    if (encoding == null) {
      // Required = annotated `required this.foo` (no default, no nullable
      // type). If the constructor demands it and we can't encode it,
      // we have to skip the widget — the dev needs a hand-written
      // adapter.
      final isRequired = param.isRequiredNamed && defaultLiteral == null;
      if (isRequired) {
        skipReason = "required param '$name' has unsupported type "
            "'${param.type.getDisplayString()}'";
        break;
      }
      // Optional: silently omit. Track for CLI reporting.
      omittedOptionalParams.add(name);
      continue;
    }
    lines.add('    $name: ${encoding.readerExpression},');
    requiredImports.addAll(encoding.requiredImports);
  }

  if (skipReason != null) {
    return _AdapterResult(
      GeneratedWidget(synthesizedName, registryKey, skipReason: skipReason),
    );
  }

  // Constructor invocation: `Foo(...)` for default, `Foo.bar(...)` for
  // named. The function name uses the synthesized symbol (so a class
  // with multiple ctors gets distinct `_build_Foo` / `_build_FooBar`
  // helpers — no collisions).
  final ctorInvocation = isDefaultCtor ? className : '$className.$ctorName';
  final body = StringBuffer()
    ..writeln(
        'Widget _build_$synthesizedName(NodeState n, SkalBridge bridge) {')
    ..writeln('  return $ctorInvocation(')
    ..writeAll(lines.map((l) => '$l\n'))
    ..writeln('  );')
    ..write('}');

  return _AdapterResult(
    GeneratedWidget(
      synthesizedName,
      registryKey,
      omittedOptionalParams: omittedOptionalParams,
    ),
    body: body.toString(),
    registryLine:
        "SkalRegistry.registerWidget('$registryKey', _build_$synthesizedName);",
    requiredImports: requiredImports.toList(),
  );
}

// ───────────────────────────────────────────────────────────────────────
// Host adapter emission
// ───────────────────────────────────────────────────────────────────────

/// Emit a host adapter for [host]. Produces three artefacts joined in
/// one body string:
///
///   1. `class _<JsxName>Host extends StatefulWidget` — the public
///      Widget subclass that the registry's `_build_*` function
///      returns. Carries the JSX-side props as `final` fields, one per
///      factory-function parameter.
///   2. `class _<JsxName>HostState extends State<_<JsxName>Host>` —
///      owns the controller via a nullable field, calls the factory
///      in `initState`, awaits it if `Future<T>`, disposes the
///      controller on unmount. Render path: SizedBox.shrink while
///      pending, error widget if the factory throws, the wrapped
///      widget once ready.
///   3. `Widget _build_<JsxName>(NodeState, SkalBridge)` — the
///      registry entry point that reads custom props off NodeState and
///      hands them to the StatefulWidget's constructor.
///
/// The wrapped widget is constructed positionally: `WrappedWidget(_ctl!)`.
/// Most "controller-driven viewport" widgets follow this convention
/// (CameraPreview, VideoPlayer). Widgets that take the controller via
/// a named param would need a follow-up extension to HostConfig.
_AdapterResult _emitHostAdapter(HostConfig host) {
  final jsxName = host.jsxName;
  final registryKey = _camelCase(jsxName);
  final wrappedName = host.wrappedWidgetName;

  // Walk the factory function's named params. Each one becomes a
  // `final` field on the host StatefulWidget AND a JSX prop the
  // registry adapter reads off NodeState.
  final fields = <String>[];          // `final String? cameraName;`
  final ctorParams = <String>[];      // `this.cameraName,`
  final factoryCallArgs = <String>[]; // `cameraName: widget.cameraName,`
  final propReaders = <String>[];     // `cameraName: n.getCustomPropStr(...) ?? null,`
  final hostRequiredImports = <String>{
    host.wrappedWidgetImport,
    host.factoryImport,
  };

  for (final param in host.factoryFn.formalParameters) {
    if (param.isPositional) continue;
    final name = param.name3;
    if (name == null || name.isEmpty) continue;

    final defaultLiteral = param.defaultValueCode;
    final defaultConstant = param.computeConstantValue();
    final encoding = encodingFor(
      type: param.type,
      paramName: name,
      defaultLiteral: defaultLiteral,
      defaultConstant: defaultConstant,
    );
    if (encoding == null) {
      // Unsupported factory param type — skip the whole host with a
      // skip reason. The dev needs to use a simpler factory signature
      // or wait for the type to gain encoding support.
      return _AdapterResult(GeneratedWidget(
        jsxName,
        registryKey,
        skipReason: "factory param '$name' has unsupported type "
            "'${param.type.getDisplayString()}'",
      ));
    }
    final typeStr = param.type.getDisplayString();
    fields.add('  final $typeStr $name;');
    ctorParams.add('    this.$name${defaultLiteral != null ? " = $defaultLiteral" : ""},');
    factoryCallArgs.add('        $name: widget.$name,');
    propReaders.add('    $name: ${encoding.readerExpression},');
    hostRequiredImports.addAll(encoding.requiredImports);
  }

  // Detect Future<T> return type — if async, the host's initState
  // awaits the factory; if sync, it just calls it directly. Both
  // paths set the controller field via setState in mounted-check.
  final isAsync = _isFuture(host.factoryFn.returnType);
  final factoryName = host.factoryFn.name3 ?? '';

  final body = StringBuffer()
    ..writeln('class _${jsxName}Host extends StatefulWidget {')
    ..writeAll(fields.map((l) => '$l\n'))
    ..writeln()
    ..writeln('  const _${jsxName}Host({')
    ..writeAll(ctorParams.map((l) => '$l\n'))
    ..writeln('  });')
    ..writeln()
    ..writeln('  @override')
    ..writeln('  State<_${jsxName}Host> createState() => _${jsxName}HostState();')
    ..writeln('}')
    ..writeln()
    ..writeln('class _${jsxName}HostState extends State<_${jsxName}Host> {')
    ..writeln('  Object? _ctl;')
    ..writeln('  Object? _err;')
    ..writeln()
    ..writeln('  @override')
    ..writeln('  void initState() {')
    ..writeln('    super.initState();')
    ..writeln('    _init();')
    ..writeln('  }')
    ..writeln()
    ..writeln('  Future<void> _init() async {')
    ..writeln('    try {')
    ..writeln('      ${isAsync ? "final c = await" : "final c ="} $factoryName(')
    ..writeAll(factoryCallArgs.map((l) => '$l\n'))
    ..writeln('      );')
    ..writeln('      if (!mounted) {')
    ..writeln('        (c as dynamic).dispose();')
    ..writeln('        return;')
    ..writeln('      }')
    ..writeln('      setState(() => _ctl = c);')
    ..writeln('    } catch (e) {')
    ..writeln('      if (mounted) setState(() => _err = e);')
    ..writeln('    }')
    ..writeln('  }')
    ..writeln()
    ..writeln('  @override')
    ..writeln('  void dispose() {')
    ..writeln('    if (_ctl != null) (_ctl as dynamic).dispose();')
    ..writeln('    super.dispose();')
    ..writeln('  }')
    ..writeln()
    ..writeln('  @override')
    ..writeln('  Widget build(BuildContext context) {')
    ..writeln('    if (_err != null) {')
    ..writeln('      return Container(')
    ..writeln('        color: const Color(0xFFFFE0E0),')
    ..writeln('        padding: const EdgeInsets.all(8),')
    ..writeln("        child: Text('$jsxName error: \$_err'),")
    ..writeln('      );')
    ..writeln('    }')
    ..writeln('    if (_ctl == null) return const SizedBox.shrink();')
    ..writeln('    return $wrappedName(_ctl as dynamic);')
    ..writeln('  }')
    ..writeln('}')
    ..writeln()
    ..writeln('Widget _build_$jsxName(NodeState n, SkalBridge bridge) {')
    ..writeln('  return _${jsxName}Host(')
    ..writeAll(propReaders.map((l) => '$l\n'))
    ..writeln('  );')
    ..write('}');

  return _AdapterResult(
    GeneratedWidget(jsxName, registryKey),
    body: body.toString(),
    registryLine:
        "SkalRegistry.registerWidget('$registryKey', _build_$jsxName);",
    requiredImports: hostRequiredImports.toList(),
  );
}

/// True when [t] is `Future<X>` for any X.
bool _isFuture(DartType t) {
  if (t is! InterfaceType) return false;
  if (t.element3.name3 != 'Future') return false;
  final lib = t.element3.library2;
  return lib.isDartAsync;
}

// ───────────────────────────────────────────────────────────────────────
// AST walk helpers
// ───────────────────────────────────────────────────────────────────────

/// Top-level classes in [unit] that look like Widgets — direct
/// (or indirect) subclasses of Widget. Skips abstract classes since
/// they can't be constructed.
///
/// Element2 model note: `libraryElement2.classes` flat-returns every
/// class declared in the library (across all its fragments / `part`
/// files). No more two-level `units.first.classes` walk — the new
/// API exposes the library-level view directly.
List<ClassElement2> _topLevelWidgetClasses(ResolvedUnitResult unit) {
  // Skip "example-app" files: ones with a top-level `void main()`
  // function. Some packages bundle example apps inside `lib/` (e.g.
  // shimmer's `lib/main.dart`) — those files contain MyApp /
  // MyHomePage classes the package itself never exposes as a public
  // widget API. Wrapping them is always a mistake. The void-main
  // check is a precise filter: real library files don't declare a
  // `main` function.
  for (final fn in unit.libraryElement2.topLevelFunctions) {
    if (fn.name3 == 'main') return const [];
  }

  final found = <ClassElement2>[];
  for (final cls in unit.libraryElement2.classes) {
    if (cls.isAbstract) continue;
    // Skip Dart-private classes (leading underscore). These are
    // implementation details — they can't be constructed from
    // outside their library, and codegen-emitted adapters live in
    // a separate library so they couldn't reference them anyway.
    // qr_flutter's `_QrContentView` is the motivating case.
    final name = cls.name3;
    if (name == null || name.startsWith('_')) continue;
    if (!_extendsWidget(cls)) continue;
    found.add(cls);
  }
  return found;
}

bool _extendsWidget(ClassElement2 cls) {
  // Walk the supertype chain looking for Widget / StatelessWidget /
  // StatefulWidget. `allSupertypes` would also work (returns the
  // complete transitive supertype set), but a direct walk via
  // `.supertype` is cheaper and matches the chain order we care
  // about (this class's parent, then grandparent, etc.).
  //
  // In the Element2 model, `InterfaceType.element3` returns an
  // InterfaceElement2 (non-nullable) — no `is` check needed to
  // navigate to the next supertype.
  var t = cls.supertype;
  while (t != null) {
    final el = t.element3;
    final name = el.name3;
    if (name == 'Widget' ||
        name == 'StatelessWidget' ||
        name == 'StatefulWidget') {
      return true;
    }
    t = el.supertype;
  }
  return false;
}

/// "FancyText" → "fancyText". Lowercases the first letter only.
String _camelCase(String pascalCase) {
  if (pascalCase.isEmpty) return pascalCase;
  return pascalCase[0].toLowerCase() + pascalCase.substring(1);
}

/// "fromColors" → "FromColors". Uppercases the first letter only.
/// Used for synthesizing JSX-facing symbols from named-ctor names:
/// `Shimmer` + pascalCase("fromColors") = `ShimmerFromColors`.
String _pascalCase(String camelCase) {
  if (camelCase.isEmpty) return camelCase;
  return camelCase[0].toUpperCase() + camelCase.substring(1);
}

/// Constructors on [cls] that are eligible for adapter emission:
/// public (no leading underscore) and non-redirecting (a redirecting
/// constructor's body is `: this.other(...)` — calling it directly is
/// fine, but calling the eventual target is clearer + avoids
/// double-walking the same parameter list). Returns the default
/// (unnamed) ctor first if present, then named ctors in declaration
/// order — keeps the generated file's ordering stable and predictable.
List<ConstructorElement2> _eligibleConstructors(ClassElement2 cls) {
  final result = <ConstructorElement2>[];
  // Default ctor first.
  for (final c in cls.constructors2) {
    final n = c.name3 ?? '';
    if (n.isEmpty || n == 'new') {
      if (!_isCtorEligible(c)) continue;
      result.add(c);
      break;
    }
  }
  // Then named ctors in source order.
  for (final c in cls.constructors2) {
    final n = c.name3 ?? '';
    if (n.isEmpty || n == 'new') continue;
    if (n.startsWith('_')) continue; // private named ctor
    if (!_isCtorEligible(c)) continue;
    result.add(c);
  }
  return result;
}

bool _isCtorEligible(ConstructorElement2 c) {
  // Skip redirecting generative constructors — they delegate to
  // another ctor and re-encoding the param list twice would emit two
  // adapters that build the same widget. The target ctor (which we
  // also visit) is the canonical entry point.
  if (c.redirectedConstructor2 != null) return false;
  return true;
}
