// Generator — turns a list of target Widget class names + a parsed
// AST view of their source files into Skal adapter source code.
//
// The output matches the hand-written shape from
// `flutter/skal_flutter/lib/adapters/greeting.dart` byte-for-byte
// (after dart format). Each Widget class produces one private
// `_build_X` function and one line inside `registerAll()`.
//
// What this generator does NOT do (yet — Slice 3+):
//
//   - Walk transitive dependencies / scan whole packages. Caller
//     hands it pre-resolved [ResolvedUnitResult]s; package scanning
//     is the CLI's job.
//   - Handle non-primitive constructor params (Widget, List<Widget>,
//     enums, Duration, EdgeInsets). The type mapper returns null for
//     those; the generator skips the whole widget with a warning.
//   - Event callbacks beyond what the bridge supports today.
//
// What it does:
//
//   1. For each [ResolvedUnitResult], walk the top-level classes.
//   2. Filter to direct subclasses of StatelessWidget / StatefulWidget
//      (anything not a Widget gets skipped silently — that's fine,
//      package source can include non-widget exports).
//   3. Find the default constructor (unnamed). Named constructors get
//      ignored — supporting them needs a JSX naming convention we
//      haven't designed yet.
//   4. For each named parameter, ask the type_mapper for an encoding.
//      If any required param has no encoding, skip the whole widget
//      and record a warning.
//   5. Emit the adapter source.
//
// Output shape:
//
//   // GENERATED by skal_codegen — do not edit by hand.
//   //
//   // Source: <input path>
//
//   import 'package:flutter/material.dart';
//   import 'package:skal_flutter/skal/bridge.dart';
//   ...
//   import '<source>.dart';
//
//   Widget _build_<ClassName>(NodeState n, SkalBridge bridge) {
//     return <ClassName>(
//       <param>: <encoding.readerExpression>,
//       ...
//     );
//   }
//
//   void registerAll() {
//     SkalRegistry.registerWidget('<camelCaseName>', _build_<ClassName>);
//   }

// See type_mapper.dart for the rationale on the experimental warning
// suppression.
// ignore_for_file: experimental_member_use

import 'package:analyzer/dart/analysis/results.dart';
import 'package:analyzer/dart/element/element2.dart';
import 'package:path/path.dart' as p;

import 'type_mapper.dart';

/// One Widget class the generator considered, with the result of that
/// consideration: emitted code OR a skip reason. Returned alongside
/// the final source so callers can surface warnings to the dev.
class GeneratedWidget {
  final String className;
  final String registryKey;
  final String? skipReason; // null = generated; non-null = skipped

  /// Names of optional constructor params that were unsupported and
  /// thus OMITTED from the generated adapter (the constructor's own
  /// default takes effect). Only populated when [skipReason] is null
  /// — a skipped widget has no per-param breakdown. Useful for the
  /// CLI to tell the dev "QrImageView: 12 props mapped, 3 omitted
  /// (padding, embeddedImage, errorStateBuilder)".
  final List<String> omittedOptionalParams;

  GeneratedWidget(
    this.className,
    this.registryKey, {
    this.skipReason,
    this.omittedOptionalParams = const [],
  });
}

class GenerationResult {
  final String source;
  final List<GeneratedWidget> widgets;

  GenerationResult(this.source, this.widgets);

  /// Widgets that DID make it into the output.
  Iterable<GeneratedWidget> get generated =>
      widgets.where((w) => w.skipReason == null);

  /// Widgets that DIDN'T — name + skip reason for diagnostics.
  Iterable<GeneratedWidget> get skipped =>
      widgets.where((w) => w.skipReason != null);
}

/// Run the generator against [units]. [sourceRelativeImports] is the
/// list of import paths to inline into the generated file's header —
/// typically one per input unit, relative to where the generated file
/// will be written.
GenerationResult generate({
  required List<ResolvedUnitResult> units,
  required List<String> sourceRelativeImports,
}) {
  final widgets = <GeneratedWidget>[];
  final adapterBodies = <String>[];
  final registryCalls = <String>[];

  // Track which units contributed at least one GENERATED widget. Units
  // with no widgets (helper-only files in a multi-file scan) or only
  // skipped widgets don't need to be imported by the generated file —
  // emitting unused imports just produces dead lint warnings in the
  // consumer's project.
  final contributingUnitIdx = <int>{};

  for (var i = 0; i < units.length; i++) {
    final unit = units[i];
    final classes = _topLevelWidgetClasses(unit);
    for (final cls in classes) {
      final result = _emitAdapter(cls);
      widgets.add(result.summary);
      if (result.body != null) {
        adapterBodies.add(result.body!);
        contributingUnitIdx.add(i);
      }
      if (result.registryLine != null) {
        registryCalls.add(result.registryLine!);
      }
    }
  }

  // Basename-only so the output is stable across machines: a
  // committed generated file shouldn't have an absolute path in
  // its header. Filtered to CONTRIBUTING units (those that produced
  // an adapter) — listing every walked .dart file in a package's
  // lib/ would just be noise.
  final sourceList = [
    for (var i = 0; i < units.length; i++)
      if (contributingUnitIdx.contains(i)) p.basename(units[i].path)
  ].join(', ');
  final buffer = StringBuffer()
    ..writeln('// GENERATED by skal_codegen — do not edit by hand.')
    ..writeln('//')
    ..writeln('// Source: $sourceList')
    ..writeln('//')
    ..writeln('// One adapter per Widget class found in the source. Each adapter reads')
    ..writeln("// its constructor's named parameters from the bridge's custom-prop bag")
    ..writeln('// via NodeState.getCustomPropX(name, default), then constructs the')
    ..writeln("// real Flutter widget. The default value comes from the constructor's")
    ..writeln('// own default — if the JSX consumer omits a prop, they get the same')
    ..writeln('// behaviour as a direct Dart caller would.')
    ..writeln()
    ..writeln("import 'package:flutter/material.dart';")
    ..writeln("import 'package:skal_flutter/skal/bridge.dart';")
    ..writeln("import 'package:skal_flutter/skal/node_state.dart';")
    ..writeln("import 'package:skal_flutter/skal/registry.dart';")
    ..writeln();
  // Dedupe imports: when multiple input files come from the same
  // pub-cache package, the CLI maps them all to a single `package:`
  // entry-point URI. Emitting that twice is a Dart compile error.
  final emittedImports = <String>{};
  for (var i = 0; i < sourceRelativeImports.length; i++) {
    if (!contributingUnitIdx.contains(i)) continue;
    final imp = sourceRelativeImports[i];
    if (!emittedImports.add(imp)) continue;
    buffer.writeln("import '$imp';");
  }
  buffer.writeln();

  for (final body in adapterBodies) {
    buffer.writeln(body);
    buffer.writeln();
  }

  buffer.writeln('void registerAll() {');
  for (final line in registryCalls) {
    buffer.writeln('  $line');
  }
  buffer.writeln('}');

  return GenerationResult(buffer.toString(), widgets);
}

class _AdapterResult {
  final GeneratedWidget summary;
  final String? body;
  final String? registryLine;
  _AdapterResult(this.summary, {this.body, this.registryLine});
}

_AdapterResult _emitAdapter(ClassElement2 cls) {
  final className = cls.name3 ?? '';
  final registryKey = _camelCase(className);

  // Find the default (unnamed) constructor. In the Element2 model
  // it's `constructors2` (returning ConstructorElement2 instances);
  // the unnamed constructor's `name3` is the empty string, same as
  // the old API.
  final ctor = cls.constructors2.firstWhere(
    (c) => c.name3 == '' || c.name3 == 'new',
    orElse: () => throw StateError(
        'no default constructor on $className — codegen MVP requires one'),
  );

  // Walk named parameters. Three outcomes per param:
  //
  //   • Supported type → emit a `name: <reader>` line.
  //   • Unsupported, but optional (has a default or is nullable) →
  //     SILENTLY omit. The constructor's own default takes effect.
  //     The dev's JSX can't set this prop, but the widget still works
  //     with sensible defaults from the original Flutter source.
  //   • Unsupported AND required → can't construct the widget without
  //     this param. Skip the whole widget with a clear reason.
  //
  // Tracking [omittedOptionalParams] lets the CLI surface "12 props
  // mapped, 3 omitted (padding, embeddedImage, errorStateBuilder)" so
  // devs know what they can't drive from JSX.
  final lines = <String>[];
  final omittedOptionalParams = <String>[];
  String? skipReason;

  for (final param in ctor.formalParameters) {
    if (param.isPositional) continue; // positional params not supported yet
    final name = param.name3;
    if (name == null || name.isEmpty) continue;
    if (name == 'key') continue; // skip Flutter's universal `Key? key`

    // FormalParameterElement exposes the default-value expression
    // both as source text (for types we can paste verbatim — strings,
    // numbers) AND as an evaluated constant value (for types we need
    // to inspect — Color's `.value` int, future enums' index, etc.).
    // The type mapper picks whichever it needs per-type.
    //
    // computeConstantValue() returns null when:
    //   • The parameter has no default (we pass null literal too).
    //   • The default isn't a constant expression (a non-const
    //     factory call etc. — unusual for Widget constructors but
    //     theoretically possible). The mapper falls back to defaults
    //     in that case.
    final defaultLiteral = param.defaultValueCode;
    final defaultConstant = param.computeConstantValue();
    final encoding = encodingFor(
      type: param.type,
      paramName: name,
      defaultLiteral: defaultLiteral,
      defaultConstant: defaultConstant,
    );
    if (encoding == null) {
      // Required = annotated `required this.foo` (no default, no nullable
      // type). If the constructor demands it and we can't encode it,
      // we have to skip the widget — the dev needs a hand-written
      // adapter.
      final isRequired = param.isRequiredNamed && defaultLiteral == null;
      if (isRequired) {
        skipReason = "required param '$name' has unsupported type "
            "'${param.type.getDisplayString()}'";
        break;
      }
      // Optional: silently omit. Track for CLI reporting.
      omittedOptionalParams.add(name);
      continue;
    }
    lines.add('    $name: ${encoding.readerExpression},');
  }

  if (skipReason != null) {
    return _AdapterResult(
      GeneratedWidget(className, registryKey, skipReason: skipReason),
    );
  }

  final body = StringBuffer()
    ..writeln('Widget _build_$className(NodeState n, SkalBridge bridge) {')
    ..writeln('  return $className(')
    ..writeAll(lines.map((l) => '$l\n'))
    ..writeln('  );')
    ..write('}');

  return _AdapterResult(
    GeneratedWidget(
      className,
      registryKey,
      omittedOptionalParams: omittedOptionalParams,
    ),
    body: body.toString(),
    registryLine:
        "SkalRegistry.registerWidget('$registryKey', _build_$className);",
  );
}

// ───────────────────────────────────────────────────────────────────────
// AST walk helpers
// ───────────────────────────────────────────────────────────────────────

/// Top-level classes in [unit] that look like Widgets — direct
/// (or indirect) subclasses of Widget. Skips abstract classes since
/// they can't be constructed.
///
/// Element2 model note: `libraryElement2.classes` flat-returns every
/// class declared in the library (across all its fragments / `part`
/// files). No more two-level `units.first.classes` walk — the new
/// API exposes the library-level view directly.
List<ClassElement2> _topLevelWidgetClasses(ResolvedUnitResult unit) {
  final found = <ClassElement2>[];
  for (final cls in unit.libraryElement2.classes) {
    if (cls.isAbstract) continue;
    // Skip Dart-private classes (leading underscore). These are
    // implementation details — they can't be constructed from
    // outside their library, and codegen-emitted adapters live in
    // a separate library so they couldn't reference them anyway.
    // qr_flutter's `_QrContentView` is the motivating case.
    final name = cls.name3;
    if (name == null || name.startsWith('_')) continue;
    if (!_extendsWidget(cls)) continue;
    found.add(cls);
  }
  return found;
}

bool _extendsWidget(ClassElement2 cls) {
  // Walk the supertype chain looking for Widget / StatelessWidget /
  // StatefulWidget. `allSupertypes` would also work (returns the
  // complete transitive supertype set), but a direct walk via
  // `.supertype` is cheaper and matches the chain order we care
  // about (this class's parent, then grandparent, etc.).
  //
  // In the Element2 model, `InterfaceType.element3` returns an
  // InterfaceElement2 (non-nullable) — no `is` check needed to
  // navigate to the next supertype.
  var t = cls.supertype;
  while (t != null) {
    final el = t.element3;
    final name = el.name3;
    if (name == 'Widget' ||
        name == 'StatelessWidget' ||
        name == 'StatefulWidget') {
      return true;
    }
    t = el.supertype;
  }
  return false;
}

/// "FancyText" → "fancyText". Lowercases the first letter only.
String _camelCase(String pascalCase) {
  if (pascalCase.isEmpty) return pascalCase;
  return pascalCase[0].toLowerCase() + pascalCase.substring(1);
}
