package com.skal.bridge

import java.nio.ByteBuffer

/**
 * JVM `actual` for [SkalBuffer] — thin wrapper over `java.nio.ByteBuffer`.
 *
 * The wrapper exists (rather than `actual typealias SkalBuffer = ByteBuffer`)
 * so the byte-order contract is encoded as a runtime invariant: callers
 * get a [SkalBuffer] only via [com.skal.SkalRuntime.acquireBridge], and
 * the only constructor of that path is `SkalJvm.acquireBridge` which
 * pre-sets `LITTLE_ENDIAN`. A typealias would let callers construct
 * `SkalBuffer(ByteBuffer.allocate(N))` and forget the byte order.
 *
 * All methods are thin forwards — the JIT inlines them on hot paths
 * (verified by checking the generated bytecode is `INVOKEINTERFACE` on
 * the underlying ByteBuffer methods, which Hotspot devirtualizes when
 * the receiver type is monomorphic).
 */
actual class SkalBuffer(internal val backing: ByteBuffer) {
    actual fun getInt(index: Int): Int = backing.getInt(index)

    actual fun getLong(index: Int): Long = backing.getLong(index)

    actual fun getByte(index: Int): Byte = backing.get(index)

    actual fun copyToByteArray(dst: ByteArray, srcOffset: Int, length: Int) {
        // ByteBuffer's bulk get is positional; set the cursor, then bulk
        // copy. pumpOps is the only caller and is single-threaded (UI),
        // so the position-mutation is safe.
        backing.position(srcOffset)
        backing.get(dst, 0, length)
    }

    actual fun putByte(index: Int, value: Byte) {
        backing.put(index, value)
    }

    actual fun putInt(index: Int, value: Int) {
        backing.putInt(index, value)
    }

    actual fun putLong(index: Int, value: Long) {
        backing.putLong(index, value)
    }
}
