// skal-qr-flutter — Skal adapter module for the third-party
// `qr_flutter` pub.dev package.
//
// The Dart-side adapter is generated by `skal_codegen` running against
// the package's QrImageView class:
//
//   $ cd flutter/skal_flutter
//   $ dart run ../../codegen/skal_codegen/bin/skal_codegen.dart \
//       ~/.pub-cache/hosted/pub.dev/qr_flutter-4.1.0/lib/src/qr_image_view.dart \
//       -o lib/adapters/generated/qr_flutter.g.dart
//
// This module is the JS-side companion: it provides the `QrImageView`
// symbol so JSX can `import { QrImageView } from 'skal-qr-flutter'`,
// the babel macro recognizes it via the vite.config.js `modules`
// entry, and lowers `<QrImageView ...>` to the `<qrImageView>`
// intrinsic tag at compile time.
//
// Real-world packaging: in production this would be a published npm
// package alongside a pub.dev `skal_qr_flutter` adapter. For the
// demo it sits in the tree.
//
// PROPS QUIRK — temporary, fixed in a follow-up:
//
//   `size` in qr_flutter is `double?`. The bridge's JS-side number
//   dispatch puts integer-looking JSX values onto the U32 wire path,
//   but the generator emits `getCustomPropF32('size', 0.0)` for
//   double params. Mismatched: <QrImageView size={200}> stores u32,
//   adapter reads f32, gets 0.0 fallback, renders zero-sized.
//
//   Workaround: pass an explicit float, `size={200.0}`. The JSX-side
//   `.0` forces JS to treat it as a float, which lands on the F32 wire
//   path and the adapter reads it correctly.
//
//   The real fix (next commit): always use F32 for numeric custom
//   props on the JS side, generator emits `.toInt()` for int params.

function makeMissingMacroComponent(name) {
  return function _skalMissingMacro() {
    throw new Error(
      `skal-qr-flutter: <${name}> was used without the babel-plugin-skal-jsx ` +
      `transform recognizing this module. Add 'skal-qr-flutter' to the ` +
      `plugin's \`modules\` option in vite.config.js.`
    );
  };
}

/**
 * @typedef {Object} QrImageViewProps Reflects the constructor params
 *   the codegen mapped for `QrImageView`. Omitted: padding,
 *   errorStateBuilder, embeddedImage, embeddedImageStyle, eyeStyle,
 *   dataModuleStyle (complex types not yet supported by codegen). To
 *   set those, write a manual adapter overriding the generated one.
 *
 * @property {string} [data]                 the string to encode
 * @property {number} [size]                 square size in px — pass as
 *   `{200.0}` (with `.0`) until the JS-int-dispatch fix lands
 * @property {string | number} [backgroundColor]   ARGB hex or u32
 * @property {string | number} [foregroundColor]
 * @property {number} [version]              QrVersions.auto = -1
 * @property {number} [errorCorrectionLevel] QrErrorCorrectLevel.L = 0
 * @property {boolean} [constrainErrorBounds]
 * @property {boolean} [gapless]
 * @property {string} [semanticsLabel]
 * @property {boolean} [embeddedImageEmitsError]
 */

/**
 * QR code renderer (Flutter `QrImageView` from the qr_flutter package).
 * Wraps a real third-party widget — codegen generated the Dart-side
 * adapter automatically by introspecting QrImageView's constructor.
 *
 * @type {(props: QrImageViewProps) => import('solid-js').JSX.Element}
 */
export const QrImageView = makeMissingMacroComponent('QrImageView');
