// GENERATED by skal_codegen — do not edit by hand.
//
// Source: complex_types.dart
//
// One adapter per Widget class found in the source. Each adapter reads
// its constructor's named parameters from the bridge's custom-prop bag
// via NodeState.getCustomPropX(name, default), then constructs the
// real Flutter widget. The default value comes from the constructor's
// own default — if the JSX consumer omits a prop, they get the same
// behaviour as a direct Dart caller would.
//
// ignore_for_file: non_constant_identifier_names, sort_child_properties_last, unused_import, deprecated_member_use

import 'package:flutter/material.dart';
import 'package:skal_flutter/skal/bridge.dart';
import 'package:skal_flutter/skal/node_state.dart';
import 'package:skal_flutter/skal/registry.dart';

import 'complex_types.dart';

Widget _build_Banner(NodeState n, SkalBridge bridge) {
  return Banner(
    message: n.getCustomPropStr('message') ?? '',
    style: BannerStyle.values[n.getCustomPropU32('style', 0)],
    dismissAfter: Duration(
      milliseconds: n.getCustomPropU32('dismissAfter', 500),
    ),
    padding: EdgeInsets.fromLTRB(
      n.getCustomPropF32('paddingLeft', 4.0),
      n.getCustomPropF32('paddingTop', 8.0),
      n.getCustomPropF32('paddingRight', 4.0),
      n.getCustomPropF32('paddingBottom', 8.0),
    ),
  );
}

void registerAll() {
  SkalRegistry.registerWidget('banner', _build_Banner);
}
