// GENERATED by skal_codegen — do not edit by hand.
//
// Source: 
//
// One adapter per Widget class found in the source. Each adapter reads
// its constructor's named parameters from the bridge's custom-prop bag
// via NodeState.getCustomPropX(name, default), then constructs the
// real Flutter widget. The default value comes from the constructor's
// own default — if the JSX consumer omits a prop, they get the same
// behaviour as a direct Dart caller would.
//
// ignore_for_file: non_constant_identifier_names, sort_child_properties_last, unused_import

import 'package:flutter/material.dart';
import 'package:skal_flutter/skal/bridge.dart';
import 'package:skal_flutter/skal/node_state.dart';
import 'package:skal_flutter/skal/registry.dart';
import '_fake_flutter.dart';
import 'host.dart';


class _FakeSyncHost extends StatefulWidget {
  final NodeState n;
  final int initial;

  const _FakeSyncHost({
    required this.n,
    this.initial = 0,
  });

  @override
  State<_FakeSyncHost> createState() => _FakeSyncHostState();
}

class _FakeSyncHostState extends State<_FakeSyncHost> {
  Object? _ctl;
  Object? _err;

  @override
  void initState() {
    super.initState();
    widget.n.methodDispatcher = _dispatch;
    _init();
  }

  Future<void> _init() async {
    try {
      final c = makeFakeViewerSync(
        initial: widget.initial,
      );
      if (!mounted) {
        (c as dynamic).dispose();
        return;
      }
      setState(() => _ctl = c);
    } catch (e) {
      if (mounted) setState(() => _err = e);
    }
  }

  @override
  void dispose() {
    widget.n.methodDispatcher = null;
    if (_ctl != null) (_ctl as dynamic).dispose();
    super.dispose();
  }

  Object? _dispatch(String method, List<Object?> args) {
    if (_ctl == null) return null;
    final ctl = _ctl as FakeController;
    switch (method) {
      case 'bump':
        ctl.bump(args[0] as int);
        return null;
      case 'reset':
        ctl.reset();
        return null;
      case 'getValue':
        return ctl.getValue();
      case 'ping':
        return ctl.ping();
      case 'describe':
        return ctl.describe(args[0] as String);
      default:
        return null;
    }
  }

  @override
  Widget build(BuildContext context) {
    if (_err != null) {
      return Container(
        color: const Color(0xFFFFE0E0),
        padding: const EdgeInsets.all(8),
        child: Text('FakeSync error: $_err'),
      );
    }
    if (_ctl == null) return const SizedBox.shrink();
    return FakeViewer(_ctl as dynamic);
  }
}

Widget _build_FakeSync(NodeState n, SkalBridge bridge) {
  return _FakeSyncHost(
    n: n,
    initial: n.getCustomPropU32('initial', 0),
  );
}

class _FakeAsyncHost extends StatefulWidget {
  final NodeState n;
  final int initial;

  const _FakeAsyncHost({
    required this.n,
    this.initial = 7,
  });

  @override
  State<_FakeAsyncHost> createState() => _FakeAsyncHostState();
}

class _FakeAsyncHostState extends State<_FakeAsyncHost> {
  Object? _ctl;
  Object? _err;

  @override
  void initState() {
    super.initState();
    widget.n.methodDispatcher = _dispatch;
    _init();
  }

  Future<void> _init() async {
    try {
      final c = await makeFakeViewerAsync(
        initial: widget.initial,
      );
      if (!mounted) {
        (c as dynamic).dispose();
        return;
      }
      setState(() => _ctl = c);
    } catch (e) {
      if (mounted) setState(() => _err = e);
    }
  }

  @override
  void dispose() {
    widget.n.methodDispatcher = null;
    if (_ctl != null) (_ctl as dynamic).dispose();
    super.dispose();
  }

  Object? _dispatch(String method, List<Object?> args) {
    if (_ctl == null) return null;
    final ctl = _ctl as FakeController;
    switch (method) {
      case 'bump':
        ctl.bump(args[0] as int);
        return null;
      case 'reset':
        ctl.reset();
        return null;
      case 'getValue':
        return ctl.getValue();
      case 'ping':
        return ctl.ping();
      case 'describe':
        return ctl.describe(args[0] as String);
      default:
        return null;
    }
  }

  @override
  Widget build(BuildContext context) {
    if (_err != null) {
      return Container(
        color: const Color(0xFFFFE0E0),
        padding: const EdgeInsets.all(8),
        child: Text('FakeAsync error: $_err'),
      );
    }
    if (_ctl == null) return const SizedBox.shrink();
    return FakeViewer(_ctl as dynamic);
  }
}

Widget _build_FakeAsync(NodeState n, SkalBridge bridge) {
  return _FakeAsyncHost(
    n: n,
    initial: n.getCustomPropU32('initial', 7),
  );
}

void registerAll() {
  SkalRegistry.registerWidget('fakeSync', _build_FakeSync);
  SkalRegistry.registerWidget('fakeAsync', _build_FakeAsync);
}
