// GENERATED by skal_codegen — do not edit by hand.
//
// Source: badge.dart, panel.dart
//
// One adapter per Widget class found in the source. Each adapter reads
// its constructor's named parameters from the bridge's custom-prop bag
// via NodeState.getCustomPropX(name, default), then constructs the
// real Flutter widget. The default value comes from the constructor's
// own default — if the JSX consumer omits a prop, they get the same
// behaviour as a direct Dart caller would.

import 'package:flutter/material.dart';
import 'package:skal_flutter/skal/bridge.dart';
import 'package:skal_flutter/skal/node_state.dart';
import 'package:skal_flutter/skal/registry.dart';

import 'mini_pack/badge.dart';
import 'mini_pack/panel.dart';

Widget _build_Badge(NodeState n, SkalBridge bridge) {
  return Badge(
    text: n.getCustomPropStr('text') ?? 'New',
    color: Color(n.getCustomPropU32('color', 0xFFFF0000)),
    count: n.getCustomPropU32('count', 0),
  );
}

Widget _build_Panel(NodeState n, SkalBridge bridge) {
  return Panel(
    title: n.getCustomPropStr('title') ?? 'Untitled',
    collapsed: n.getCustomPropU32('collapsed', 0) != 0,
    padding: n.getCustomPropF32('padding', 8.0),
  );
}

void registerAll() {
  SkalRegistry.registerWidget('badge', _build_Badge);
  SkalRegistry.registerWidget('panel', _build_Panel);
}
