// GENERATED by skal_codegen — do not edit by hand.
//
// Source: named_ctors.dart
//
// One adapter per Widget class found in the source. Each adapter reads
// its constructor's named parameters from the bridge's custom-prop bag
// via NodeState.getCustomPropX(name, default), then constructs the
// real Flutter widget. The default value comes from the constructor's
// own default — if the JSX consumer omits a prop, they get the same
// behaviour as a direct Dart caller would.
//
// ignore_for_file: non_constant_identifier_names, sort_child_properties_last, unused_import, deprecated_member_use

import 'package:flutter/material.dart';
import 'package:skal_flutter/skal/bridge.dart';
import 'package:skal_flutter/skal/node_state.dart';
import 'package:skal_flutter/skal/registry.dart';

import 'named_ctors.dart';

Widget _build_Card(NodeState n, SkalBridge bridge) {
  return Card(
    title: n.getCustomPropStr('title') ?? 'untitled',
    background: Color(n.getCustomPropU32('background', 0xFFFFFFFF)),
  );
}

Widget _build_CardOutlined(NodeState n, SkalBridge bridge) {
  return Card.outlined(title: n.getCustomPropStr('title') ?? 'untitled');
}

Widget _build_SheetElevated(NodeState n, SkalBridge bridge) {
  return Sheet.elevated(label: n.getCustomPropStr('label') ?? 'sheet');
}

Widget _build_Link(NodeState n, SkalBridge bridge) {
  return Link(label: n.getCustomPropStr('label') ?? 'click me');
}

void registerAll() {
  SkalRegistry.registerWidget('card', _build_Card);
  SkalRegistry.registerWidget('cardOutlined', _build_CardOutlined);
  SkalRegistry.registerWidget('sheetElevated', _build_SheetElevated);
  SkalRegistry.registerWidget('link', _build_Link);
}
