// GENERATED by skal_codegen — do not edit by hand.
//
// Source: nullable_primitives.dart
//
// One adapter per Widget class found in the source. Each adapter reads
// its constructor's named parameters from the bridge's custom-prop bag
// via NodeState.getCustomPropX(name, default), then constructs the
// real Flutter widget. The default value comes from the constructor's
// own default — if the JSX consumer omits a prop, they get the same
// behaviour as a direct Dart caller would.
//
// ignore_for_file: non_constant_identifier_names, sort_child_properties_last, unused_import, deprecated_member_use, implementation_imports, unnecessary_import, depend_on_referenced_packages

import 'package:flutter/material.dart';
import 'package:skal_flutter/skal/bridge.dart';
import 'package:skal_flutter/skal/node_state.dart';
import 'package:skal_flutter/skal/registry.dart';

import 'nullable_primitives.dart';

Widget _build_Tunable(NodeState n, SkalBridge bridge) {
  return Tunable(
    opacity: n.getCustomPropF32OrNull('opacity'),
    maxLines: n.getCustomPropU32OrNull('maxLines'),
    dense: n.getCustomPropBoolOrNull('dense'),
    tint: (() {
      final v = n.getCustomPropU32OrNull('tint');
      return v == null ? null : Color(v);
    })(),
    scale: n.getCustomPropF32('scale', 1.0),
    priority: n.getCustomPropU32('priority', 0),
    enabled: n.getCustomPropU32('enabled', 1) != 0,
    background: Color(n.getCustomPropU32('background', 0xFF202020)),
  );
}

void registerAll() {
  SkalRegistry.registerWidget('tunable', _build_Tunable);
}
