// GENERATED by skal_codegen — do not edit by hand.
//
// Source: widget_list.dart
//
// One adapter per Widget class found in the source. Each adapter reads
// its constructor's named parameters from the bridge's custom-prop bag
// via NodeState.getCustomPropX(name, default), then constructs the
// real Flutter widget. The default value comes from the constructor's
// own default — if the JSX consumer omits a prop, they get the same
// behaviour as a direct Dart caller would.
//
// ignore_for_file: non_constant_identifier_names, sort_child_properties_last, unused_import

import 'package:flutter/material.dart';
import 'package:skal_flutter/skal/bridge.dart';
import 'package:skal_flutter/skal/node_state.dart';
import 'package:skal_flutter/skal/registry.dart';
import 'package:skal_flutter/skal/root.dart';

import 'widget_list.dart';

Widget _build_Grid(NodeState n, SkalBridge bridge) {
  return Grid(
    children: List.generate(n.childCount, (i) => SkalNode(nodeId: n.childAt(i), bridge: bridge, key: ValueKey<int>(n.childAt(i)))),
    columns: n.getCustomPropU32('columns', 2),
  );
}

Widget _build_LayerStack(NodeState n, SkalBridge bridge) {
  return LayerStack(
    layers: List.generate(n.childCount, (i) => SkalNode(nodeId: n.childAt(i), bridge: bridge, key: ValueKey<int>(n.childAt(i)))),
    background: Color(n.getCustomPropU32('background', 0xFF000000)),
  );
}

void registerAll() {
  SkalRegistry.registerWidget('grid', _build_Grid);
  SkalRegistry.registerWidget('layerStack', _build_LayerStack);
}
