// GENERATED by skal_codegen — do not edit by hand.
//
// Source: widget_child.dart
//
// One adapter per Widget class found in the source. Each adapter reads
// its constructor's named parameters from the bridge's custom-prop bag
// via NodeState.getCustomPropX(name, default), then constructs the
// real Flutter widget. The default value comes from the constructor's
// own default — if the JSX consumer omits a prop, they get the same
// behaviour as a direct Dart caller would.
//
// ignore_for_file: non_constant_identifier_names, sort_child_properties_last, unused_import, deprecated_member_use

import 'package:flutter/material.dart';
import 'package:skal_flutter/skal/bridge.dart';
import 'package:skal_flutter/skal/node_state.dart';
import 'package:skal_flutter/skal/registry.dart';
import 'package:skal_flutter/skal/root.dart';

import 'widget_child.dart';

Widget _build_Wrapper(NodeState n, SkalBridge bridge) {
  return Wrapper(
    child: n.childCount > 0
        ? SkalNode(
            nodeId: n.childAt(0),
            bridge: bridge,
            key: ValueKey<int>(n.childAt(0)),
          )
        : const SizedBox.shrink(),
  );
}

Widget _build_Tinted(NodeState n, SkalBridge bridge) {
  return Tinted(
    child: n.childCount > 0
        ? SkalNode(
            nodeId: n.childAt(0),
            bridge: bridge,
            key: ValueKey<int>(n.childAt(0)),
          )
        : const SizedBox.shrink(),
    tint: Color(n.getCustomPropU32('tint', 0xFFAA0000)),
  );
}

void registerAll() {
  SkalRegistry.registerWidget('wrapper', _build_Wrapper);
  SkalRegistry.registerWidget('tinted', _build_Tinted);
}
