// Solid universal-renderer adapter for Skal.
//
// Everything imported from this module by user JSX is generated by
// `babel-preset-solid` with `generate: 'universal'`. The babel plugin
// turns `<column>...</column>` into:
//
//   const _$el = createElement('column');
//   insert(_$el, ...);
//
// We map each of those host-tree calls onto bridge ops (CREATE_NODE,
// INSERT_BEFORE, REMOVE_NODE, SET_TEXT, BIND_HANDLER). Solid handles
// reactivity (signals, effects, memos, For, Show, etc.) by composing
// our `effect`/`memo` exports with createSignal & friends from solid-js.

import { createRenderer } from 'solid-js/universal';
import * as B from './bridge.js';

// Map JSX tag → widget type opcode.
const TAG_TO_WIDGET = {
  box:          B.WT_BOX,
  column:       B.WT_COLUMN,
  scrollColumn: B.WT_SCROLL_COLUMN,
  row:          B.WT_ROW,
  // 'text' is intentionally NOT here — text content is created via
  // createTextNode below. Devs use plain string children for text:
  //   <column>{() => `Count: ${count()}`}</column>
  button:       B.WT_BUTTON,
};

/**
 * Host node — a JS-side mirror of a bridge node. Maintains parent/sibling
 * pointers (Solid's universal renderer needs walking via getFirstChild +
 * getNextSibling) and the node's tag.
 *
 * We do NOT mirror the children list as an array — sibling links are the
 * canonical source. Insert/remove keeps both sides (bridge children list
 * + JS sibling pointers) in sync.
 */
class SkalNode {
  constructor(tag, id, isText = false) {
    this.tag = tag;
    this.id = id;
    this.isText = isText;
    this.parent = null;
    this.firstChild = null;
    this.lastChild = null;
    this.nextSibling = null;
    this.prevSibling = null;
    // For text nodes we cache the current value so replaceText can
    // short-circuit when nothing changed (Solid sometimes calls it with
    // the same value during reconciliation).
    this.text = '';
  }
}

const _renderer = createRenderer({
  createElement(tag) {
    const wt = TAG_TO_WIDGET[tag];
    if (wt === undefined) {
      throw new Error(`Skal: unknown JSX tag <${tag}>`);
    }
    const id = B.allocNodeId();
    B.writeOp(B.OP_CREATE_NODE, id, wt, 0);
    B.scheduleCommit();
    return new SkalNode(tag, id, false);
  },

  createTextNode(value) {
    const id = B.allocNodeId();
    B.writeOp(B.OP_CREATE_NODE, id, B.WT_TEXT, 0);
    const s = value == null ? '' : String(value);
    if (s.length > 0) B.setText(id, s);
    B.scheduleCommit();
    const node = new SkalNode('#text', id, true);
    node.text = s;
    return node;
  },

  replaceText(textNode, value) {
    const s = value == null ? '' : String(value);
    if (textNode.text === s) return;
    textNode.text = s;
    B.setText(textNode.id, s);
    B.scheduleCommit();
  },

  setProperty(node, name, value, _prev) {
    // onClick / onclick — wire to a bridge handler ID.
    if (name === 'onClick' || name === 'onclick') {
      if (typeof value === 'function') {
        const handlerId = B.newHandlerId(value);
        B.bindHandler(node.id, B.EV_CLICK, handlerId);
        B.scheduleCommit();
      }
      return;
    }
    // <button label="..." /> — set the button's text content.
    if (name === 'label' && node.tag === 'button') {
      const s = value == null ? '' : String(value);
      B.setText(node.id, s);
      B.scheduleCommit();
      return;
    }
    // Numeric u32 props (padding, color, font_size, etc.) — opaque
    // pass-through. Only useful once SkalNode in Kotlin starts reading
    // node.props, which it doesn't yet.
    if (typeof value === 'number' && Number.isInteger(value)) {
      // Map well-known names to their prop IDs; anything else is ignored.
      // Currently no composables read props, so this is a no-op.
      return;
    }
    // Silently drop unknown string props for now.
  },

  insertNode(parent, node, anchor) {
    // Bridge op
    const anchorId = anchor ? anchor.id : 0;
    B.writeOp(B.OP_INSERT_BEFORE, parent.id, node.id, anchorId);
    B.scheduleCommit();
    // Local linked-list bookkeeping (keep getFirstChild/getNextSibling fast).
    node.parent = parent;
    if (anchor) {
      node.nextSibling = anchor;
      node.prevSibling = anchor.prevSibling;
      if (anchor.prevSibling) anchor.prevSibling.nextSibling = node;
      else parent.firstChild = node;
      anchor.prevSibling = node;
    } else {
      // Append.
      node.prevSibling = parent.lastChild;
      node.nextSibling = null;
      if (parent.lastChild) parent.lastChild.nextSibling = node;
      else parent.firstChild = node;
      parent.lastChild = node;
    }
  },

  removeNode(parent, node) {
    B.writeOp(B.OP_REMOVE_NODE, node.id, 0, 0);
    B.scheduleCommit();
    if (node.prevSibling) node.prevSibling.nextSibling = node.nextSibling;
    else parent.firstChild = node.nextSibling;
    if (node.nextSibling) node.nextSibling.prevSibling = node.prevSibling;
    else parent.lastChild = node.prevSibling;
    node.parent = null;
    node.prevSibling = null;
    node.nextSibling = null;
  },

  isTextNode(node) { return node.isText; },
  getParentNode(node) { return node.parent; },
  getFirstChild(node) { return node.firstChild; },
  getNextSibling(node) { return node.nextSibling; },
});

// These are the names babel-preset-solid emits imports for. Re-export
// every entry from createRenderer's return value so JSX desugars cleanly.
export const {
  render,
  effect,
  memo,
  createComponent,
  createElement,
  createTextNode,
  insertNode,
  insert,
  spread,
  setProp,
  mergeProps,
  use,
} = _renderer;

// ───────────────────────────────────────────────────────────────────────
// The root host node. Pre-creates the bridge node with id=ROOT_NODE_ID
// (which Kotlin's SkalRoot mounts at) and exposes it for Solid's render().
// ───────────────────────────────────────────────────────────────────────

B.writeOp(B.OP_CREATE_NODE, B.ROOT_NODE_ID, B.WT_SCROLL_COLUMN, 0);
B.scheduleCommit();

export const root = new SkalNode('scrollColumn', B.ROOT_NODE_ID, false);
