// GENERATED by skal_codegen — do not edit by hand.
//
// Source: qr_image_view.dart, shimmer.dart
//
// One adapter per Widget class found in the source. Each adapter reads
// its constructor's named parameters from the bridge's custom-prop bag
// via NodeState.getCustomPropX(name, default), then constructs the
// real Flutter widget. The default value comes from the constructor's
// own default — if the JSX consumer omits a prop, they get the same
// behaviour as a direct Dart caller would.
//
// ignore_for_file: non_constant_identifier_names, sort_child_properties_last, unused_import, deprecated_member_use, implementation_imports, unnecessary_import, depend_on_referenced_packages

import 'package:flutter/material.dart';
import 'package:skal_flutter/skal/bridge.dart';
import 'package:skal_flutter/skal/node_state.dart';
import 'package:skal_flutter/skal/registry.dart';
import 'dart:convert';
import 'dart:io';
import 'package:camera/camera.dart';
import 'package:kitchen_sink/adapters/camera_factory.dart';
import 'package:kitchen_sink/adapters/ticker.dart';
import 'package:qr_flutter/src/types.dart';
import 'package:skal_flutter/skal/root.dart';

import 'package:qr_flutter/qr_flutter.dart';
import 'package:shimmer/shimmer.dart';

Map<String, dynamic>? _skalDecodeMap(Object? raw) {
  if (raw == null) return null;
  if (raw is Map<String, dynamic>) return raw;
  if (raw is String) {
    if (raw.isEmpty) return null;
    try {
      final decoded = jsonDecode(raw);
      if (decoded is Map<String, dynamic>) return decoded;
    } catch (_) {}
  }
  return null;
}

Alignment _skalParseAlignment(dynamic v, {Alignment def = Alignment.center}) {
  if (v is String) {
    switch (v) {
      case 'topLeft':
        return Alignment.topLeft;
      case 'topCenter':
        return Alignment.topCenter;
      case 'topRight':
        return Alignment.topRight;
      case 'centerLeft':
        return Alignment.centerLeft;
      case 'center':
        return Alignment.center;
      case 'centerRight':
        return Alignment.centerRight;
      case 'bottomLeft':
        return Alignment.bottomLeft;
      case 'bottomCenter':
        return Alignment.bottomCenter;
      case 'bottomRight':
        return Alignment.bottomRight;
    }
  }
  if (v is List && v.length == 2) {
    return Alignment((v[0] as num).toDouble(), (v[1] as num).toDouble());
  }
  return def;
}

Color _skalParseColor(dynamic v) {
  if (v is int) return Color(v);
  if (v is String) {
    var s = v.startsWith('#') ? v.substring(1) : v;
    if (s.length == 6) s = 'FF$s';
    return Color(int.parse(s, radix: 16));
  }
  return const Color(0xFF000000);
}

QrDataModuleShape? _skalParseEnumQrDataModuleShape(Object? raw) {
  if (raw is int) {
    if (raw < 0 || raw >= QrDataModuleShape.values.length) return null;
    return QrDataModuleShape.values[raw];
  }
  if (raw is String) {
    switch (raw) {
      case 'square':
        return QrDataModuleShape.square;
      case 'circle':
        return QrDataModuleShape.circle;
    }
  }
  return null;
}

QrEyeShape? _skalParseEnumQrEyeShape(Object? raw) {
  if (raw is int) {
    if (raw < 0 || raw >= QrEyeShape.values.length) return null;
    return QrEyeShape.values[raw];
  }
  if (raw is String) {
    switch (raw) {
      case 'square':
        return QrEyeShape.square;
      case 'circle':
        return QrEyeShape.circle;
    }
  }
  return null;
}

Gradient? _skalParseGradient(String? json) {
  if (json == null || json.isEmpty) return null;
  final m = jsonDecode(json) as Map<String, dynamic>;
  final colors = (m['colors'] as List).map(_skalParseColor).toList();
  final stops = (m['stops'] as List?)
      ?.cast<num>()
      .map((n) => n.toDouble())
      .toList();
  switch (m['type']) {
    case 'radial':
      return RadialGradient(
        colors: colors,
        stops: stops,
        radius: (m['radius'] as num?)?.toDouble() ?? 0.5,
        center: _skalParseAlignment(m['center'], def: Alignment.center),
      );
    case 'sweep':
      return SweepGradient(
        colors: colors,
        stops: stops,
        startAngle: (m['startAngle'] as num?)?.toDouble() ?? 0.0,
        endAngle: (m['endAngle'] as num?)?.toDouble() ?? 6.283185307,
        center: _skalParseAlignment(m['center'], def: Alignment.center),
      );
    default: // 'linear' or missing
      return LinearGradient(
        colors: colors,
        stops: stops,
        begin: _skalParseAlignment(m['begin'], def: Alignment.centerLeft),
        end: _skalParseAlignment(m['end'], def: Alignment.centerRight),
      );
  }
}

QrDataModuleStyle? _skalParseQrDataModuleStyle(Object? raw) {
  final j = _skalDecodeMap(raw);
  if (j == null) return null;
  return QrDataModuleStyle(
    dataModuleShape: _skalParseEnumQrDataModuleShape(j['dataModuleShape']),
    color: ((j['color']) == null ? null : _skalParseColor(j['color'])),
  );
}

QrEmbeddedImageStyle? _skalParseQrEmbeddedImageStyle(Object? raw) {
  final j = _skalDecodeMap(raw);
  if (j == null) return null;
  return QrEmbeddedImageStyle(
    size: _skalParseSize(j['size']),
    color: ((j['color']) == null ? null : _skalParseColor(j['color'])),
  );
}

QrEyeStyle? _skalParseQrEyeStyle(Object? raw) {
  final j = _skalDecodeMap(raw);
  if (j == null) return null;
  return QrEyeStyle(
    eyeShape: _skalParseEnumQrEyeShape(j['eyeShape']),
    color: ((j['color']) == null ? null : _skalParseColor(j['color'])),
  );
}

Size? _skalParseSize(Object? raw) {
  final j = _skalDecodeMap(raw);
  if (j == null) return null;
  return Size(
    ((j['width']) as num?)?.toDouble() ?? 0.0,
    ((j['height']) as num?)?.toDouble() ?? 0.0,
  );
}

Widget _build_QrImageView(NodeState n, SkalBridge bridge) {
  return QrImageView(
    data: n.getCustomPropStr('data') ?? '',
    size: n.getCustomPropF32OrNull('size'),
    padding: EdgeInsets.fromLTRB(
      n.getCustomPropF32('paddingLeft', 10.0),
      n.getCustomPropF32('paddingTop', 10.0),
      n.getCustomPropF32('paddingRight', 10.0),
      n.getCustomPropF32('paddingBottom', 10.0),
    ),
    backgroundColor: Color(n.getCustomPropU32('backgroundColor', 0x00000000)),
    version: n.getCustomPropU32('version', QrVersions.auto),
    errorCorrectionLevel: n.getCustomPropU32(
      'errorCorrectionLevel',
      QrErrorCorrectLevel.L,
    ),
    constrainErrorBounds: n.getCustomPropU32('constrainErrorBounds', 1) != 0,
    gapless: n.getCustomPropU32('gapless', 1) != 0,
    embeddedImage:
        ((() {
              final s = n.getCustomPropStr('embeddedImage') ?? '';
              if (s.isEmpty) return null;
              if (s.startsWith('http')) return NetworkImage(s);
              if (s.startsWith('file://'))
                return FileImage(File(s.substring(7)));
              if (s.startsWith('/')) return FileImage(File(s));
              return AssetImage(s);
            })()
            as ImageProvider?),
    embeddedImageStyle: _skalParseQrEmbeddedImageStyle(
      n.getCustomPropStr('embeddedImageStyle'),
    ),
    semanticsLabel: n.getCustomPropStr('semanticsLabel') ?? 'qr code',
    eyeStyle:
        (_skalParseQrEyeStyle(n.getCustomPropStr('eyeStyle')) ??
        const QrEyeStyle(eyeShape: QrEyeShape.square, color: Colors.black)),
    dataModuleStyle:
        (_skalParseQrDataModuleStyle(n.getCustomPropStr('dataModuleStyle')) ??
        const QrDataModuleStyle(
          dataModuleShape: QrDataModuleShape.square,
          color: Colors.black,
        )),
    embeddedImageEmitsError:
        n.getCustomPropU32('embeddedImageEmitsError', 0) != 0,
    foregroundColor: (() {
      final v = n.getCustomPropU32OrNull('foregroundColor');
      return v == null ? null : Color(v);
    })(),
  );
}

Widget _build_Shimmer(NodeState n, SkalBridge bridge) {
  return Shimmer(
    child: n.childCount > 0
        ? SkalNode(
            nodeId: n.childAt(0),
            bridge: bridge,
            key: ValueKey<int>(n.childAt(0)),
          )
        : const SizedBox.shrink(),
    gradient: (_skalParseGradient(n.getCustomPropStr('gradient')) as Gradient),
    direction: ShimmerDirection.values[n.getCustomPropU32('direction', 0)],
    period: Duration(milliseconds: n.getCustomPropU32('period', 1500)),
    loop: n.getCustomPropU32('loop', 0),
    enabled: n.getCustomPropU32('enabled', 1) != 0,
  );
}

Widget _build_ShimmerFromColors(NodeState n, SkalBridge bridge) {
  return Shimmer.fromColors(
    child: n.childCount > 0
        ? SkalNode(
            nodeId: n.childAt(0),
            bridge: bridge,
            key: ValueKey<int>(n.childAt(0)),
          )
        : const SizedBox.shrink(),
    baseColor: Color(n.getCustomPropU32('baseColor', 0xFF000000)),
    highlightColor: Color(n.getCustomPropU32('highlightColor', 0xFF000000)),
    period: Duration(milliseconds: n.getCustomPropU32('period', 1500)),
    direction: ShimmerDirection.values[n.getCustomPropU32('direction', 0)],
    loop: n.getCustomPropU32('loop', 0),
    enabled: n.getCustomPropU32('enabled', 1) != 0,
  );
}

class _CameraHost extends StatefulWidget {
  final NodeState n;
  final String? cameraName;
  final int resolutionIndex;

  const _CameraHost({
    required this.n,
    this.cameraName,
    this.resolutionIndex = 1,
  });

  @override
  State<_CameraHost> createState() => _CameraHostState();
}

class _CameraHostState extends State<_CameraHost> {
  Object? _ctl;
  Object? _err;

  @override
  void initState() {
    super.initState();
    widget.n.methodDispatcher = _dispatch;
    _init();
  }

  Future<void> _init() async {
    try {
      final c = await createCamera(
        cameraName: widget.cameraName,
        resolutionIndex: widget.resolutionIndex,
      );
      if (!mounted) {
        (c as dynamic).dispose();
        return;
      }
      setState(() => _ctl = c);
    } catch (e) {
      if (mounted) setState(() => _err = e);
    }
  }

  @override
  void dispose() {
    widget.n.methodDispatcher = null;
    if (_ctl != null) (_ctl as dynamic).dispose();
    super.dispose();
  }

  Object? _dispatch(String method, List<Object?> args) {
    if (_ctl == null) return null;
    final ctl = _ctl as CameraController;
    switch (method) {
      case 'debugCheckIsDisposed':
        ctl.debugCheckIsDisposed();
        return null;
      case 'initialize':
        ctl.initialize();
        return null;
      case 'prepareForVideoRecording':
        ctl.prepareForVideoRecording();
        return null;
      case 'pausePreview':
        ctl.pausePreview();
        return null;
      case 'resumePreview':
        ctl.resumePreview();
        return null;
      case 'takePicture':
        return ctl.takePicture();
      case 'stopImageStream':
        ctl.stopImageStream();
        return null;
      case 'stopVideoRecording':
        return ctl.stopVideoRecording();
      case 'pauseVideoRecording':
        ctl.pauseVideoRecording();
        return null;
      case 'resumeVideoRecording':
        ctl.resumeVideoRecording();
        return null;
      case 'buildPreview':
        return ctl.buildPreview();
      case 'getMaxZoomLevel':
        return ctl.getMaxZoomLevel();
      case 'getMinZoomLevel':
        return ctl.getMinZoomLevel();
      case 'setZoomLevel':
        ctl.setZoomLevel(args[0] as double);
        return null;
      case 'getMinExposureOffset':
        return ctl.getMinExposureOffset();
      case 'getMaxExposureOffset':
        return ctl.getMaxExposureOffset();
      case 'getExposureOffsetStepSize':
        return ctl.getExposureOffsetStepSize();
      case 'setExposureOffset':
        return ctl.setExposureOffset(args[0] as double);
      case 'unlockCaptureOrientation':
        ctl.unlockCaptureOrientation();
        return null;
      case 'supportsImageStreaming':
        return ctl.supportsImageStreaming();
      default:
        return null;
    }
  }

  @override
  Widget build(BuildContext context) {
    if (_err != null) {
      return Container(
        color: const Color(0xFFFFE0E0),
        padding: const EdgeInsets.all(8),
        child: Text('Camera error: $_err'),
      );
    }
    if (_ctl == null) return const SizedBox.shrink();
    return CameraPreview(_ctl as dynamic);
  }
}

Widget _build_Camera(NodeState n, SkalBridge bridge) {
  return _CameraHost(
    n: n,
    cameraName: n.getCustomPropStr('cameraName'),
    resolutionIndex: n.getCustomPropU32('resolutionIndex', 1),
  );
}

class _TickerHost extends StatefulWidget {
  final NodeState n;
  final int intervalMs;
  final bool startPaused;

  const _TickerHost({
    required this.n,
    this.intervalMs = 1000,
    this.startPaused = false,
  });

  @override
  State<_TickerHost> createState() => _TickerHostState();
}

class _TickerHostState extends State<_TickerHost> {
  Object? _ctl;
  Object? _err;

  @override
  void initState() {
    super.initState();
    widget.n.methodDispatcher = _dispatch;
    _init();
  }

  Future<void> _init() async {
    try {
      final c = createTicker(
        intervalMs: widget.intervalMs,
        startPaused: widget.startPaused,
      );
      if (!mounted) {
        (c as dynamic).dispose();
        return;
      }
      setState(() => _ctl = c);
    } catch (e) {
      if (mounted) setState(() => _err = e);
    }
  }

  @override
  void dispose() {
    widget.n.methodDispatcher = null;
    if (_ctl != null) (_ctl as dynamic).dispose();
    super.dispose();
  }

  Object? _dispatch(String method, List<Object?> args) {
    if (_ctl == null) return null;
    final ctl = _ctl as TickController;
    switch (method) {
      case 'pause':
        ctl.pause();
        return null;
      case 'resume':
        ctl.resume();
        return null;
      case 'reset':
        ctl.reset();
        return null;
      case 'getValue':
        return ctl.getValue();
      case 'isPaused':
        return ctl.isPaused();
      case 'bump':
        ctl.bump(args[0] as int);
        return null;
      case 'describe':
        return ctl.describe(args[0] as String);
      case 'snapshot':
        return ctl.snapshot();
      case 'ticks':
        return ctl.ticks();
      default:
        return null;
    }
  }

  @override
  Widget build(BuildContext context) {
    if (_err != null) {
      return Container(
        color: const Color(0xFFFFE0E0),
        padding: const EdgeInsets.all(8),
        child: Text('Ticker error: $_err'),
      );
    }
    if (_ctl == null) return const SizedBox.shrink();
    return TickView(_ctl as dynamic);
  }
}

Widget _build_Ticker(NodeState n, SkalBridge bridge) {
  return _TickerHost(
    n: n,
    intervalMs: n.getCustomPropU32('intervalMs', 1000),
    startPaused: n.getCustomPropU32('startPaused', 0) != 0,
  );
}

void registerAll() {
  SkalRegistry.registerWidget('qrImageView', _build_QrImageView);
  SkalRegistry.registerWidget('shimmer', _build_Shimmer);
  SkalRegistry.registerWidget('shimmerFromColors', _build_ShimmerFromColors);
  SkalRegistry.registerWidget('camera', _build_Camera);
  SkalRegistry.registerWidget('ticker', _build_Ticker);
}
