// Skal — app entry point.
//
// Bootstrap sequence:
//
//   1. Skal.create()          — FFI to skal_create_runtime; spins up
//                               bun's worker + JSC, returns the
//                               shared 2 MiB bridge buffer pointer.
//   2. load skal-app.js       — read the Solid+app bundle out of the
//                               app's assets directory.
//   3. skal.evaluate(source)  — bun parses + runs the IIFE on its
//                               worker thread. The bundle wires up
//                               Solid's universal renderer to our
//                               bridge encoder, mounts the App
//                               component, and queues an op-batch.
//   4. SkalBridge(skal)       — wraps the buffer in our ByteData
//                               drain logic.
//   5. bridge.pumpOps()       — initial drain so the very first frame
//                               already has the JS-emitted tree.
//   6. runApp(SkalRoot)       — Flutter mounts the tree; from here on,
//                               every frame ticks pumpOps and Flutter
//                               coalesces dirty rebuilds.

import 'dart:io';
import 'dart:ui' show FramePhase;

import 'package:flutter/cupertino.dart';
import 'package:flutter/foundation.dart' show kReleaseMode;
import 'package:flutter/material.dart';
import 'package:flutter/scheduler.dart';
import 'package:flutter/services.dart';
import 'package:path_provider/path_provider.dart';

import 'adapters/generated/skal_adapters.g.dart' as local_gen;
import 'skal_codegen.g.dart' as packages_gen;
import 'skal/bridge.dart';
import 'skal/dialogs.dart';
import 'skal/root.dart';
import 'skal_ffi.dart';

void main() async {
  // Monotonic clock for boot timing — wall-clock (DateTime.now) can step
  // backwards if NTP corrects during launch, occasionally yielding negative
  // init/eval numbers.
  final bootClock = Stopwatch()..start();
  final t0 = bootClock.elapsedMicroseconds;
  WidgetsFlutterBinding.ensureInitialized();

  // ── 0. Register custom widget adapters ──────────────────────────────
  //
  // For real apps each third-party Skal adapter package would expose
  // its own registerAll(). The dev's main() calls each in turn before
  // runApp(). Order is "registrations win on collision" — later
  // registrations override earlier, so codegen output runs first and
  // hand-written manual adapters run after to shadow as needed.
  //
  // Local widgets — generated by the CLI from `lib/adapters/greeting_widget.dart`:
  //
  //   dart run ../../codegen/skal_codegen/bin/skal_codegen.dart \
  //     lib/adapters/greeting_widget.dart \
  //     -o lib/adapters/generated/skal_adapters.g.dart
  //
  // The CLI path is the right tool for one-off local widget wrapping.
  local_gen.registerAll();

  // Third-party packages — generated by build_runner from the
  // `lib/skal_codegen.yaml` marker file's `packages:` list:
  //
  //   dart run build_runner build
  //
  // The Builder walks each listed package's lib/ in pub-cache and
  // emits a single combined adapter at `lib/skal_codegen.g.dart`,
  // INCLUDING adapters for named constructors (e.g. shimmer's
  // `Shimmer.fromColors` surfaces as `<ShimmerFromColors>` in JSX).
  // Add a package by listing it in skal_codegen.yaml and re-running.
  //
  // Hand-written escape-hatch adapters would also be wired here, if
  // any: they'd live under `lib/adapters/<name>_manual.dart`, expose
  // a `registerAll()` of their own, and be called AFTER packages_gen
  // so they shadow on name collision. The MVP currently has none —
  // qr_flutter + shimmer both round-trip cleanly through codegen.
  packages_gen.registerAll();

  // ── 1. Resolve the data dir, then create the bun runtime ────────────
  //
  // The base data dir (<appSupport>/skal-store) is resolved up front and
  // handed to the runtime, which installs it as globalThis.__skal_data_dir.
  // That lets the JS store read it synchronously — skipping the async
  // getDataDir() RPC, whose reply otherwise can't be serviced until the
  // JS thread goes idle (hundreds of ms into boot).
  String dataDir = '';
  try {
    final support = await getApplicationSupportDirectory();
    dataDir = '${support.path}/skal-store';
    Directory(dataDir).createSync(recursive: true);
  } catch (_) {
    // best-effort — JS falls back to the getDataDir RPC
  }

  final tCreate0 = bootClock.elapsedMicroseconds;
  final skal = Skal.create(dataDir);
  if (skal == null) {
    runApp(const _ErrorApp(message: 'skal_create_runtime returned 0'));
    return;
  }
  final tCreate1 = bootClock.elapsedMicroseconds;

  // ── 1b. Prewarm the native store ────────────────────────────────────
  //
  // Opening the store (segment scan → keydir) is native and schema-free,
  // so kick it off on a background thread now — it overlaps the bytecode
  // extraction + bundle evaluation below. The JS side's __skal_store_open
  // picks up the prewarmed handle; if this fails the store just opens
  // synchronously on first use. The directory must match what the JS
  // store opens — <dataDir>/<cfg.name>, and the store's name is 'store'.
  if (dataDir.isNotEmpty) {
    try {
      skal.prewarmStore('$dataDir/store');
    } catch (_) {
      // best-effort — JS opens the store itself if prewarm didn't happen
    }
  }

  // ── 2 + 3. Load and evaluate the JS bundle ──────────────────────────
  //
  // Two paths:
  //
  //   • Bytecode path (release): extract `skal-app.cjs` + its
  //     `skal-app.cjs.jsc` sibling out of the APK ZIP into a real
  //     filesystem directory, then eval a tiny async IIFE that does
  //     `await import('file://...')`. Bun's module loader sees the
  //     `// @bun @bytecode @bun-cjs` marker in the .cjs header,
  //     reads the .jsc bytecode bytes, attaches them to JSC's
  //     SourceProvider — parser is skipped entirely.
  //
  //   • Source path (debug/profile): rootBundle.loadString reads the
  //     raw IIFE from APK assets and passes it straight through
  //     skal_evaluate. Simpler but pays the parse cost on every
  //     cold launch (~hundreds of ms for the 23 KiB Solid bundle).
  //
  // We gate by kReleaseMode rather than always preferring bytecode
  // so hot-reload-style iteration keeps working in debug/profile
  // (where the asset .cjs / .jsc may lag behind the .js anyway).
  //
  // Extraction is one-shot per APK install: existsSync() on both files
  // skips the write after the first launch (~200 ms on first launch,
  // ~tens of µs on subsequent ones; see _extractBytecodeAssets).
  final EvalResult result;
  double extractMs = 0.0;
  final int tEval0 = bootClock.elapsedMicroseconds;
  if (kReleaseMode) {
    final tX0 = bootClock.elapsedMicroseconds;
    final cjsPath = await _extractBytecodeAssets();
    final tX1 = bootClock.elapsedMicroseconds;
    extractMs = (tX1 - tX0) / 1000.0;
    // Async IIFE — Bun__REPL__evaluate runs the script as a Program (no
    // top-level await), but dynamic import() is legal in Program context.
    // Bun's worker waitForPromise hook unwraps the returned promise
    // before signalDone, so this is synchronous from Dart's POV.
    final loader =
        "(async()=>{await import(${_jsStringLiteral('file://$cjsPath')});"
        "return 'skal-app loaded';})();";
    result = skal.evaluate(loader, url: 'skal:loader');
  } else {
    final source = await rootBundle.loadString('assets/skal-app.js');
    result = skal.evaluate(source, url: 'skal-app.js');
  }
  final tEval1 = bootClock.elapsedMicroseconds;

  // ── 4 + 5. Wrap in the bridge and do an initial drain ──────────────
  final bridge = SkalBridge(skal);
  bridge.ensureRoot();
  bridge.pumpOps();

  // Register the app-level RPC dispatcher on the (now-existing) root
  // node — backs the imperative showDialog / showSnackbar JS API.
  installAppDispatcher(bridge);

  if (result.isError) {
    debugPrint('[skal] EVAL ERROR: ${result.value}');
  }
  final evalOnlyMs = (tEval1 - tEval0) / 1000.0 - extractMs;
  debugPrint('[skal] init=${((tCreate1 - tCreate0) / 1000).toStringAsFixed(1)}ms '
      'extract=${extractMs.toStringAsFixed(1)}ms '
      'eval=${evalOnlyMs.toStringAsFixed(1)}ms '
      'result=${result.value} '
      'nodes=${bridge.nodes.length}');

  runApp(SkalApp(
    bridge: bridge,
    initMs: (tCreate1 - tCreate0) / 1000.0,
    evalMs: (tEval1 - tEval0) / 1000.0,
    bootMs: (tEval1 - t0) / 1000.0,
  ));
}

class SkalApp extends StatelessWidget {
  final SkalBridge bridge;
  final double initMs;
  final double evalMs;
  final double bootMs;
  const SkalApp({
    super.key,
    required this.bridge,
    required this.initMs,
    required this.evalMs,
    required this.bootMs,
  });

  @override
  Widget build(BuildContext context) {
    // Rebuilds whenever JS calls `setDesign` — the MaterialApp theme
    // and the CupertinoTheme below both re-derive from the bridge's
    // design mode + brightness. See FLUTTER_JS_COMPONENTS.md §10.1.
    return ListenableBuilder(
      listenable: bridge.designChanged,
      builder: (context, _) {
        final dark = bridge.designBrightness == 1;
        return MaterialApp(
          title: 'Skal-Flutter',
          theme: dark
              ? ThemeData.dark(useMaterial3: true)
              : ThemeData.light(useMaterial3: true),
          debugShowCheckedModeBanner: false,
          // Context-free handles for the imperative dialog API (§10.2).
          navigatorKey: skalNavigatorKey,
          scaffoldMessengerKey: skalScaffoldMessengerKey,
          // CupertinoTheme ancestor so Cupertino-variant widgets
          // (CupertinoButton/Switch/…) theme + pick up brightness.
          home: CupertinoTheme(
            data: CupertinoThemeData(
              brightness: dark ? Brightness.dark : Brightness.light,
            ),
            child: Scaffold(
              backgroundColor: dark
                  ? const Color(0xFF101014)
                  : const Color(0xFFF0F0F3),
              body: SafeArea(
                child: Column(
                  children: [
                    PerfHud(
                      bridge: bridge,
                      initMs: initMs,
                      evalMs: evalMs,
                      bootMs: bootMs,
                    ),
                    // SkalRoot is mounted inside Expanded only (no outer
                    // SingleChildScrollView). The JS app's root is a
                    // <listView>, which renders to ListView.builder —
                    // a self-contained vertical scroller that
                    // virtualizes its children. Wrapping it in another
                    // vertical scroller would (a) crash on unbounded
                    // constraints, (b) defeat virtualization.
                    //
                    // If the JS app uses a plain <column> as its root,
                    // anything off-screen will be clipped. Use
                    // <listView> at the top level for scrollable
                    // content.
                    Expanded(child: SkalRoot(bridge: bridge)),
                  ],
                ),
              ),
            ),
          ),
        );
      },
    );
  }
}

// ─────────────────────────────────────────────────────────────────────────
// PerfHud — diagnostic overlay shown above the app.
//
// Polls SchedulerBinding.addTimingsCallback for real GPU frame
// timings, reads bridge.pumpAvgNs / pumpPeakNs once per frame for
// drain cost, reads bridge.propWritesLastDrain /
// coldPropsTouchedLastDrain for "how much JS work hit us this frame."
// ─────────────────────────────────────────────────────────────────────────

class PerfHud extends StatefulWidget {
  final SkalBridge bridge;
  final double initMs;
  final double evalMs;
  final double bootMs;
  const PerfHud({
    super.key,
    required this.bridge,
    required this.initMs,
    required this.evalMs,
    required this.bootMs,
  });

  @override
  State<PerfHud> createState() => _PerfHudState();
}

class _PerfHudState extends State<PerfHud> with SingleTickerProviderStateMixin {
  // Two numbers, two meanings:
  //
  //   _fps     = inter-frame rate (1 / (Δ between consecutive
  //              FrameTiming.vsyncStart timestamps)). This IS frames-
  //              per-second as a user perceives it — capped at the
  //              panel's refresh rate, drops when frames are missed.
  //
  //   _frameMs = totalSpan, how much of the budget the frame's work
  //              consumed (vsync → rasterFinish). On a 60 Hz panel
  //              budget is 16.67 ms; >16 ms means you're about to
  //              miss the next vsync. Says nothing about FPS on its
  //              own — a 4 ms frame and a 14 ms frame both show as
  //              "60 FPS" if neither dropped.
  //
  // Previous version computed FPS as 1e6 / totalSpan_us, which over-
  // reports any time frames complete faster than the vsync interval
  // (we saw "166 FPS" / "266 FPS" — pure artifact, all those frames
  // were vsync-limited to 60 Hz on this emulator).
  double _fps = 0;
  double _frameMs = 0;
  int? _prevVsyncUs;
  late final Ticker _refreshTicker;

  @override
  void initState() {
    super.initState();
    SchedulerBinding.instance.addTimingsCallback(_onTimings);
    // A refresh ticker keeps the HUD numbers updating even when nothing
    // else in the tree is dirty (otherwise the HUD's text would stop
    // updating during JS-idle steady state). Also ensures Flutter keeps
    // requesting frames, so `_onTimings` keeps firing and we have data
    // to compute inter-frame FPS from.
    _refreshTicker = createTicker((_) {
      if (mounted) setState(() {});
    })..start();
  }

  void _onTimings(List<FrameTiming> timings) {
    if (timings.isEmpty) return;
    // Walk every timing in the batch — `addTimingsCallback` can hand
    // us 2+ frames at once and we want each inter-frame interval, not
    // just the last one.
    for (final t in timings) {
      // FrameTiming exposes phase timestamps via timestampInMicroseconds,
      // not as Duration getters. vsyncStart is when the OS told Flutter
      // to start producing a new frame — successive vsyncStart deltas
      // give true inter-frame intervals.
      final vsyncUs = t.timestampInMicroseconds(FramePhase.vsyncStart);
      if (_prevVsyncUs != null) {
        final intervalUs = vsyncUs - _prevVsyncUs!;
        if (intervalUs > 0) {
          final fps = 1e6 / intervalUs;
          _fps = _fps == 0 ? fps : _fps * 0.9 + fps * 0.1;
        }
      }
      _prevVsyncUs = vsyncUs;
    }
    final ms = timings.last.totalSpan.inMicroseconds / 1000.0;
    _frameMs = _frameMs == 0 ? ms : _frameMs * 0.9 + ms * 0.1;
  }

  @override
  void dispose() {
    SchedulerBinding.instance.removeTimingsCallback(_onTimings);
    _refreshTicker.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    // Display pump times in ms with 3 decimals so warm-state sub-µs
    // numbers print as `0.155 ms` while cold-launch spikes still
    // read naturally as e.g. `4.123 ms`.
    final pumpMs = widget.bridge.pumpAvgNs / 1000000.0;
    final peakMs = widget.bridge.pumpPeakNs / 1000000.0;
    final writes = widget.bridge.propWritesLastDrain;
    final touched = widget.bridge.coldPropsTouchedLastDrain;
    return Container(
      color: const Color(0xFF202028),
      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
      width: double.infinity,
      child: DefaultTextStyle(
        style: const TextStyle(
          color: Color(0xFFE0E0E0),
          fontFamily: 'monospace',
          fontSize: 11,
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text('Skal — Solid in JS, Flutter rendering',
                style: TextStyle(fontWeight: FontWeight.bold)),
            Text('init ${widget.initMs.toStringAsFixed(1)} ms · '
                'first eval ${widget.evalMs.toStringAsFixed(1)} ms · '
                'boot ${widget.bootMs.toStringAsFixed(1)} ms'),
            Text('${_fps.toStringAsFixed(0)} FPS '
                '(${_frameMs.toStringAsFixed(2)} ms) · '
                'pump ${pumpMs.toStringAsFixed(3)} ms '
                '(peak ${peakMs.toStringAsFixed(3)} ms) · '
                'props $writes/$touched'),
          ],
        ),
      ),
    );
  }
}

/// Pull `skal-app.cjs` and `skal-app.cjs.jsc` out of the APK's assets/
/// ZIP entries and lay them down on a real filesystem path. Returns the
/// absolute path of the extracted .cjs file.
///
/// Deferred optimization: run on a background isolate so it overlaps
/// with `skal_create_runtime` on cold launch. The naive Isolate.run
/// version copies the 290 KB byte payload across the isolate boundary
/// which negates the parallelism win; a proper implementation needs
/// `TransferableTypedData` for zero-copy transfer, plus splitting the
/// call so the main isolate kicks off both extraction and runtime init
/// in parallel. ~50 LOC, only matters on the first cold launch after
/// install.
///
/// bun's module loader takes file:// URLs and reads the bytes via libc
/// open()/read(). APK assets aren't mmap'd as regular files — they live
/// inside the .apk's ZIP stream — so we must extract once. The .jsc must
/// sit next to the .cjs because bun derives the bytecode path by appending
/// ".jsc" to the resolved module URL.
///
/// Staleness check: an `adb install -r` reinstall — what `flutter run`
/// and most app upgrades do — KEEPS the app's data directory. A bare
/// `existsSync()` check would therefore load the PREVIOUS APK's
/// bytecode forever: a silent version mismatch against the freshly
/// installed libskal (e.g. a changed bridge-buffer size → the JS side
/// throws `bridge buffer not available` at eval time). So we
/// byte-compare the small (~50 KB) `.cjs` against the APK's bundled
/// copy and re-extract only when it actually changed. The expensive
/// part — loading + writing the ~400 KB `.jsc` — is still skipped on
/// an unchanged warm relaunch.
Future<String> _extractBytecodeAssets() async {
  final dir = await getApplicationSupportDirectory();
  final cjsFile = File('${dir.path}/skal-app.cjs');
  final jscFile = File('${dir.path}/skal-app.cjs.jsc');

  // load() (not loadString) — both are raw bytes that must round-trip
  // without UTF-8 reinterpretation. .cjs is mostly ASCII but contains
  // emoji literals in user strings; .jsc is binary.
  final cjsData = await rootBundle.load('assets/skal-app.cjs');
  final cjsBytes =
      cjsData.buffer.asUint8List(cjsData.offsetInBytes, cjsData.lengthInBytes);

  // Up to date? The .cjs and .jsc are always rebuilt as a pair, so the
  // .cjs is a faithful staleness proxy for both.
  if (cjsFile.existsSync() &&
      jscFile.existsSync() &&
      _bytesEqual(cjsFile.readAsBytesSync(), cjsBytes)) {
    return cjsFile.path;
  }

  final jscData = await rootBundle.load('assets/skal-app.cjs.jsc');
  await cjsFile.writeAsBytes(cjsBytes, flush: false);
  await jscFile.writeAsBytes(
    jscData.buffer.asUint8List(jscData.offsetInBytes, jscData.lengthInBytes),
    flush: false,
  );
  return cjsFile.path;
}

/// Byte-equality for the staleness check. Length-first so a changed
/// bundle (almost always a different size) rejects in O(1).
bool _bytesEqual(List<int> a, List<int> b) {
  if (a.length != b.length) return false;
  for (var i = 0; i < a.length; i++) {
    if (a[i] != b[i]) return false;
  }
  return true;
}

/// Quote a string as a JS string literal — quotes, backslashes, and
/// control chars escaped. Needed because we embed an arbitrary
/// filesystem path into the source of the async-IIFE loader, and
/// arbitrary paths can contain characters that break naïve string
/// concatenation (quote, backslash, newline, …).
String _jsStringLiteral(String s) {
  final sb = StringBuffer('"');
  for (var i = 0; i < s.length; i++) {
    final c = s.codeUnitAt(i);
    switch (c) {
      case 0x5C: sb.write(r'\\'); break;
      case 0x22: sb.write(r'\"'); break;
      case 0x0A: sb.write(r'\n'); break;
      case 0x0D: sb.write(r'\r'); break;
      case 0x09: sb.write(r'\t'); break;
      case 0x08: sb.write(r'\b'); break;
      case 0x0C: sb.write(r'\f'); break;
      default:
        if (c < 0x20) {
          sb.write('\\u${c.toRadixString(16).padLeft(4, '0')}');
        } else {
          sb.writeCharCode(c);
        }
    }
  }
  sb.write('"');
  return sb.toString();
}

class _ErrorApp extends StatelessWidget {
  final String message;
  const _ErrorApp({required this.message});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Padding(
            padding: const EdgeInsets.all(24),
            child: Text('Skal init failed: $message'),
          ),
        ),
      ),
    );
  }
}
