// GENERATED by skal_codegen — do not edit by hand.
//
// Source: qr_image_view.dart, shimmer.dart
//
// One adapter per Widget class found in the source. Each adapter reads
// its constructor's named parameters from the bridge's custom-prop bag
// via NodeState.getCustomPropX(name, default), then constructs the
// real Flutter widget. The default value comes from the constructor's
// own default — if the JSX consumer omits a prop, they get the same
// behaviour as a direct Dart caller would.
//
// ignore_for_file: non_constant_identifier_names, sort_child_properties_last, unused_import

import 'package:flutter/material.dart';
import 'package:skal_flutter/skal/bridge.dart';
import 'package:skal_flutter/skal/node_state.dart';
import 'package:skal_flutter/skal/registry.dart';
import 'package:skal_flutter/skal/root.dart';

import 'package:qr_flutter/qr_flutter.dart';
import 'package:shimmer/shimmer.dart';

Widget _build_QrImageView(NodeState n, SkalBridge bridge) {
  return QrImageView(
    data: n.getCustomPropStr('data') ?? '',
    size: n.getCustomPropF32('size', 0.0),
    padding: EdgeInsets.fromLTRB(n.getCustomPropF32('paddingLeft', 10.0), n.getCustomPropF32('paddingTop', 10.0), n.getCustomPropF32('paddingRight', 10.0), n.getCustomPropF32('paddingBottom', 10.0)),
    backgroundColor: Color(n.getCustomPropU32('backgroundColor', 0x00000000)),
    version: n.getCustomPropU32('version', QrVersions.auto),
    errorCorrectionLevel: n.getCustomPropU32('errorCorrectionLevel', QrErrorCorrectLevel.L),
    constrainErrorBounds: n.getCustomPropU32('constrainErrorBounds', 1) != 0,
    gapless: n.getCustomPropU32('gapless', 1) != 0,
    semanticsLabel: n.getCustomPropStr('semanticsLabel') ?? 'qr code',
    embeddedImageEmitsError: n.getCustomPropU32('embeddedImageEmitsError', 0) != 0,
    foregroundColor: Color(n.getCustomPropU32('foregroundColor', 0xFF000000)),
  );
}

Widget _build_ShimmerFromColors(NodeState n, SkalBridge bridge) {
  return Shimmer.fromColors(
    child: n.childCount > 0 ? SkalNode(nodeId: n.childAt(0), bridge: bridge, key: ValueKey<int>(n.childAt(0))) : const SizedBox.shrink(),
    baseColor: Color(n.getCustomPropU32('baseColor', 0xFF000000)),
    highlightColor: Color(n.getCustomPropU32('highlightColor', 0xFF000000)),
    period: Duration(milliseconds: n.getCustomPropU32('period', 1500)),
    direction: ShimmerDirection.values[n.getCustomPropU32('direction', 0)],
    loop: n.getCustomPropU32('loop', 0),
    enabled: n.getCustomPropU32('enabled', 1) != 0,
  );
}

void registerAll() {
  SkalRegistry.registerWidget('qrImageView', _build_QrImageView);
  SkalRegistry.registerWidget('shimmerFromColors', _build_ShimmerFromColors);
}
