// build_runner integration entry point.
//
// Lets devs run `dart run build_runner build` (or `… watch`) to invoke
// skal_codegen the same way they'd invoke any other Dart code
// generator. Standard ecosystem ergonomics: tooling integration, IDE
// hooks, file watching, parallel build steps.
//
// How to opt in (consumer side):
//
//   1. Add to pubspec.yaml:
//        dev_dependencies:
//          build_runner: ^2.4.0
//          skal_codegen: { path: ../codegen/skal_codegen }
//
//   2. Create `lib/skal_codegen.yaml` (the marker file) containing:
//        packages:
//          - qr_flutter
//          - video_player
//
//   3. Run `dart run build_runner build`.
//
//   4. Import the generated file from main.dart:
//        import 'skal_codegen.g.dart' as gen;
//        gen.registerAll();
//
// Why a marker file rather than reading the consumer's pubspec.yaml?
//
//   build_runner's output-path derivation is suffix-based — each
//   builder declares "input extension → output extension" pairs, and
//   the engine computes the output path by substituting the input's
//   trailing match. That works cleanly when every input file maps to
//   a paired output ("`.dart` → `.freezed.dart`" alongside).
//
//   Using `$lib$` (build_runner's "synthetic per-package input")
//   forces an awkward path resolution where build_runner's
//   computed expected output path didn't match what we'd write —
//   spent significant time fighting double-`lib/` issues. The marker
//   file pattern is the standard ecosystem alternative + works
//   out-of-the-box with no path tricks.
//
// What we generate:
//
//   For each package listed in skal_codegen.yaml, the Builder
//   resolves its lib/ via the consumer's
//   `.dart_tool/package_config.json`, walks every .dart file, runs
//   the generator, and combines the adapters from all packages into
//   ONE output file (`lib/skal_codegen.g.dart`). Single registerAll(),
//   single import in main.dart.
//
// Limitations of this MVP:
//
//   • Watch mode picks up changes to skal_codegen.yaml automatically
//     (it's the declared input), but NOT to pubspec.lock or the
//     wrapped packages' source files. Workaround: re-run
//     `build_runner build` after `flutter pub upgrade`.
//
//   • Every build regenerates from scratch — no incremental.
//     Acceptable: an analyzer pass over a single package takes ~1s.

// `libraryElement2` is marked @experimental until the analyzer's new
// element model stabilizes. See codegen/skal_codegen/lib/src/type_mapper.dart
// for the full rationale.
// ignore_for_file: experimental_member_use

import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:analyzer/dart/analysis/analysis_context_collection.dart';
import 'package:analyzer/dart/analysis/results.dart';
import 'package:analyzer/file_system/physical_file_system.dart';
import 'package:build/build.dart';
import 'package:path/path.dart' as p;
import 'package:yaml/yaml.dart';

import 'src/generator.dart';

/// Builder factory — referenced by name from `build.yaml`. build_runner
/// calls this once per build target and gets back a Builder it then
/// drives via `build()`.
Builder skalBuilder(BuilderOptions options) => _SkalAdapterBuilder();

class _SkalAdapterBuilder implements Builder {
  /// Suffix-based mapping. The build engine derives the output path
  /// by swapping `skal_codegen.yaml` → `skal_codegen.g.dart` against
  /// the input path. So input `lib/skal_codegen.yaml` → output
  /// `lib/skal_codegen.g.dart`. Clean and predictable.
  @override
  final Map<String, List<String>> buildExtensions = const {
    'skal_codegen.yaml': ['skal_codegen.g.dart'],
  };

  @override
  Future<void> build(BuildStep buildStep) async {
    final pkgName = buildStep.inputId.package;
    final outputAsset = AssetId(
      pkgName,
      buildStep.inputId.path
          .replaceFirst(RegExp(r'skal_codegen\.yaml$'), 'skal_codegen.g.dart'),
    );

    // Read the marker file the dev created to opt in.
    final markerYaml = await buildStep.readAsString(buildStep.inputId);
    final packages = _readPackagesFromMarker(markerYaml);
    if (packages.isEmpty) {
      log.info('skal_codegen: ${buildStep.inputId.path} has no '
          '`packages:` list — emitting empty registerAll()');
      await buildStep.writeAsString(outputAsset,
          '// GENERATED by skal_codegen — no `packages:` in '
          '${buildStep.inputId.path}.\n\nvoid registerAll() {}\n');
      return;
    }

    // build_runner's cwd IS the consumer's project root during a
    // build. Analyzer needs an absolute path anchor + access to
    // `.dart_tool/package_config.json` to resolve `package:flutter/…`
    // and pub-cache packages.
    final pkgRoot = p.normalize(p.absolute('.'));

    // Single analyzer context anchored at the consumer's project,
    // same strategy as the CLI. Resolving via the consumer's
    // package_config lets us find Widget classes inside pub-cache
    // AND resolve their `package:` imports correctly.
    final collection = AnalysisContextCollection(
      includedPaths: [pkgRoot],
      resourceProvider: PhysicalResourceProvider.INSTANCE,
    );
    final ctx = collection.contexts.first;

    // Gather inputs across ALL wrapped packages so we run one
    // generator invocation and emit one combined file.
    final allUnits = <ResolvedUnitResult>[];
    for (final wrappedPkg in packages) {
      final libDir = _resolvePackageLibDir(pkgRoot, wrappedPkg);
      if (libDir == null) {
        log.warning('skal_codegen: package "$wrappedPkg" not found in '
            '.dart_tool/package_config.json — did you `flutter pub get`?');
        continue;
      }
      final inputFiles = _walkDartFiles(libDir).toList()..sort();
      for (final input in inputFiles) {
        final unitResult = await ctx.currentSession.getResolvedUnit(input);
        if (unitResult is ResolvedUnitResult) allUnits.add(unitResult);
      }
    }

    // For inputs from pub-cache, the natural import is the wrapped
    // package's canonical entry-point (`package:foo/foo.dart`) —
    // brings in transitive re-exports (enum constants, value classes)
    // referenced by constructor defaults.
    final outputAbsPath = p.join(pkgRoot, outputAsset.path);
    final relImports = [
      for (final unit in allUnits)
        if (unit.libraryElement2.uri.scheme == 'package' &&
            unit.libraryElement2.uri.pathSegments.isNotEmpty)
          'package:${unit.libraryElement2.uri.pathSegments.first}/'
              '${unit.libraryElement2.uri.pathSegments.first}.dart'
        else
          p.relative(unit.path, from: p.dirname(outputAbsPath))
    ];

    final result = generate(
      units: allUnits,
      sourceRelativeImports: relImports,
    );

    await buildStep.writeAsString(outputAsset, result.source);
    log.info('skal_codegen: ${result.generated.length} widget(s) from '
        '${packages.length} package(s) → ${outputAsset.path}');
    // Surface every skipped widget. Each one is a place where the dev
    // either needs a 5-line manual adapter (most common) or has to
    // wait for the codegen to grow support for the offending type.
    // The Builder log goes through build_runner's stderr; warnings
    // show up in the colored `[WARNING]` section of `build` output.
    for (final w in result.skipped) {
      log.warning(
          'skal_codegen: skipped ${w.className} — ${w.skipReason}. '
          'Write a manual SkalRegistry.registerWidget call to wrap it.');
    }
  }
}

/// Pull the `packages:` list out of a skal_codegen.yaml marker file.
/// Returns an empty list if the field is missing or malformed.
List<String> _readPackagesFromMarker(String markerYaml) {
  final parsed = loadYaml(markerYaml);
  if (parsed is! YamlMap) return const [];
  final pkgs = parsed['packages'];
  if (pkgs is! YamlList) return const [];
  return pkgs.cast<String>().toList();
}

/// Resolve a wrapped-package's lib/ on disk, via
/// `<consumerRoot>/.dart_tool/package_config.json`. Returns null if
/// the consumer hasn't pub-get'd or the package isn't listed.
///
/// Mirrors the CLI's `_resolvePackageLibDir`; duplicated here rather
/// than imported because the CLI lives under bin/ (not exported).
String? _resolvePackageLibDir(String pkgRoot, String packageName) {
  final cfgPath = p.join(pkgRoot, '.dart_tool', 'package_config.json');
  final cfgFile = File(cfgPath);
  if (!cfgFile.existsSync()) return null;

  final Map<String, dynamic> cfg;
  try {
    cfg = jsonDecode(cfgFile.readAsStringSync()) as Map<String, dynamic>;
  } on FormatException {
    return null;
  }
  final pkgs = (cfg['packages'] as List?) ?? const [];
  for (final entry in pkgs.cast<Map<String, dynamic>>()) {
    if (entry['name'] != packageName) continue;
    final rootUri = entry['rootUri'] as String?;
    final packageUri = entry['packageUri'] as String?;
    if (rootUri == null) return null;
    final base = Uri.file(p.join(pkgRoot, '.dart_tool/'));
    final resolved = base.resolve(rootUri);
    return p.normalize(p.join(resolved.toFilePath(), packageUri ?? 'lib/'));
  }
  return null;
}

/// Recursively yield `.dart` files under [dir], skipping `*.g.dart` and
/// hidden directories.
Iterable<String> _walkDartFiles(String dir) sync* {
  for (final entity in Directory(dir).listSync(recursive: true, followLinks: false)) {
    if (entity is! File) continue;
    final path = entity.path;
    if (!path.endsWith('.dart')) continue;
    if (path.endsWith('.g.dart')) continue;
    final segments = p.split(p.relative(path, from: dir));
    if (segments.any((s) => s.startsWith('.'))) continue;
    yield p.normalize(p.absolute(path));
  }
}
