// build_runner integration entry point.
//
// Lets devs run `dart run build_runner build` (or `… watch`) to invoke
// skal_codegen the same way they'd invoke any other Dart code
// generator. Standard ecosystem ergonomics: tooling integration, IDE
// hooks, file watching, parallel build steps.
//
// How to opt in (consumer side):
//
//   1. Add to pubspec.yaml:
//        dev_dependencies:
//          build_runner: ^2.4.0
//          skal_codegen: { path: ../codegen/skal_codegen }
//
//   2. Create `lib/skal_codegen.yaml` (the marker file) containing:
//        packages:
//          - qr_flutter
//          - video_player
//
//   3. Run `dart run build_runner build`.
//
//   4. Import the generated file from main.dart:
//        import 'skal_codegen.g.dart' as gen;
//        gen.registerAll();
//
// Why a marker file rather than reading the consumer's pubspec.yaml?
//
//   build_runner's output-path derivation is suffix-based — each
//   builder declares "input extension → output extension" pairs, and
//   the engine computes the output path by substituting the input's
//   trailing match. That works cleanly when every input file maps to
//   a paired output ("`.dart` → `.freezed.dart`" alongside).
//
//   Using `$lib$` (build_runner's "synthetic per-package input")
//   forces an awkward path resolution where build_runner's
//   computed expected output path didn't match what we'd write —
//   spent significant time fighting double-`lib/` issues. The marker
//   file pattern is the standard ecosystem alternative + works
//   out-of-the-box with no path tricks.
//
// What we generate:
//
//   For each package listed in skal_codegen.yaml, the Builder
//   resolves its lib/ via the consumer's
//   `.dart_tool/package_config.json`, walks every .dart file, runs
//   the generator, and combines the adapters from all packages into
//   ONE output file (`lib/skal_codegen.g.dart`). Single registerAll(),
//   single import in main.dart.
//
// Limitations of this MVP:
//
//   • Watch mode picks up changes to skal_codegen.yaml automatically
//     (it's the declared input), but NOT to pubspec.lock or the
//     wrapped packages' source files. Workaround: re-run
//     `build_runner build` after `flutter pub upgrade`.
//
//   • Every build regenerates from scratch — no incremental.
//     Acceptable: an analyzer pass over a single package takes ~1s.

// `libraryElement2` is marked @experimental until the analyzer's new
// element model stabilizes. See codegen/skal_codegen/lib/src/type_mapper.dart
// for the full rationale.
// ignore_for_file: experimental_member_use

import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:analyzer/dart/analysis/analysis_context_collection.dart';
import 'package:analyzer/dart/analysis/results.dart';
import 'package:analyzer/dart/element/element2.dart';
import 'package:analyzer/dart/element/type.dart';
import 'package:analyzer/file_system/physical_file_system.dart';
import 'package:build/build.dart';
import 'package:path/path.dart' as p;
import 'package:yaml/yaml.dart';

import 'src/generator.dart';

/// Builder factory — referenced by name from `build.yaml`. build_runner
/// calls this once per build target and gets back a Builder it then
/// drives via `build()`.
Builder skalBuilder(BuilderOptions options) => _SkalAdapterBuilder();

class _SkalAdapterBuilder implements Builder {
  /// Suffix-based mapping. Two outputs:
  ///
  ///   • `skal_codegen.g.dart` — the Dart adapter that the consumer's
  ///     main.dart imports + calls registerAll() on.
  ///
  ///   • `skal_codegen.json` — a JSON manifest of every wrapped
  ///     widget's (className, registryKey). The Vite-side
  ///     vite-plugin-skal-codegen.js reads this to auto-configure
  ///     the JSX module + babel macro without the dev having to edit
  ///     vite.config.js per wrapped widget. Output filename matches
  ///     the input by suffix swap, same as the Dart output.
  @override
  final Map<String, List<String>> buildExtensions = const {
    'skal_codegen.yaml': ['skal_codegen.g.dart', 'skal_codegen.json'],
  };

  @override
  Future<void> build(BuildStep buildStep) async {
    final pkgName = buildStep.inputId.package;
    final outputAsset = AssetId(
      pkgName,
      buildStep.inputId.path
          .replaceFirst(RegExp(r'skal_codegen\.yaml$'), 'skal_codegen.g.dart'),
    );

    // Read the marker file the dev created to opt in.
    final markerYaml = await buildStep.readAsString(buildStep.inputId);
    final packages = _readPackagesFromMarker(markerYaml);
    final hostEntries = _readHostsFromMarker(markerYaml);
    if (packages.isEmpty && hostEntries.isEmpty) {
      log.info('skal_codegen: ${buildStep.inputId.path} has no '
          '`packages:` list — emitting empty registerAll()');
      await buildStep.writeAsString(outputAsset,
          '// GENERATED by skal_codegen — no `packages:` in '
          '${buildStep.inputId.path}.\n\nvoid registerAll() {}\n');
      // Emit an empty manifest too — build_runner expects every
      // declared output to be written, and downstream consumers
      // (vite-plugin-skal-codegen) handle the empty case cleanly.
      final manifestAsset = AssetId(
        pkgName,
        buildStep.inputId.path
            .replaceFirst(RegExp(r'skal_codegen\.yaml$'),
                'skal_codegen.json'),
      );
      await buildStep.writeAsString(
          manifestAsset, '{"widgets": {}}\n');
      return;
    }

    // build_runner's cwd IS the consumer's project root during a
    // build. Analyzer needs an absolute path anchor + access to
    // `.dart_tool/package_config.json` to resolve `package:flutter/…`
    // and pub-cache packages.
    final pkgRoot = p.normalize(p.absolute('.'));

    // Single analyzer context anchored at the consumer's project,
    // same strategy as the CLI. Resolving via the consumer's
    // package_config lets us find Widget classes inside pub-cache
    // AND resolve their `package:` imports correctly.
    final collection = AnalysisContextCollection(
      includedPaths: [pkgRoot],
      resourceProvider: PhysicalResourceProvider.INSTANCE,
    );
    final ctx = collection.contexts.first;

    // Gather inputs across ALL wrapped packages so we run one
    // generator invocation and emit one combined file.
    final allUnits = <ResolvedUnitResult>[];
    for (final wrappedPkg in packages) {
      final libDir = _resolvePackageLibDir(pkgRoot, wrappedPkg);
      if (libDir == null) {
        log.warning('skal_codegen: package "$wrappedPkg" not found in '
            '.dart_tool/package_config.json — did you `flutter pub get`?');
        continue;
      }
      final inputFiles = _walkDartFiles(libDir).toList()..sort();
      for (final input in inputFiles) {
        final unitResult = await ctx.currentSession.getResolvedUnit(input);
        if (unitResult is ResolvedUnitResult) allUnits.add(unitResult);
      }
    }

    // For inputs from pub-cache, the natural import is the wrapped
    // package's canonical entry-point (`package:foo/foo.dart`) —
    // brings in transitive re-exports (enum constants, value classes)
    // referenced by constructor defaults.
    final outputAbsPath = p.join(pkgRoot, outputAsset.path);
    final relImports = [
      for (final unit in allUnits)
        if (unit.libraryElement2.uri.scheme == 'package' &&
            unit.libraryElement2.uri.pathSegments.isNotEmpty)
          'package:${unit.libraryElement2.uri.pathSegments.first}/'
              '${unit.libraryElement2.uri.pathSegments.first}.dart'
        else
          p.relative(unit.path, from: p.dirname(outputAbsPath))
    ];

    // Resolve host configs — each maps a JSX symbol → controller-
    // owning StatefulWidget the generator synthesizes. Done after
    // the analyzer context is up so factory-function resolution can
    // share the same package_config-anchored context.
    final hosts = await _resolveHosts(collection, pkgRoot, hostEntries);

    final result = generate(
      units: allUnits,
      sourceRelativeImports: relImports,
      hosts: hosts,
    );

    await buildStep.writeAsString(outputAsset, result.source);
    log.info('skal_codegen: ${result.generated.length} widget(s) from '
        '${packages.length} package(s) + ${hosts.length} host(s) → '
        '${outputAsset.path}');

    // Emit the JSON manifest. vite-plugin-skal-codegen.js reads this
    // at build time to materialize the JSX-side `skal-codegen-generated`
    // module + register every widget name with the babel macro. Format
    // is intentionally minimal — one entry per generated widget, keyed
    // by Dart class name (the JSX-side capitalized symbol), valued
    // with the lowercase tag the renderer's TAG_TO_WIDGET fallthrough
    // path resolves.
    final manifestAsset = AssetId(
      pkgName,
      buildStep.inputId.path
          .replaceFirst(RegExp(r'skal_codegen\.yaml$'),
              'skal_codegen.json'),
    );
    final manifest = {
      'widgets': {
        for (final w in result.generated) w.className: w.registryKey,
      },
    };
    await buildStep.writeAsString(
        manifestAsset, const JsonEncoder.withIndent('  ').convert(manifest));

    // Surface every skipped widget. Each one is a place where the dev
    // either needs a 5-line manual adapter (most common) or has to
    // wait for the codegen to grow support for the offending type.
    // The Builder log goes through build_runner's stderr; warnings
    // show up in the colored `[WARNING]` section of `build` output.
    for (final w in result.skipped) {
      log.warning(
          'skal_codegen: skipped ${w.className} — ${w.skipReason}. '
          'Write a manual SkalRegistry.registerWidget call to wrap it.');
    }
  }
}

/// Pull the `packages:` list out of a skal_codegen.yaml marker file.
/// Returns an empty list if the field is missing or malformed.
List<String> _readPackagesFromMarker(String markerYaml) {
  final parsed = loadYaml(markerYaml);
  if (parsed is! YamlMap) return const [];
  final pkgs = parsed['packages'];
  if (pkgs is! YamlList) return const [];
  return pkgs.cast<String>().toList();
}

/// One entry in the marker file's `hosts:` map — declared by the
/// dev to ask codegen for a stateful-controller adapter pattern
/// (StatefulWidget wrapper around a controller-owning factory)
/// instead of a pure prop-encoding adapter.
///
/// Sample YAML:
///
///   hosts:
///     Camera:                                             # ← key = jsxName
///       widget: CameraPreview                             # ← wrappedWidgetName
///       factory: package:skal_flutter/adapters/camera_factory.dart#createCamera
///                ↑ importUri                              ↑ factoryFnName
class _HostMarkerEntry {
  final String jsxName;
  final String wrappedWidgetName;
  final String factoryImport;
  final String factoryFnName;
  _HostMarkerEntry(this.jsxName, this.wrappedWidgetName, this.factoryImport,
      this.factoryFnName);
}

/// Parse the marker file's `hosts:` section into raw entries. Each
/// entry still needs analyzer resolution (factory function lookup)
/// before it becomes a [HostConfig] the generator can consume.
List<_HostMarkerEntry> _readHostsFromMarker(String markerYaml) {
  final parsed = loadYaml(markerYaml);
  if (parsed is! YamlMap) return const [];
  final hosts = parsed['hosts'];
  if (hosts is! YamlMap) return const [];
  final out = <_HostMarkerEntry>[];
  for (final entry in hosts.entries) {
    final jsxName = entry.key.toString();
    final value = entry.value;
    if (value is! YamlMap) continue;
    final widget = value['widget']?.toString();
    final factory = value['factory']?.toString();
    if (widget == null || factory == null) continue;
    // Split on the `#` separator: `pkg:foo.dart#fnName`.
    final hash = factory.indexOf('#');
    if (hash < 0) continue;
    final factoryImport = factory.substring(0, hash);
    final factoryFn = factory.substring(hash + 1);
    if (factoryImport.isEmpty || factoryFn.isEmpty) continue;
    out.add(_HostMarkerEntry(jsxName, widget, factoryImport, factoryFn));
  }
  return out;
}

/// Walk the analyzer context for each marker-file host entry,
/// resolving its factory function. Returns one [HostConfig] per
/// successfully-resolved entry; entries whose factory function
/// can't be found get a warning + skip.
Future<List<HostConfig>> _resolveHosts(
  AnalysisContextCollection collection,
  String pkgRoot,
  List<_HostMarkerEntry> entries,
) async {
  final ctx = collection.contexts.first;
  final out = <HostConfig>[];
  for (final e in entries) {
    // Resolve the factory import URI to a filesystem path. The URI
    // is a `package:` form; we need a file path the analyzer can
    // resolve via getResolvedUnit.
    final filePath =
        _resolvePackageUriToPath(pkgRoot, Uri.parse(e.factoryImport));
    if (filePath == null) {
      log.warning('skal_codegen: host "${e.jsxName}" — couldn\'t resolve '
          'factory import ${e.factoryImport}. Skipping.');
      continue;
    }
    final unit = await ctx.currentSession.getResolvedUnit(filePath);
    if (unit is! ResolvedUnitResult) {
      log.warning('skal_codegen: host "${e.jsxName}" — analyzer couldn\'t '
          'resolve $filePath. Skipping.');
      continue;
    }
    // Find the top-level function with the declared name.
    ExecutableElement2? factoryFn;
    for (final fn in unit.libraryElement2.topLevelFunctions) {
      if (fn.name3 == e.factoryFnName) {
        factoryFn = fn;
        break;
      }
    }
    if (factoryFn == null) {
      log.warning('skal_codegen: host "${e.jsxName}" — no top-level '
          'function `${e.factoryFnName}` in ${e.factoryImport}. Skipping.');
      continue;
    }
    // Wrapped widget import. Two strategies, in order:
    //
    //   1. Derive from the factory's return type. The controller's
    //      package usually re-exports the widget (e.g. camera's
    //      barrel `package:camera/camera.dart` exports both
    //      CameraController AND CameraPreview). This is the strongest
    //      signal — no traversal of import graphs needed.
    //
    //   2. Fallback: the factory's own file. Works when the dev's
    //      factory file imports the wrapped widget directly.
    //
    // A v2 could let devs declare `widgetImport:` explicitly to
    // cover the edge cases (different package, narrow `src/` URI).
    final wrappedImport = _deriveWrappedWidgetImport(factoryFn) ??
        e.factoryImport;
    out.add(HostConfig(
      jsxName: e.jsxName,
      wrappedWidgetName: e.wrappedWidgetName,
      factoryFn: factoryFn,
      factoryImport: e.factoryImport,
      wrappedWidgetImport: wrappedImport,
    ));
  }
  return out;
}

/// Resolve a `package:foo/bar.dart` URI to an absolute filesystem
/// path, via the consumer's `.dart_tool/package_config.json`.
String? _resolvePackageUriToPath(String pkgRoot, Uri pkgUri) {
  if (pkgUri.scheme != 'package' || pkgUri.pathSegments.isEmpty) return null;
  final pkgName = pkgUri.pathSegments.first;
  final libDir = _resolvePackageLibDir(pkgRoot, pkgName);
  if (libDir == null) return null;
  // Everything after the package name is the path inside lib/.
  final rest = pkgUri.pathSegments.skip(1).join('/');
  return p.normalize(p.join(libDir, rest));
}

/// Derive the wrapped-widget's canonical import URI from the
/// factory function's return type. The controller's library
/// (`package:camera/src/camera_controller.dart` for camera) usually
/// has a sibling barrel (`package:camera/camera.dart`) that re-
/// exports BOTH the controller AND the widget that takes it. We
/// derive the barrel from the first path segment of the controller's
/// library URI.
///
/// Returns null when the factory's return type isn't from a `package:`
/// URI (caller falls back to the factory file itself in that case).
String? _deriveWrappedWidgetImport(ExecutableElement2 factoryFn) {
  // Unwrap Future<T> → T to get the controller's actual type.
  var t = factoryFn.returnType;
  if (t.element3?.name3 == 'Future') {
    if (t is InterfaceType && t.typeArguments.length == 1) {
      t = t.typeArguments.first;
    }
  }
  final lib = t.element3?.library2;
  if (lib == null) return null;
  final uri = lib.uri;
  if (uri.scheme != 'package' || uri.pathSegments.isEmpty) return null;
  final pkg = uri.pathSegments.first;
  return 'package:$pkg/$pkg.dart';
}

/// Resolve a wrapped-package's lib/ on disk, via
/// `<consumerRoot>/.dart_tool/package_config.json`. Returns null if
/// the consumer hasn't pub-get'd or the package isn't listed.
///
/// Mirrors the CLI's `_resolvePackageLibDir`; duplicated here rather
/// than imported because the CLI lives under bin/ (not exported).
String? _resolvePackageLibDir(String pkgRoot, String packageName) {
  final cfgPath = p.join(pkgRoot, '.dart_tool', 'package_config.json');
  final cfgFile = File(cfgPath);
  if (!cfgFile.existsSync()) return null;

  final Map<String, dynamic> cfg;
  try {
    cfg = jsonDecode(cfgFile.readAsStringSync()) as Map<String, dynamic>;
  } on FormatException {
    return null;
  }
  final pkgs = (cfg['packages'] as List?) ?? const [];
  for (final entry in pkgs.cast<Map<String, dynamic>>()) {
    if (entry['name'] != packageName) continue;
    final rootUri = entry['rootUri'] as String?;
    final packageUri = entry['packageUri'] as String?;
    if (rootUri == null) return null;
    final base = Uri.file(p.join(pkgRoot, '.dart_tool/'));
    final resolved = base.resolve(rootUri);
    return p.normalize(p.join(resolved.toFilePath(), packageUri ?? 'lib/'));
  }
  return null;
}

/// Recursively yield `.dart` files under [dir], skipping `*.g.dart` and
/// hidden directories.
Iterable<String> _walkDartFiles(String dir) sync* {
  for (final entity in Directory(dir).listSync(recursive: true, followLinks: false)) {
    if (entity is! File) continue;
    final path = entity.path;
    if (!path.endsWith('.dart')) continue;
    if (path.endsWith('.g.dart')) continue;
    final segments = p.split(p.relative(path, from: dir));
    if (segments.any((s) => s.startsWith('.'))) continue;
    yield p.normalize(p.absolute(path));
  }
}
