#!/usr/bin/env bash
# new-app.sh — scaffold a new Skal app under examples/<name>/.
#
# Usage:
#   scripts/new-app.sh my-app
#
# Creates a kebab-case-named workspace package + flutter-host stub.
# Platform configs (android/, ios/, macos/) are NOT generated by this
# script — the new app's README explains how to add them via
# `flutter create` once you've decided which platforms you want.
#
# What this script DOES:
#   1. Copies scripts/templates/default/ into examples/<name>/
#   2. Substitutes the name into package.json, pubspec.yaml,
#      main.dart, README, html title.
#   3. Runs `bun install` at the repo root so the new workspace
#      package is registered + dependencies are hoisted.
#
# What you still have to do manually:
#   - flutter create --platforms ... inside flutter-host/
#   - scripts/link-libskal-flutter-{mac,}.sh to install libskal
#     into the new platform configs (or copy from kitchen-sink/)
#   - flutter pub get + flutter run

set -euo pipefail

# ── arg parse ────────────────────────────────────────────────────────
if [[ $# -lt 1 ]]; then
  echo "usage: $0 <app-name>" >&2
  echo "   eg: $0 my-app" >&2
  exit 1
fi

NAME="$1"

# Name must be kebab-case: lowercase letters, digits, single hyphens.
# Bun workspaces + Dart pubspec both accept these without escaping.
if ! [[ "${NAME}" =~ ^[a-z][a-z0-9-]*[a-z0-9]$ ]] && ! [[ "${NAME}" =~ ^[a-z]$ ]]; then
  echo "error: name must be kebab-case (lowercase + digits + hyphens), got: ${NAME}" >&2
  exit 1
fi

# Dart package names disallow hyphens — derive a snake_case variant.
NAME_SNAKE="${NAME//-/_}"

# ── paths ────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
TEMPLATE="${SCRIPT_DIR}/templates/default"
TARGET="${REPO_ROOT}/examples/${NAME}"

if [[ ! -d "${TEMPLATE}" ]]; then
  echo "error: template dir missing: ${TEMPLATE}" >&2
  exit 1
fi

if [[ -e "${TARGET}" ]]; then
  echo "error: target exists: ${TARGET}" >&2
  echo "       remove it first, or pick a different name." >&2
  exit 1
fi

# ── copy + substitute ────────────────────────────────────────────────
echo "→ Creating ${TARGET}"
mkdir -p "${TARGET}"

# tar-pipe rather than cp -R so we control which files come along
# (skips .DS_Store, node_modules, etc. — none in the template today
# but future-proof against operator error).
( cd "${TEMPLATE}" && tar cf - \
    --exclude='node_modules' \
    --exclude='.DS_Store' \
    --exclude='dist' \
    --exclude='build' \
    . ) | ( cd "${TARGET}" && tar xf - )

# Token-substitute __APP_NAME__ → kebab, __APP_NAME_SNAKE__ → snake.
# Touched files: every text file under the new tree (sed -i'' on macOS
# needs an empty backup extension passed positionally; GNU sed treats it
# as an empty extension argument).
while IFS= read -r f; do
  case "${f}" in
    *.png|*.jpg|*.ico|*.gz|*.zip|*/assets/*) continue ;;
  esac
  sed -i.bak \
    -e "s/__APP_NAME_SNAKE__/${NAME_SNAKE}/g" \
    -e "s/__APP_NAME__/${NAME}/g" \
    "${f}"
  rm -f "${f}.bak"
done < <(find "${TARGET}" -type f \( \
    -name '*.json' -o -name '*.jsx' -o -name '*.js' -o -name '*.html' \
    -o -name '*.md' -o -name '*.yaml' -o -name '*.dart' -o -name '*.sh' \
    -o -name '*.cjs' \
  \))

chmod +x "${TARGET}/scripts/find-vendored-bun.sh" 2>/dev/null || true

# ── install ──────────────────────────────────────────────────────────
echo "→ Running 'bun install' at the repo root to hoist the new workspace"
( cd "${REPO_ROOT}" && bun install )

# ── next steps ───────────────────────────────────────────────────────
cat <<EOF

✓ Scaffolded examples/${NAME}/

Next steps:

  # Add Flutter platform configs (pick whichever platforms you want):
  cd examples/${NAME}/flutter-host
  flutter create --org com.example --project-name ${NAME_SNAKE} \\
    --platforms macos,ios,android .

  # Install libskal binaries into the new platform dirs (host arch only):
  cd ${REPO_ROOT}
  SKAL_FLUTTER_FRAMEWORKS=\$PWD/examples/${NAME}/flutter-host/macos/Frameworks \\
    scripts/link-libskal-flutter-mac.sh
  SKAL_FLUTTER_NATIVE_LIBS=\$PWD/examples/${NAME}/flutter-host/android/app/src/main/jniLibs/arm64-v8a \\
    scripts/link-libskal-flutter.sh
  # (assumes vendor/bun/build/{release,android} are already built)

  # Build the JS bundle + run:
  cd examples/${NAME}
  bun run build
  cd flutter-host && flutter pub get && flutter run -d macos

  # …or just the web preview:
  cd examples/${NAME}
  bun run dev:web   # → http://localhost:5173
EOF
