// build_runner integration entry point.
//
// Lets devs run `dart run build_runner build` (or `… watch`) to invoke
// skal_codegen the same way they'd invoke any other Dart code
// generator. Standard ecosystem ergonomics: tooling integration, IDE
// hooks, file watching, parallel build steps.
//
// How to opt in (consumer side):
//
//   1. Add to pubspec.yaml:
//        dev_dependencies:
//          build_runner: ^2.4.0
//          skal_codegen: { path: ../packages/skal_codegen }
//
//   2. Create `lib/skal_codegen.yaml` (the marker file) containing:
//        packages:
//          - qr_flutter
//          - video_player
//
//   3. Run `dart run build_runner build`.
//
//   4. Import the generated file from main.dart:
//        import 'skal_codegen.g.dart' as gen;
//        gen.registerAll();
//
// Why a marker file rather than reading the consumer's pubspec.yaml?
//
//   build_runner's output-path derivation is suffix-based — each
//   builder declares "input extension → output extension" pairs, and
//   the engine computes the output path by substituting the input's
//   trailing match. That works cleanly when every input file maps to
//   a paired output ("`.dart` → `.freezed.dart`" alongside).
//
//   Using `$lib$` (build_runner's "synthetic per-package input")
//   forces an awkward path resolution where build_runner's
//   computed expected output path didn't match what we'd write —
//   spent significant time fighting double-`lib/` issues. The marker
//   file pattern is the standard ecosystem alternative + works
//   out-of-the-box with no path tricks.
//
// What we generate:
//
//   For each package listed in skal_codegen.yaml, the Builder
//   resolves its lib/ via the consumer's
//   `.dart_tool/package_config.json`, walks every .dart file, runs
//   the generator, and combines the adapters from all packages into
//   ONE output file (`lib/skal_codegen.g.dart`). Single registerAll(),
//   single import in main.dart.
//
// Limitations of this MVP:
//
//   • Watch mode picks up changes to skal_codegen.yaml automatically
//     (it's the declared input), but NOT to pubspec.lock or the
//     wrapped packages' source files. Workaround: re-run
//     `build_runner build` after `flutter pub upgrade`.
//
//   • Every build regenerates from scratch — no incremental.
//     Acceptable: an analyzer pass over a single package takes ~1s.

// `libraryElement2` is marked @experimental until the analyzer's new
// element model stabilizes. See packages/skal_codegen/lib/src/type_mapper.dart
// for the full rationale.
// ignore_for_file: experimental_member_use

import 'dart:async';
import 'dart:io';
import 'dart:convert';

import 'package:analyzer/dart/analysis/analysis_context_collection.dart';
import 'package:analyzer/dart/analysis/results.dart';
import 'package:analyzer/dart/element/element2.dart';
import 'package:analyzer/file_system/physical_file_system.dart';
import 'package:build/build.dart';
import 'package:path/path.dart' as p;
import 'package:yaml/yaml.dart';

import 'src/generator.dart';
import 'src/package_resolver.dart';

/// Builder factory — referenced by name from `build.yaml`. build_runner
/// calls this once per build target and gets back a Builder it then
/// drives via `build()`.
Builder skalBuilder(BuilderOptions options) => _SkalAdapterBuilder();

class _SkalAdapterBuilder implements Builder {
  /// Suffix-based mapping. Two outputs:
  ///
  ///   • `skal_codegen.g.dart` — the Dart adapter that the consumer's
  ///     main.dart imports + calls registerAll() on.
  ///
  ///   • `skal_codegen.json` — a JSON manifest of every wrapped
  ///     widget's (className, registryKey). The Vite-side
  ///     vite-plugin-skal-codegen.js reads this to auto-configure
  ///     the JSX module + babel macro without the dev having to edit
  ///     vite.config.js per wrapped widget. Output filename matches
  ///     the input by suffix swap, same as the Dart output.
  @override
  final Map<String, List<String>> buildExtensions = const {
    'skal_codegen.yaml': ['skal_codegen.g.dart', 'skal_codegen.json'],
  };

  @override
  Future<void> build(BuildStep buildStep) async {
    final pkgName = buildStep.inputId.package;
    final outputAsset = AssetId(
      pkgName,
      buildStep.inputId.path
          .replaceFirst(RegExp(r'skal_codegen\.yaml$'), 'skal_codegen.g.dart'),
    );

    // Read the marker file the dev created to opt in.
    final markerYaml = await buildStep.readAsString(buildStep.inputId);
    final packages = _readPackagesFromMarker(markerYaml);
    final hostEntries = _readHostsFromMarker(markerYaml);
    final serviceEntries = _readServicesFromMarker(markerYaml);
    if (packages.isEmpty && hostEntries.isEmpty && serviceEntries.isEmpty) {
      log.info('skal_codegen: ${buildStep.inputId.path} has none of '
          '`packages:`, `hosts:` or `services:` — emitting empty '
          'registerAll()');
      await buildStep.writeAsString(outputAsset,
          '// GENERATED by skal_codegen — none of `packages:`, `hosts:` '
          'or `services:` declared in ${buildStep.inputId.path}.\n\n'
          'void registerAll() {}\n');
      // Emit an empty manifest too — build_runner expects every
      // declared output to be written, and downstream consumers
      // (vite-plugin-skal-codegen) handle the empty case cleanly.
      final manifestAsset = AssetId(
        pkgName,
        buildStep.inputId.path
            .replaceFirst(RegExp(r'skal_codegen\.yaml$'),
                'skal_codegen.json'),
      );
      await buildStep.writeAsString(manifestAsset,
          '{"widgets": {}, "services": {}, "skipped": {"widgets": {}, '
          '"services": {}, "omittedProps": {}}}\n');
      return;
    }

    // build_runner's cwd IS the consumer's project root during a
    // build. Analyzer needs an absolute path anchor + access to
    // `.dart_tool/package_config.json` to resolve `package:flutter/…`
    // and pub-cache packages.
    final pkgRoot = p.normalize(p.absolute('.'));

    // Single analyzer context anchored at the consumer's project,
    // same strategy as the CLI. Resolving via the consumer's
    // package_config lets us find Widget classes inside pub-cache
    // AND resolve their `package:` imports correctly.
    final collection = AnalysisContextCollection(
      includedPaths: [pkgRoot],
      resourceProvider: PhysicalResourceProvider.INSTANCE,
    );
    final ctx = collection.contexts.first;

    // Gather inputs across ALL wrapped packages so we run one
    // generator invocation and emit one combined file.
    final allUnits = <ResolvedUnitResult>[];
    for (final wrappedPkg in packages) {
      final libDir = resolvePackageLibDir(pkgRoot, wrappedPkg);
      if (libDir == null) {
        log.warning('skal_codegen: package "$wrappedPkg" not found in '
            '.dart_tool/package_config.json — did you `flutter pub get`?');
        continue;
      }
      final inputFiles = walkDartFiles(libDir).toList()..sort();
      for (final input in inputFiles) {
        final unitResult = await ctx.currentSession.getResolvedUnit(input);
        if (unitResult is ResolvedUnitResult) allUnits.add(unitResult);
      }
    }

    // For inputs from pub-cache, the natural import is the wrapped
    // package's canonical entry-point (`package:foo/foo.dart`) —
    // brings in transitive re-exports (enum constants, value classes)
    // referenced by constructor defaults.
    final outputAbsPath = p.join(pkgRoot, outputAsset.path);
    final relImports = [
      for (final unit in allUnits)
        if (unit.libraryElement2.uri.scheme == 'package' &&
            unit.libraryElement2.uri.pathSegments.isNotEmpty)
          'package:${unit.libraryElement2.uri.pathSegments.first}/'
              '${unit.libraryElement2.uri.pathSegments.first}.dart'
        else
          p.relative(unit.path, from: p.dirname(outputAbsPath))
    ];

    // Resolve host configs — each maps a JSX symbol → controller-
    // owning StatefulWidget the generator synthesizes. Done after
    // the analyzer context is up so factory-function resolution can
    // share the same package_config-anchored context.
    final hosts = await _resolveHosts(collection, pkgRoot, hostEntries);
    final services =
        await _resolveServices(collection, pkgRoot, serviceEntries);

    final result = generate(
      units: allUnits,
      sourceRelativeImports: relImports,
      hosts: hosts,
      services: services,
      overrides: _readOverridesFromMarker(markerYaml),
      // Canonical-barrel lookup for src/-declared classes — see
      // _addCanonicalImport's conditional-export rationale.
      barrelResolver: (pkg) {
        final libDir = resolvePackageLibDir(pkgRoot, pkg);
        if (libDir == null) return null;
        return File(p.join(libDir, '$pkg.dart')).existsSync()
            ? 'package:$pkg/$pkg.dart'
            : null;
      },
    );

    await buildStep.writeAsString(outputAsset, result.source);
    log.info('skal_codegen: ${result.generated.length} widget(s) from '
        '${packages.length} package(s) + ${hosts.length} host(s) → '
        '${outputAsset.path}');

    // Emit the JSON manifest. vite-plugin-skal-codegen.js reads this
    // at build time to materialize the JSX-side `skal-flutter` module
    // (plugin default; configurable via `moduleName:`) and to register
    // every widget name with the babel macro. Format
    // is intentionally minimal — one entry per generated widget, keyed
    // by Dart class name (the JSX-side capitalized symbol), valued
    // with the lowercase tag the renderer's TAG_TO_WIDGET fallthrough
    // path resolves.
    final manifestAsset = AssetId(
      pkgName,
      buildStep.inputId.path
          .replaceFirst(RegExp(r'skal_codegen\.yaml$'),
              'skal_codegen.json'),
    );
    //
    // The `skipped` section is the B4 skip manifest. Until it existed,
    // a dropped widget was a build-log warning and nothing else — so a
    // dev who ran `build_runner` once and scrolled past had no way to
    // see what they'd lost or what to override. Writing it to the
    // manifest makes the loss inspectable after the fact, and gives
    // tooling something to diff.
    final manifest = {
      'widgets': {
        for (final w in result.generated) w.className: w.registryKey,
      },
      // B2 — registryKey → prop names the JS renderer must wire to the
      // indexed-builder protocol rather than to a plain callback.
      'builders': {
        for (final w in result.generated)
          if (w.builderParams.isNotEmpty) w.registryKey: w.builderParams,
      },
      'services': {
        for (final s in result.services)
          if (s.skipReason == null)
            s.name: {
              'class': s.className,
              'methods': s.methods,
              if (s.skippedMethods.isNotEmpty)
                'skippedMethods': s.skippedMethods,
              // Optional params dropped from a method's signature. The
              // slot still exists (declaration-ordinal) but is never
              // read — a JS caller passing a value there is ignored,
              // which is exactly why it's recorded.
              if (s.omittedParams.isNotEmpty)
                'omittedParams': s.omittedParams,
            },
      },
      'skipped': {
        'widgets': {
          for (final w in result.skipped) w.className: w.skipReason,
        },
        'services': {
          for (final s in result.services)
            if (s.skipReason != null) s.name: s.skipReason,
        },
        'omittedProps': {
          for (final w in result.generated)
            if (w.omittedOptionalParams.isNotEmpty)
              w.className: w.omittedOptionalParams,
        },
      },
    };
    await buildStep.writeAsString(
        manifestAsset, const JsonEncoder.withIndent('  ').convert(manifest));

    for (final key in result.unmatchedOverrideKeys) {
      log.warning('skal_codegen: overrides entry "$key" matched no '
          'widget. Key it by the JSX symbol (the synthesized name for '
          'a named constructor — e.g. ScrollablePositionedListBuilder) '
          'or the bare class name.');
    }

    for (final s in result.services) {
      if (s.skipReason != null) {
        log.warning('skal_codegen: service "${s.name}" produced nothing — '
            '${s.skipReason}.');
        continue;
      }
      log.info('skal_codegen: service "${s.name}" → ${s.className} '
          '(${s.methods.length} method(s)'
          '${s.skippedMethods.isEmpty ? '' : ', '
              '${s.skippedMethods.length} skipped'})');
      s.skippedMethods.forEach((m, why) {
        log.info('skal_codegen:   ${s.name}.$m — $why');
      });
    }

    // Surface every skipped widget. Each one is a place where the dev
    // either needs a 5-line manual adapter (most common) or has to
    // wait for the codegen to grow support for the offending type.
    // The Builder log goes through build_runner's stderr; warnings
    // show up in the colored `[WARNING]` section of `build` output.
    for (final w in result.skipped) {
      log.warning(
          'skal_codegen: skipped ${w.isValue ? "value " : ""}'
          '${w.className} — ${w.skipReason}. '
          'Write a manual SkalRegistry.registerWidget call to wrap it, '
          'or add an `overrides:` entry. Full list in skal_codegen.json '
          'under "skipped".');
    }
  }
}

/// Parse the marker file's `overrides:` section — the B4 escape valves.
///
///   overrides:
///     TileLayer:
///       imports: ['package:flutter_map/flutter_map.dart']
///       tileProvider: { const: 'NetworkTileProvider()' }
///       tileBuilder:  { ignore: true }
///
///     PolygonLayer:
///       typeArgs: [Object]          # B6 — pin a generic widget's type
///
/// `imports:` and `typeArgs:` are reserved at the widget level; every
/// other key is a constructor parameter name. A param genuinely named
/// `imports` or `typeArgs` is not reachable this way — an acceptable
/// trade for keeping the common case one level shallower.
Map<String, WidgetOverride> _readOverridesFromMarker(String markerYaml) {
  final parsed = loadYaml(markerYaml);
  if (parsed is! YamlMap) return const {};
  final overrides = parsed['overrides'];
  if (overrides is! YamlMap) return const {};
  final out = <String, WidgetOverride>{};
  for (final entry in overrides.entries) {
    final widget = entry.key.toString();
    final value = entry.value;
    if (value is! YamlMap) continue;
    final imports = <String>[];
    final typeArgs = <String>[];
    final params = <String, ParamOverride>{};
    for (final p in value.entries) {
      final key = p.key.toString();
      if (key == 'imports') {
        final v = p.value;
        if (v is YamlList) {
          imports.addAll(v.map((e) => e.toString()));
        } else if (v is String) {
          imports.add(v);
        }
        continue;
      }
      if (key == 'typeArgs') {
        final v = p.value;
        if (v is YamlList) {
          typeArgs.addAll(v.map((e) => e.toString()));
        } else if (v is String) {
          typeArgs.add(v);
        }
        continue;
      }
      final cfg = p.value;
      if (cfg is YamlMap) {
        final constExpr = cfg['const']?.toString();
        final ignore = cfg['ignore'] == true;
        final builder = cfg['builder'] == true;
        final handle = cfg['handle'] == true;
        params[key] = ParamOverride(
            constExpr: constExpr,
            ignore: ignore,
            builder: builder,
            handle: handle);
      } else if (cfg is String) {
        // Shorthand: `tileProvider: NetworkTileProvider()`.
        params[key] = ParamOverride(constExpr: cfg);
      } else if (cfg == null || cfg == false) {
        // `tileBuilder:` with nothing after it reads as "drop this".
        params[key] = const ParamOverride(ignore: true);
      }
    }
    out[widget] =
        WidgetOverride(params: params, imports: imports, typeArgs: typeArgs);
  }
  return out;
}

/// One entry in the marker file's `services:` section — a headless
/// native capability wrapped as root-node RPC (Roadmap A2). No factory
/// is needed, unlike `hosts:`, because a static method has no
/// constructor to cross the bridge.
///
/// Sample YAML — short and long form:
///
///   services:
///     - geolocator                  # class Geolocator, namespace 'geolocator'
///     clipboard:                    # explicit
///       package: flutter            # (optional) where to look
///       class: Clipboard
class _ServiceMarkerEntry {
  final String name;
  final String? packageName;
  final String? className;
  _ServiceMarkerEntry(this.name, this.packageName, this.className);
}

/// Parse the marker file's `services:` section. Accepts a list of
/// package names (short form) or a map of namespace → config.
/// A service name is pasted verbatim into generated single-quoted Dart
/// AND becomes a wire namespace split on `.` — so it must be a plain
/// identifier-ish token. A quote or `$` would emit uncompilable (or
/// interpolating) Dart with an opaque parser error pointing at a file
/// the dev is told never to edit; a dot would register a namespace the
/// dispatcher can never route.
final RegExp _kValidServiceName = RegExp(r'^[A-Za-z_][A-Za-z0-9_-]*$');

bool _checkServiceName(String name) {
  if (_kValidServiceName.hasMatch(name)) return true;
  log.warning('skal_codegen: service name "$name" is not a valid '
      'namespace (letters, digits, _ and - only; no dots or quotes). '
      'Skipping.');
  return false;
}

List<_ServiceMarkerEntry> _readServicesFromMarker(String markerYaml) {
  final parsed = loadYaml(markerYaml);
  if (parsed is! YamlMap) return const [];
  final services = parsed['services'];
  final out = <_ServiceMarkerEntry>[];
  if (services is YamlList) {
    for (final e in services) {
      final name = e.toString();
      if (name.isEmpty || !_checkServiceName(name)) continue;
      out.add(_ServiceMarkerEntry(name, name, null));
    }
    return out;
  }
  if (services is YamlMap) {
    for (final entry in services.entries) {
      final name = entry.key.toString();
      if (!_checkServiceName(name)) continue;
      final value = entry.value;
      if (value is YamlMap) {
        out.add(_ServiceMarkerEntry(
          name,
          value['package']?.toString(),
          value['class']?.toString(),
        ));
      } else if (value is String) {
        // `geolocator: Geolocator` — namespace on the left, class on
        // the right, package inferred from the namespace.
        out.add(_ServiceMarkerEntry(name, name, value));
      }
    }
  }
  return out;
}

/// Resolve each `services:` entry to the class whose static methods
/// become the dispatch table.
///
/// Class-name inference for the short form: PascalCase the package
/// name (`geolocator` → `Geolocator`, `share_plus` → `SharePlus`) and,
/// failing that, take the first class in the package's entry-point
/// namespace that actually declares static methods. That second rule
/// is what makes `- share_plus` work, where the class is `Share`.
Future<List<ServiceConfig>> _resolveServices(
  AnalysisContextCollection collection,
  String pkgRoot,
  List<_ServiceMarkerEntry> entries,
) async {
  final ctx = collection.contexts.first;
  final out = <ServiceConfig>[];
  for (final e in entries) {
    final pkg = e.packageName ?? e.name;
    final libDir = resolvePackageLibDir(pkgRoot, pkg);
    if (libDir == null) {
      log.warning('skal_codegen: service "${e.name}" — package "$pkg" not '
          'found in .dart_tool/package_config.json. Did you '
          '`flutter pub get`? Skipping.');
      continue;
    }
    // Search every library in the package, not just the entry point:
    // a plugin's capability class often lives in `src/` and is only
    // re-exported.
    ClassElement2? found;
    String? foundUri;
    final wanted = e.className ?? _pascalCaseFromPackageName(pkg);
    // Fallback candidates when the PascalCase guess misses. PUBLIC
    // classes only, and non-src/ libraries preferred: the alphabetical
    // walk visits src/ internals first, and 'first class with a static
    // method' over that ordering plausibly lands on a private helper —
    // a private name pasted into the generated file doesn't compile,
    // and a wrong public internal silently wraps the wrong API.
    ClassElement2? fallbackPublic;
    String? fallbackPublicUri;
    ClassElement2? fallbackSrc;
    String? fallbackSrcUri;
    for (final file in walkDartFiles(libDir).toList()..sort()) {
      final unit = await ctx.currentSession.getResolvedUnit(file);
      if (unit is! ResolvedUnitResult) continue;
      final lib = unit.libraryElement2;
      final uri = lib.uri.toString();
      final isSrc = uri.contains('/src/');
      for (final cls in lib.classes) {
        final clsName = cls.name3 ?? '';
        if (clsName == wanted) {
          found = cls;
          foundUri = uri;
          break;
        }
        if (clsName.isEmpty || clsName.startsWith('_')) continue;
        if (!cls.methods2.any((m) => m.isStatic)) continue;
        if (!isSrc) {
          fallbackPublic ??= cls;
          fallbackPublicUri ??= uri;
        } else {
          fallbackSrc ??= cls;
          fallbackSrcUri ??= uri;
        }
      }
      if (found != null) break;
    }
    final cls = found ?? fallbackPublic ?? fallbackSrc;
    final uri = foundUri ?? fallbackPublicUri ?? fallbackSrcUri;
    if (cls == null || uri == null) {
      log.warning('skal_codegen: service "${e.name}" — no class '
          '"$wanted" (and no public class with static methods) in '
          'package "$pkg". Add `class:` to the services: entry. '
          'Skipping.');
      continue;
    }
    if (found == null) {
      // A guessed class is a guess — say so at WARNING level so it
      // shows in the colored build output, not the info spam.
      log.warning('skal_codegen: service "${e.name}" — no class named '
          '"$wanted"; using "${cls.name3}" (first public class with '
          'static methods). Set `class:` explicitly if this is wrong.');
    }
    out.add(ServiceConfig(name: e.name, cls: cls, importUri: uri));
  }
  return out;
}

/// `share_plus` → `SharePlus`. Used only to guess a service's class
/// name from its package name; an explicit `class:` always wins.
///
/// Named distinctly from generator.dart's `_pascalCase` on purpose:
/// that one only uppercases the first letter (right for lowerCamelCase
/// constructor names), while this one splits on separators (right for
/// snake_case package names). Consolidating on either would silently
/// break the other's inputs — a same-named pair with different
/// semantics is a refactor trap, so the names now say what they do.
String _pascalCaseFromPackageName(String s) => s
    .split(RegExp(r'[_\-\s]+'))
    .where((p) => p.isNotEmpty)
    .map((p) => p[0].toUpperCase() + p.substring(1))
    .join();

/// Pull the `packages:` list out of a skal_codegen.yaml marker file.
/// Returns an empty list if the field is missing or malformed.
List<String> _readPackagesFromMarker(String markerYaml) {
  final parsed = loadYaml(markerYaml);
  if (parsed is! YamlMap) return const [];
  final pkgs = parsed['packages'];
  if (pkgs is! YamlList) return const [];
  return pkgs.cast<String>().toList();
}

/// One entry in the marker file's `hosts:` map — declared by the
/// dev to ask codegen for a stateful-controller adapter pattern
/// (StatefulWidget wrapper around a controller-owning factory)
/// instead of a pure prop-encoding adapter.
///
/// Sample YAML:
///
///   hosts:
///     Camera:                                             # ← key = jsxName
///       widget: CameraPreview                             # ← wrappedWidgetName
///       factory: package:skal_flutter/adapters/camera_factory.dart#createCamera
///                ↑ importUri                              ↑ factoryFnName
class _HostMarkerEntry {
  final String jsxName;
  final String wrappedWidgetName;
  final String factoryImport;
  final String factoryFnName;
  /// Optional named-param name for the controller pass-through. Null
  /// means positional (the default). See HostConfig.controllerProp.
  final String? controllerProp;
  _HostMarkerEntry(this.jsxName, this.wrappedWidgetName, this.factoryImport,
      this.factoryFnName, this.controllerProp);
}

/// Parse the marker file's `hosts:` section into raw entries. Each
/// entry still needs analyzer resolution (factory function lookup)
/// before it becomes a [HostConfig] the generator can consume.
List<_HostMarkerEntry> _readHostsFromMarker(String markerYaml) {
  final parsed = loadYaml(markerYaml);
  if (parsed is! YamlMap) return const [];
  final hosts = parsed['hosts'];
  if (hosts is! YamlMap) return const [];
  final out = <_HostMarkerEntry>[];
  for (final entry in hosts.entries) {
    final jsxName = entry.key.toString();
    final value = entry.value;
    if (value is! YamlMap) continue;
    final widget = value['widget']?.toString();
    final factory = value['factory']?.toString();
    if (widget == null || factory == null) continue;
    // Split on the `#` separator: `pkg:foo.dart#fnName`.
    final hash = factory.indexOf('#');
    if (hash < 0) continue;
    final factoryImport = factory.substring(0, hash);
    final factoryFn = factory.substring(hash + 1);
    if (factoryImport.isEmpty || factoryFn.isEmpty) continue;
    // Optional named-controller hint. Most viewport widgets take the
    // controller positionally (default); a few (WebView,
    // TextEditingController-driven forms) take it as `controller:`.
    final controllerProp = value['controllerProp']?.toString();
    out.add(_HostMarkerEntry(
        jsxName, widget, factoryImport, factoryFn, controllerProp));
  }
  return out;
}

/// Walk the analyzer context for each marker-file host entry,
/// resolving its factory function. Returns one [HostConfig] per
/// successfully-resolved entry; entries whose factory function
/// can't be found get a warning + skip.
Future<List<HostConfig>> _resolveHosts(
  AnalysisContextCollection collection,
  String pkgRoot,
  List<_HostMarkerEntry> entries,
) async {
  final ctx = collection.contexts.first;
  final out = <HostConfig>[];
  for (final e in entries) {
    // Resolve the factory import URI to a filesystem path. The URI
    // is a `package:` form; we need a file path the analyzer can
    // resolve via getResolvedUnit.
    final filePath =
        _resolvePackageUriToPath(pkgRoot, Uri.parse(e.factoryImport));
    if (filePath == null) {
      log.warning('skal_codegen: host "${e.jsxName}" — couldn\'t resolve '
          'factory import ${e.factoryImport}. Skipping.');
      continue;
    }
    final unit = await ctx.currentSession.getResolvedUnit(filePath);
    if (unit is! ResolvedUnitResult) {
      log.warning('skal_codegen: host "${e.jsxName}" — analyzer couldn\'t '
          'resolve $filePath. Skipping.');
      continue;
    }
    // Find the top-level function with the declared name.
    ExecutableElement2? factoryFn;
    for (final fn in unit.libraryElement2.topLevelFunctions) {
      if (fn.name3 == e.factoryFnName) {
        factoryFn = fn;
        break;
      }
    }
    if (factoryFn == null) {
      log.warning('skal_codegen: host "${e.jsxName}" — no top-level '
          'function `${e.factoryFnName}` in ${e.factoryImport}. Skipping.');
      continue;
    }
    // Wrapped widget import. Strategy: walk every library the factory
    // imports, look at its export namespace for a class matching the
    // declared widget name. Whichever library exports it gets used as
    // the import in the generated host adapter.
    //
    // Two cases this covers:
    //
    //   • Pub package with a barrel — camera's factory imports
    //     `package:camera/camera.dart`, which re-exports BOTH
    //     CameraController AND CameraPreview. We use the barrel
    //     directly (the only file we need to import for both).
    //
    //   • Local package, controller + widget in the same file — the
    //     ticker's factory imports the file containing both, finds
    //     the widget class there, uses the same file URI.
    //
    // Falls back to the factory's own file if no other library
    // exports the widget name. Last resort: a no-such-class compile
    // error surfaces a clear message to the dev.
    final wrappedImport =
        _findWidgetImport(unit, e.wrappedWidgetName) ?? e.factoryImport;
    out.add(HostConfig(
      jsxName: e.jsxName,
      wrappedWidgetName: e.wrappedWidgetName,
      factoryFn: factoryFn,
      factoryImport: e.factoryImport,
      wrappedWidgetImport: wrappedImport,
      controllerProp: e.controllerProp,
    ));
  }
  return out;
}

/// Resolve a `package:foo/bar.dart` URI to an absolute filesystem
/// path, via the consumer's `.dart_tool/package_config.json`.
String? _resolvePackageUriToPath(String pkgRoot, Uri pkgUri) {
  if (pkgUri.scheme != 'package' || pkgUri.pathSegments.isEmpty) return null;
  final pkgName = pkgUri.pathSegments.first;
  final libDir = resolvePackageLibDir(pkgRoot, pkgName);
  if (libDir == null) return null;
  // Everything after the package name is the path inside lib/.
  final rest = pkgUri.pathSegments.skip(1).join('/');
  return p.normalize(p.join(libDir, rest));
}

/// Walk the factory's import graph looking for a library that exports
/// a class named [wrappedWidgetName]. Returns that library's `package:`
/// URI — the right form to import in the generated host adapter.
///
/// Strategy: for each library the factory imports, examine its export
/// NAMESPACE (which includes both directly-declared classes AND
/// `export 'foo.dart'` re-exports). If the namespace contains a class
/// matching [wrappedWidgetName], use that library's URI.
///
/// Falls back to checking the factory's OWN library first — the
/// widget might be declared in the same file (Ticker's case).
String? _findWidgetImport(
  ResolvedUnitResult factoryUnit,
  String wrappedWidgetName,
) {
  final factoryLib = factoryUnit.libraryElement2;
  // Check the factory's own library first — handles "controller +
  // widget + factory in one file" (local-package case).
  if (_libraryExposes(factoryLib, wrappedWidgetName)) {
    return factoryLib.uri.toString();
  }
  // Otherwise walk each imported library's export namespace.
  for (final imp in factoryLib.firstFragment.libraryImports2) {
    final lib = imp.importedLibrary2;
    if (lib == null) continue;
    if (_libraryExposes(lib, wrappedWidgetName)) {
      return lib.uri.toString();
    }
  }
  return null;
}

/// True iff [lib]'s export namespace contains a class named [name].
/// Covers both directly-declared classes AND `export 'other.dart'`
/// re-exports — the latter is the camera case: `package:camera/camera.dart`
/// declares no classes itself, just `export 'src/...'` statements.
bool _libraryExposes(LibraryElement2 lib, String name) {
  // Direct classes (cheap check first).
  for (final cls in lib.classes) {
    if (cls.name3 == name) return true;
  }
  // exportNamespace covers re-exports. Returns a Namespace whose
  // `definedNames` map (in the new API: getter on the namespace) keys
  // the exported names → their Elements. We just need to know if the
  // name is present + resolves to a class.
  final exported = lib.exportNamespace.definedNames2;
  final el = exported[name];
  return el is ClassElement2;
}

