// GENERATED by skal_codegen — do not edit by hand.
//
// Source: fancy_text.dart
//
// One adapter per Widget class found in the source. Each adapter reads
// its constructor's named parameters from the bridge's custom-prop bag
// via NodeState.getCustomPropX(name, default), then constructs the
// real Flutter widget. The default value comes from the constructor's
// own default — if the JSX consumer omits a prop, they get the same
// behaviour as a direct Dart caller would.
//
// ignore_for_file: non_constant_identifier_names, sort_child_properties_last, unused_import, deprecated_member_use, implementation_imports, unnecessary_import, depend_on_referenced_packages

import 'package:flutter/material.dart';
import 'package:skal_flutter/skal/bridge.dart';
import 'package:skal_flutter/skal/node_state.dart';
import 'package:skal_flutter/skal/registry.dart';

import 'fancy_text.dart';

Widget _build_FancyText(NodeState n, SkalBridge bridge) {
  return FancyText(
    message: n.getCustomPropStr('message') ?? 'Hello',
    color: Color(n.getCustomPropU32('color', 0xFF000000)),
    fontSize: n.getCustomPropF32('fontSize', 14.0),
  );
}

void registerAll() {
  SkalRegistry.registerWidget('fancyText', _build_FancyText);
}
