// GENERATED by skal_codegen — do not edit by hand.
//
// Source: gradient.dart
//
// One adapter per Widget class found in the source. Each adapter reads
// its constructor's named parameters from the bridge's custom-prop bag
// via NodeState.getCustomPropX(name, default), then constructs the
// real Flutter widget. The default value comes from the constructor's
// own default — if the JSX consumer omits a prop, they get the same
// behaviour as a direct Dart caller would.
//
// ignore_for_file: non_constant_identifier_names, sort_child_properties_last, unused_import, deprecated_member_use, implementation_imports, unnecessary_import, depend_on_referenced_packages, unnecessary_cast

import 'package:flutter/material.dart';
import 'package:skal_flutter/skal/bridge.dart';
import 'package:skal_flutter/skal/node_state.dart';
import 'package:skal_flutter/skal/registry.dart';
import 'dart:convert';
import 'package:skal_flutter/skal/root.dart';

import 'gradient.dart';

/// Apply Skal's BaseProps (width / height / padding) around a generated
/// adapter's widget.
///
/// Built-in widgets (`<Box>`, `<Column>`, …) accept these. Codegen'd ones
/// construct only their own constructor's params, so before this helper
/// existed `FlutterMap height={520}` was silently ignored — the map
/// went unbounded inside a Column and overflowed by 99,477 pixels.
///
/// Cost when unset is two null-map lookups; the wrapper widgets are
/// only constructed when the prop is actually present.
///
/// [owned] names props whose bare numeric wire slot the widget's own
/// generated reader already consumes (a `double width` param), which
/// therefore must NOT be applied twice. Ownership never covers the
/// string `'fill'` form — a numeric reader ignores the string slot, so
/// the wrapper still honors `width="fill"` even on an owned dimension.
Widget _skalApplyBaseProps(
  NodeState n,
  Widget child, [
  Set<String> owned = const {},
]) {
  if (!owned.contains('padding')) {
    final pad = n.getCustomPropF32OrNull('padding');
    if (pad != null) {
      child = Padding(padding: EdgeInsets.all(pad), child: child);
    }
  }
  final w = owned.contains('width')
      ? _skalFillDim(n, 'width')
      : _skalBaseDim(n, 'width');
  final h = owned.contains('height')
      ? _skalFillDim(n, 'height')
      : _skalBaseDim(n, 'height');
  if (w != null || h != null) {
    // SkalFill, not SizedBox: `'fill'` maps to double.infinity, and a
    // raw SizedBox(∞) inside an unbounded axis (codegen widget in a
    // Row, fill-height in a Column) throws and silently blanks the
    // whole layout flush. SkalFill fills when bounded, wraps when not.
    child = SkalFill(width: w, height: h, child: child);
  }
  return child;
}

/// The `'fill'`-only read for dimensions the widget itself owns
/// numerically: its own param handles numbers, but its F32 reader
/// cannot see the string slot, so the wrapper still supplies
/// "as much as the parent allows".
double? _skalFillDim(NodeState n, String name) =>
    n.getCustomPropStr(name) == 'fill' ? double.infinity : null;

/// Read a dimension prop. Numbers pass through; the string `'fill'`
/// means "as much as the parent allows", matching the built-in
/// widgets' `width="fill"`.
double? _skalBaseDim(NodeState n, String name) {
  final v = n.getCustomPropF32OrNull(name);
  if (v != null) return v;
  if (n.getCustomPropStr(name) == 'fill') return double.infinity;
  return null;
}

Alignment _skalParseAlignment(dynamic v, {Alignment def = Alignment.center}) {
  if (v is String) {
    switch (v) {
      case 'topLeft':
        return Alignment.topLeft;
      case 'topCenter':
        return Alignment.topCenter;
      case 'topRight':
        return Alignment.topRight;
      case 'centerLeft':
        return Alignment.centerLeft;
      case 'center':
        return Alignment.center;
      case 'centerRight':
        return Alignment.centerRight;
      case 'bottomLeft':
        return Alignment.bottomLeft;
      case 'bottomCenter':
        return Alignment.bottomCenter;
      case 'bottomRight':
        return Alignment.bottomRight;
    }
  }
  if (v is List && v.length == 2) {
    return Alignment((v[0] as num).toDouble(), (v[1] as num).toDouble());
  }
  return def;
}

Color _skalParseColor(dynamic v) {
  if (v is int) return Color(v);
  if (v is String) {
    var s = v.startsWith('#') ? v.substring(1) : v;
    if (s.length == 6) s = 'FF$s';
    return Color(int.parse(s, radix: 16));
  }
  return const Color(0xFF000000);
}

Gradient? _skalParseGradient(String? json) {
  if (json == null || json.isEmpty) return null;
  final m = jsonDecode(json) as Map<String, dynamic>;
  final colors = (m['colors'] as List).map(_skalParseColor).toList();
  final stops = (m['stops'] as List?)
      ?.cast<num>()
      .map((n) => n.toDouble())
      .toList();
  switch (m['type']) {
    case 'radial':
      return RadialGradient(
        colors: colors,
        stops: stops,
        radius: (m['radius'] as num?)?.toDouble() ?? 0.5,
        center: _skalParseAlignment(m['center'], def: Alignment.center),
      );
    case 'sweep':
      return SweepGradient(
        colors: colors,
        stops: stops,
        startAngle: (m['startAngle'] as num?)?.toDouble() ?? 0.0,
        endAngle: (m['endAngle'] as num?)?.toDouble() ?? 6.283185307,
        center: _skalParseAlignment(m['center'], def: Alignment.center),
      );
    default: // 'linear' or missing
      return LinearGradient(
        colors: colors,
        stops: stops,
        begin: _skalParseAlignment(m['begin'], def: Alignment.centerLeft),
        end: _skalParseAlignment(m['end'], def: Alignment.centerRight),
      );
  }
}

Widget _build_Painted(NodeState n, SkalBridge bridge) {
  return _skalApplyBaseProps(
    n,
    Painted(gradient: _skalParseGradient(n.getCustomPropStr('gradient'))),
  );
}

Widget _build_Banner(NodeState n, SkalBridge bridge) {
  return _skalApplyBaseProps(
    n,
    Banner(
      gradient:
          (_skalParseGradient(n.getCustomPropStr('gradient')) as Gradient),
      label: n.getCustomPropStr('label') ?? 'banner',
    ),
  );
}

void registerAll() {
  SkalRegistry.registerWidget('painted', _build_Painted);
  SkalRegistry.registerWidget('banner', _build_Banner);
}
