// GENERATED by skal_codegen — do not edit by hand.
//
// Source: positional.dart
//
// One adapter per Widget class found in the source. Each adapter reads
// its constructor's named parameters from the bridge's custom-prop bag
// via NodeState.getCustomPropX(name, default), then constructs the
// real Flutter widget. The default value comes from the constructor's
// own default — if the JSX consumer omits a prop, they get the same
// behaviour as a direct Dart caller would.
//
// ignore_for_file: non_constant_identifier_names, sort_child_properties_last, unused_import, deprecated_member_use, implementation_imports, unnecessary_import, depend_on_referenced_packages

import 'package:flutter/material.dart';
import 'package:skal_flutter/skal/bridge.dart';
import 'package:skal_flutter/skal/node_state.dart';
import 'package:skal_flutter/skal/registry.dart';
import 'package:skal_flutter/skal/root.dart';

import 'positional.dart';

Widget _build_Padded(NodeState n, SkalBridge bridge) {
  return Padded(
    n.getCustomPropU32('padding', 0),
    child: n.childCount > 0
        ? SkalNode(
            nodeId: n.childAt(0),
            bridge: bridge,
            key: ValueKey<int>(n.childAt(0)),
          )
        : const SizedBox.shrink(),
  );
}

Widget _build_Tagged(NodeState n, SkalBridge bridge) {
  return Tagged(
    n.getCustomPropStr('label') ?? '',
    n.getCustomPropU32('badge', 0),
  );
}

void registerAll() {
  SkalRegistry.registerWidget('padded', _build_Padded);
  SkalRegistry.registerWidget('tagged', _build_Tagged);
}
