// GENERATED by skal_codegen — do not edit by hand.
//
// Source:
//
// One adapter per Widget class found in the source. Each adapter reads
// its constructor's named parameters from the bridge's custom-prop bag
// via NodeState.getCustomPropX(name, default), then constructs the
// real Flutter widget. The default value comes from the constructor's
// own default — if the JSX consumer omits a prop, they get the same
// behaviour as a direct Dart caller would.
//
// ignore_for_file: non_constant_identifier_names, sort_child_properties_last, unused_import, deprecated_member_use, implementation_imports, unnecessary_import, depend_on_referenced_packages, unnecessary_cast

import 'package:flutter/material.dart';
import 'package:skal_flutter/skal/bridge.dart';
import 'package:skal_flutter/skal/node_state.dart';
import 'package:skal_flutter/skal/registry.dart';
import 'package:skal_flutter/skal/services.dart';
import 'dart:convert';
import 'package:skal_flutter/skal/handles.dart';
import 'service_class.dart';

Map<String, dynamic>? _skalDecodeMap(Object? raw) {
  if (raw == null) return null;
  if (raw is Map<String, dynamic>) return raw;
  if (raw is String) {
    if (raw.isEmpty) return null;
    try {
      final decoded = jsonDecode(raw);
      if (decoded is Map<String, dynamic>) return decoded;
    } catch (_) {}
  }
  return null;
}

Object? _skalEncodeBattery(Battery? v) {
  if (v == null) return null;
  return <String, Object?>{
    'level': v.level,
    'charging': v.charging,
    'health': v.health.name,
  };
}

LocationAccuracy? _skalEnumArgLocationAccuracy(Object? raw) {
  if (raw is String) {
    for (final e in LocationAccuracy.values) {
      if (e.name == raw) return e;
    }
    return null;
  }
  if (raw is num) {
    final i = raw.toInt();
    if (i < 0 || i >= LocationAccuracy.values.length) return null;
    return LocationAccuracy.values[i];
  }
  return null;
}

Region? _skalParseRegion(Object? raw) {
  final j = _skalDecodeMap(raw);
  if (j == null) return null;
  return Region(
    latitude: ((j['latitude']) as num?)?.toDouble() ?? 0.0,
    longitude: ((j['longitude']) as num?)?.toDouble() ?? 0.0,
    radiusMeters: ((j['radiusMeters']) as num?)?.toDouble() ?? 100.0,
    label: (j['label']) as String? ?? '',
  );
}

void _registerService_geo() {
  registerService('geo', (String method, List<Object?> args) {
    switch (method) {
      case 'acquire':
        return (skalHandleOf)(Geo.acquire());
      case 'attach':
        return Geo.attach(
          (skalHandleArg<NativeHandle>((args.isNotEmpty ? args[0] : null)))!,
        );
      case 'battery':
        return (_skalEncodeBattery)(Geo.battery());
      case 'coversAll':
        return Geo.coversAll(
          ((((args.isNotEmpty ? args[0] : null)) is List
                  ? [
                      for (final e
                          in ((args.isNotEmpty ? args[0] : null)) as List)
                        _skalParseRegion(e),
                    ].whereType<Region>().toList()
                  : null) ??
              const []),
        );
      case 'currentAccuracy':
        return ((LocationAccuracy v) => v.name)(Geo.currentAccuracy());
      case 'describe':
        return Geo.describe();
      case 'getCurrentPosition':
        return Geo.getCurrentPosition(
          accuracy:
              (_skalEnumArgLocationAccuracy(
                (args.isNotEmpty ? args[0] : null),
              ) ??
              LocationAccuracy.medium),
        );
      case 'history':
        return Geo.history(
          ((((args.isNotEmpty ? args[0] : null)) as num?)?.toInt() ?? 0),
        );
      case 'isInside':
        return Geo.isInside(
          (_skalParseRegion((args.isNotEmpty ? args[0] : null)))!,
          ((((args.length > 1 ? args[1] : null)) as num?)?.toDouble() ?? 0.0),
          ((((args.length > 2 ? args[2] : null)) as num?)?.toDouble() ?? 0.0),
        );
      case 'pickAccuracy':
        return Future.value(
          Geo.pickAccuracy(),
        ).then((LocationAccuracy v) => v.name);
      case 'positionStream':
        return Geo.positionStream(
          distanceFilter:
              ((((args.isNotEmpty ? args[0] : null)) as num?)?.toDouble() ??
              0.0),
        );
      case 'sharePaths':
        return Geo.sharePaths(
          ((((args.isNotEmpty ? args[0] : null)) is List
                  ? List<String>.from(
                      ((args.isNotEmpty ? args[0] : null)) as List,
                    )
                  : null) ??
              const []),
        );
      case 'startTracking':
        return Geo.startTracking(
          (((args.isNotEmpty ? args[0] : null)) as String? ?? ''),
        );
    }
    throw 'skal service "geo": unknown method "$method"';
  });
}

void registerAll() {
  _registerService_geo();
}
