// GENERATED by skal_codegen — do not edit by hand.
//
// Source: value_class.dart
//
// One adapter per Widget class found in the source. Each adapter reads
// its constructor's named parameters from the bridge's custom-prop bag
// via NodeState.getCustomPropX(name, default), then constructs the
// real Flutter widget. The default value comes from the constructor's
// own default — if the JSX consumer omits a prop, they get the same
// behaviour as a direct Dart caller would.
//
// ignore_for_file: non_constant_identifier_names, sort_child_properties_last, unused_import, deprecated_member_use, implementation_imports, unnecessary_import, depend_on_referenced_packages

import 'package:flutter/material.dart';
import 'package:skal_flutter/skal/bridge.dart';
import 'package:skal_flutter/skal/node_state.dart';
import 'package:skal_flutter/skal/registry.dart';
import 'dart:convert';

import 'value_class.dart';

Map<String, dynamic>? _skalDecodeMap(Object? raw) {
  if (raw == null) return null;
  if (raw is Map<String, dynamic>) return raw;
  if (raw is String) {
    if (raw.isEmpty) return null;
    try {
      final decoded = jsonDecode(raw);
      if (decoded is Map<String, dynamic>) return decoded;
    } catch (_) {}
  }
  return null;
}

Color _skalParseColor(dynamic v) {
  if (v is int) return Color(v);
  if (v is String) {
    var s = v.startsWith('#') ? v.substring(1) : v;
    if (s.length == 6) s = 'FF$s';
    return Color(int.parse(s, radix: 16));
  }
  return const Color(0xFF000000);
}

GeoBounds? _skalParseGeoBounds(Object? raw) {
  final j = _skalDecodeMap(raw);
  if (j == null) return null;
  return GeoBounds(
    _skalParseGeoPoint(j['southwest'])!,
    _skalParseGeoPoint(j['northeast'])!,
  );
}

GeoPoint? _skalParseGeoPoint(Object? raw) {
  final j = _skalDecodeMap(raw);
  if (j == null) return null;
  return GeoPoint(
    ((j['lat']) as num?)?.toDouble() ?? 0.0,
    ((j['lng']) as num?)?.toDouble() ?? 0.0,
  );
}

MapInit? _skalParseMapInit(Object? raw) {
  final j = _skalDecodeMap(raw);
  if (j == null) return null;
  return MapInit(
    initialCenter: _skalParseGeoPoint(j['initialCenter'])!,
    initialZoom: ((j['initialZoom']) as num?)?.toDouble() ?? 13.0,
    keepAlive: (j['keepAlive']) as bool? ?? false,
    bounds: _skalParseGeoBounds(j['bounds']),
    backgroundColor: ((j['backgroundColor']) == null
        ? null
        : _skalParseColor(j['backgroundColor'])),
  );
}

Widget _build_MiniMap(NodeState n, SkalBridge bridge) {
  return MiniMap(
    init: _skalParseMapInit(n.getCustomPropStr('init'))!,
    cameraBounds: _skalParseGeoBounds(n.getCustomPropStr('cameraBounds')),
    label: n.getCustomPropStr('label') ?? 'map',
  );
}

void registerAll() {
  SkalRegistry.registerWidget('miniMap', _build_MiniMap);
}
